#+latex_class: article_usual2
# erases make title
# #+BIND: org-export-latex-title-command ""

# fucks all the maketitlestuff just to be sure
#+OPTIONS: num:nil
#+OPTIONS: toc:nil
#+OPTIONS: h:5



#+BEGIN_SRC R :session calc :exports none :results values drawer :dir /home/johannes/
library(jtls)
dt_nbrs <- fread("/home/johannes/Dropbox/phd/papers/closing/misc/nbrs.csv")
wd_nbrs(dt_nbrs)
## quit(save="no")
#+end_src

#+RESULTS:
:results:
# meanhaz
#+MACRO: meanhaz_upto_20 0.89%
#+MACRO: meanhaz_upto_30 0.91%
#+MACRO: meanhaz_upto_40 0.78%
#+MACRO: meanhaz_upto_100 0.79%


# pltcfgs
#+MACRO: ynkplt_p_vrblcvrg_ugrpd (eval (concat "#+label: fig:p_vrblcvrg_ugrpd\n" "#+caption: PMDB variable coverage by museum status\n" "#+attr_latex: :width 19cm\n" "[[file:../figures/p_vrblcvrg_ugrpd.pdf]]"))
#+MACRO: ynkplt_p_vrblcvrg (eval (concat "#+label: fig:p_vrblcvrg\n" "#+caption: PMDB variable coverage by museum status and variable group\n" "#+attr_latex: :width 19cm\n" "[[file:../figures/p_vrblcvrg.pdf]]"))
#+MACRO: ynkplt_p_vrblcvrg_ratio (eval (concat "#+label: fig:p_vrblcvrg_ratio\n" "#+caption: PMDB variable coverage (abs/rel prop) by museum status and variable group\n" "#+attr_latex: :width 18cm\n" "[[file:../figures/p_vrblcvrg_ratio.pdf]]"))
#+MACRO: ynkplt_p_surv (eval (concat "#+label: fig:p_surv\n" "#+caption: Private Museum Survival probability\n" "#+attr_latex: :width 14cm\n" "[[file:../figures/p_surv.pdf]]"))
#+MACRO: ynkplt_p_hazard (eval (concat "#+label: fig:p_hazard\n" "#+caption: Private Museum hazard function\n" "#+attr_latex: :width 16cm\n" "[[file:../figures/p_hazard.pdf]]"))
#+MACRO: ynkplt_p_agedens (eval (concat "#+label: fig:p_agedens\n" "#+caption: Age distribution of private museums\n" "#+attr_latex: :width 17cm\n" "[[file:../figures/p_agedens.pdf]]"))
#+MACRO: ynkplt_p_yeardens (eval (concat "#+label: fig:p_yeardens\n" "#+caption: Private Museum-year Distribution\n" "#+attr_latex: :width 19cm\n" "[[file:../figures/p_yeardens.pdf]]"))
#+MACRO: ynkplt_p_coxphdiag_more (eval (concat "#+label: fig:p_coxphdiag_more\n" "#+caption: Model Diagnostics\n" "#+attr_latex: :width 19cm\n" "[[file:../figures/p_coxphdiag_more.pdf]]"))


# figlbls
#+MACRO: refplt_p_vrblcvrg_ugrpd \ref{fig:p_vrblcvrg_ugrpd}
#+MACRO: refplt_p_vrblcvrg \ref{fig:p_vrblcvrg}
#+MACRO: refplt_p_vrblcvrg_ratio \ref{fig:p_vrblcvrg_ratio}
#+MACRO: refplt_p_surv \ref{fig:p_surv}
#+MACRO: refplt_p_hazard \ref{fig:p_hazard}
#+MACRO: refplt_p_agedens \ref{fig:p_agedens}
#+MACRO: refplt_p_yeardens \ref{fig:p_yeardens}
#+MACRO: refplt_p_coxphdiag_more \ref{fig:p_coxphdiag_more}


# reftbl
#+MACRO: reftbl_t_testtable \ref{tbl:t_testtable}
#+MACRO: reftbl_t_coxzph \ref{tbl:t_coxzph}
#+MACRO: reftbl_t_reg_coxph \ref{tbl:t_reg_coxph}
#+MACRO: reftbl_t_sumstats \ref{tbl:t_sumstats}
:end:


* Private museum closures

** Abstract: TODO

** Introduction

In recent years, private, collector-run museums have seen an unprecedented proliferation.
#
These museums, run by individual collectors, constitute an addition to established organizational forms of art provision such as museums run/financed by the state or foundations and associations.
#
Despite their occasionally spectacular/sensationalist press coverage (TODO:ref), these institutions and the motivations of their founders have remained remarkably intransparent.
#
Financed in large parts by their founders' private wealth, few reporting requirements exists; and while some founders highlight their charitable and distintersted intentions in media coverage, such statements intended for a public audience might not necessarily accurately reflect underlying founder motivations.



This study (attempts to) elucidate the hard-to-observe collector motivations by studying one of the most decisive actions that their founder can take: the decision to close the museum.
#
Besides investigating the longevity of members of this new organizational form, this study gives insights into the motivations and decision making of founders.
# 
In other words, what can the factors leading to the closure of private museums tell us about the internal processes and dependence relationships of these institutions, as well as about the motivations of their founders?





# interrelated question of sustainability/longevity and collector decision making

# Thinking about private museums can take place along several discourses:
# - celebratory, disinterested, giving back to community 
# - critical: self-promotional, focus on inequality/legitimacy/status

#+latex: \bigbreak
#+latex: \noindent
Private museums:
- founded by collector -> needs to have amassed substantial art collection
- building of its own, limited public/corporate funding, has to be visitable -> requires substantial resources


** Theory

TODO: the theory section (including the hypotheses) is mostly copied from an earlier literature review on organizational closure, and while there are some references to how it could relate to private museums, it isn't integrated with the current focus on collector decision making and private museum sustainability. 

*** Size

Larger NPOs are generally found to have lower mortality rates [[parencite:&Hager_1999_demise;&Duckles_Hager_Galaskiewicz_2005_close]], with size being measured through indicators such as assets [[parencite:&Lu_Shon_Zhang_2019_dissolution]], number of employees parencite:&Bielefeld_1994_survival and volunteers [[parencite:&Fernandez_2007_dissolution]], or revenues parencite:&Searing_2020_zombies.
#
Smaller organiations are argued to face greater difficulty in collecting resources and recruiting staff as well as relatively higher costs for administration and regulation [[parencite:&Helmig_Ingerfurth_Pinz_2013_nonprofit]], while being less able to diversify or benefit from economies of scale [[parencite:&Hager_1999_demise]]. 
#
Larger organizations are also argued to be able to waste some resources during normal times which can be utilized effectively during situations of crisis without having to scale back services (which generate revenue) [[parencite:&Hager_2001_vulnerability]] and hence avoid downsizing, which can lead to dissolution [[parencite:&Duckles_Hager_Galaskiewicz_2005_close;&Bielefeld_1994_survival]]. 

#+latex: \bigbreak
#+latex: \noindent
*H_size*: Larger private museums are less likely to close than smaller ones.




*** Resource diversification

A substantial amount of literature focuses on resources as resource depletion is a leading cause of (nonprofit) organizational demise. 
#
Diversification (i.e. a multitude of funding sources) is found to reduce mortality [[parencite:&Fernandez_2007_dissolution;&Bielefeld_1994_survival;&Hager_2001_vulnerability;&Lu_Shon_Zhang_2019_dissolution]]; similarly volatility (rapid changes in revenues) is found to increase mortality [[parencite:&Mayer_2022_slimmer]]. 
#
While private museums are likely already generally leaning toward higher concentration than NPOs generally due to high reliance on the financial contributions of the founder-collector, there might still be variation in the degree of revenue concentration as museums might vary in the proportion of revenues received from ticket prices, restaurants, cafes, museum shops or other activities. 

#+latex: \bigbreak
#+latex: \noindent
*H_diversification*: Private museums with more diversified revenue channels are less likely to close than more diversified ones.

*** Age


The age of an organization is considered in different ways to be related to closing.
#
What started with liability of newness [[parencite:&Stinchcombe_1965_structure]], which posited that organizational mortality decreases over time due to acquisition of capabilities and connections, has lead to a number of extensions [[parencite:&Carroll_Khessina_2019_demography;&Hannan_1998_mortality]]:
#
Liability of adolescence argues that shortly after foundings organizations can still draw on endowments, the expiration of which leads to a peak of mortality some time after opening.
#
While according to this view mortality still decreases after the peak as the organization becomes more established, other perspectives argue also for a positive relationship between age and mortality:
# 
According to the liability of obsolescence paradigm the environment changes faster than organizations which are seen as relatively constrained by inertia, which therefore leads to declining fitness and survival chances.
#
Similar, according to "liability of senescence" capabilities/routines/coalitions can constrain the actions of organizations.
#
Given such conflicting predictions, [[textcite:&Carroll_Khessina_2019_demography]] propose to model age dependence with piece-wise constant hazard models (rather than parametric models) to estimate age-specific effects which can, but do not have to, indicate a relationship between age and mortality.



*** Organizational transformation
#
[[textcite:&Carroll_Khessina_2019_demography]] argue that transformation of core features of organizations such as changes in technology or authority can have divergent consequences. 
#
On the one hand, it can disrupt internal routines as well as external customer relations by decreasing (perceived) reliability and accountability as the change upsets established perceptions, which can lead to higher mortality. 
#
On the other hand, organizational transformation can be necessary to adapt to a changing environment, and hence be beneficial for survival.



In the case of private museums, the death of the founder might constitute a substantial transformation as authority has to be reconfigured.
# 
Abandonment by insiders (such as divorce of directors) has been argued to contribute to NPO closure [[parencite:&Duckles_Hager_Galaskiewicz_2005_close]].[fn::Conflict is similarly argued to contribute to closure but is not testable with the current data.]
#
Even if plans have been made for a handover, the new leaders might not share the same commitment to art as the original founder, potentially decreasing museum sustainability. 
# question is if death is so important, or rather restructuring of authority


In the case of private museums, founder death has been speculated to pose a challenge to their sustainability as "seldom do heirs share a similar passion or wish to take on the financial burden of maintaining private museum indefinitely" [[parencite:&Walker_2019_collector p.234]].
#
# 
However, existing research has not found a straightforward effect of founder death on museum closure [[parencite:&Velthuis_Gera_forthcoming_fragility;&Velthuis_etal_2023_boom]].
#
Nevertheless as previous research has relied primarily on descriptive statistics, investigating founder death in a multivariate survival model allows to investigate the effect of founder death with higher precision.
#


#+latex: \bigbreak
#+latex: \noindent
*H_death*: A private museum is more likely to close after the death of the founder.


*** legitimacy/understandability 
# provide legitimacy

Legitimacy is necessary for being understood/tolerated/supported by other the organizations in the environemnt; to the extent that this influences resource acquisition it could influence survival prospects.
#
While [[textcite:&Bielefeld_1994_survival]] finds that NPOs who pursue less legitimation strategies (obtaining endorsements, lobbying or contributing to local causes) are more likely to close, other studies find limited impact of legitimacy on survival, both when measured via density parencite:&Bogaert_etal_2014_ecological or from archival sources and interviews [[parencite:&Fernandez_2007_dissolution]].
#
In the context of private museums, decline of legitimacy/status could lead to lower visitor numbers, less discounts from art dealers, less government grants (?) or lower chances on collaborations with other museums or corporations, resulting in lower revenues and higher acquisition costs.


Legitimacy might be obtained by isomorphism, i.e. adopting features associated with blueprints [[parencite:&diMaggio_1983_iron]].
#
Understandability/sense-making [[parencite:&Glynn_Abzug_2002_names]] might thus be limited if an organization is atypical [[parencite:&Rosch_1975_family]], i.e. displays an unusual combination of features.
#
In the case of private museums, such cases might be combinations of features from house museums (e.g. accessibility only by appointment) with full-service museums (e.g. extensive activities). 
#
Next to "hard" organizational features, adherence to naming conventions has been found to enhance legitimacy [[parencite:&Glynn_Abzug_2002_names]]; organizations that adhere to field norms about name length, name ambiguity (usage of artificial names) and name domain specificity (mentioning industry) were judged more legitimate. 
# 
However, the category of museums could be relatively flexible (for example, it is generally not subject to state regulation), which might result in a relatively high tolerance of diversity as "anything goes" and hence limited "devaluation" of non-conforming/atypical members. 

#+latex: \bigbreak
#+latex: \noindent
*H_typicality*: Atypical private museums have higher mortality rates.

Legitimacy might also be measured by inclusion in industry registers, such as the Museum of the World (MOW) database [[parencite:&deGruyter_2021_MOW]].

#+latex: \bigbreak
#+latex: \noindent
*H_mow*: Private museums included in the MOW database have higher survival chances.



*** reputation

Reputation has been argued to enhance organizational survival [[parencite:&Rao_1994_reputation]].
#
However, reputation effects could also be a spurious effect of organizational capabilities as more competent organizations are more able to both aquire reputation through certification contests and survive in long run parencite:&Goldfarb_Zavyalova_Pillai_2018_Rao.
#
Recognition might be measured by inclusion in the Artnews top 200 collector ranking.

#+latex: \bigbreak
#+latex: \noindent
*H_artnews*: Private museums of collectors included in the Artnews top 200 collector ranking are less likely to close. 


** Data and Methods

*** Dependent Variable
A newly constructed database (see [[textcite:&Velthuis_etal_2023_boom]] for details) is used to measure museum survival.
#
The unit of analysis is country year.
#
The main dependenent variable is an indicator of museum closure, which takes for the museums which close in the year of their closure, and zero otherwise.
#
Typically for survival data, museums that do not close during the observation period are right-censored, i.e. for such museums the dependent variable is zero for all years.

*** Predictors
TODO: the current do not yet measure all the concepts discussed in the theory, and some are not justified yet on theoretical grouns (founder name in museum name, gender, density).

#+latex: \bigbreak
#+latex: \noindent
On the level of the founder, gender constitutes a time-invariant variable; with possible values being male, female and couple.
#
Founder death is constructed as a time-varying covariate, and is set to 1 for museum-years after the death of the founder. 

On the museum level, self-identification measures whether a the name of a museum includes the term "Museum", "Foundation", "Collection", or other (such as "Villa", "Institute", "Center" or "Gallery", which are grouped together as they are less frequent).
#
Further analyzing the name, a binary indicator also measures whether the name of the founder is included.
#
Finally, a binary predictor measures whether the museum is included in the "Museums of the World" database [[parencite:&deGruyter_2021_MOW]], a database containig 55k museums.
#



On the level of the environment, the density (number) of private museum per country is included both in linear and squared form.
#
Organizational theory [[parencite:&hannan89_organ]] predicts a U-shaped relationship between density and mortality: While at low levels, increases in the number of organizations are argued to primarily increase legitimacy/familiarity and lower exit rates, increases at higher numbers increase the competition over resources and thereby raise mortality rates.

#+latex: \bigbreak
#+latex: \noindent
TODO: 
- add museum size/diversification indicators: most museum-level variables that we collected have many missing values (figure {{{refplt_p_vrblcvrg_ratio}}}), so it's challenging to get good estimates out of them. I'm thinking of using some dimensionality reduction like PCA.  
- add inclusion in Artnews collector ranking
- add Tax incentives (country-level)
- expand densities: 
  - per capita
  - include MOW museums, for now density is based only on private museums
  - within proximate environment (circle of X kilometer around museum), rather than country-level
- account for clustering within countries/regions

*** Analytical framework


First, we investigate the relationship between age and closing descriptively using hazard rates and the Kaplan-Meier survival function.
#
This non-parametric method estimates the hazard rate as the conditional probability of exiting at time t_i given being alive as $h(t_i) = \frac{d_i}{n_i}$, (with $n_i$ as the number of units at risk at time $t_i$ and $d_i$ as the number of exits at time $t_i$), and the survival function as the product of these conditional probabilities as $S(t) = \prod_{t_i \geq t} \left(1-h(t_i) \right)$.



In a second step, I use Cox proportional hazard models which estimate the relationship between covariates and the hazard rate.
#
The Cox-proportional hazard model has the form $h(t,\mathbf{x}) = h_0(t) \psi$, with $\psi = \exp(\sum_{j=1}^p x_j \beta_j)$, with $h(t)$ as the hazard rate, $h_0(t)$ as the baseline hazard rate, $\mathbf{x}$ as the set of variables indexed by $j$, and $\beta$ as the coefficient of the $j$ -th variable.
#
Estimation via partial maximum likelihood allows estimation of \beta without estimating the baseline hazard rate, which is therefore not constrained to a parametric form. 
# 
Coefficients are interpeted as log hazard ratios, i.e. as multipliers of the baseline hazard rate. 



This model assume proportional hazards, i.e. that the coefficient of a variable stays constant over time, which indicates that for a variable at every time point the hazard ratio is the same.
#
So far, tests show a violation of the proportionality assumption only for the variable indicating whether the museum name includes the name of the founder  which furthermore is marginal as it slightly varies by the type of time transformation (table {{{reftbl_t_coxzph}}}, figure {{{refplt_p_coxphdiag_more}}}).


** Results

*** Summary statistics

In total, 479 private museums are included in the database, 53 of them have closed.
#
7282 museum-years are observed.

#+latex: \noindent


#+INCLUDE: "../tables/t_sumstats_wcpF.tex" export latex

Table {{{reftbl_t_sumstats}}} shows summary statistics for all variables.

*** Hazard rate and Age Dependence

{{{ynkplt_p_hazard}}}

{{{ynkplt_p_surv}}}


Figure {{{refplt_p_hazard}}} shows the hazard rate over time, figure {{{refplt_p_surv}}} the corresponding survival probability.
#
The hazard rate doubles over the first 10 years from approximately 0.45% to 0.9%, at which value it approximately stays constant for the next 20 years, after which it appears to decline.
#
However, the decline after thirty years is presumably less certain as very few private museums have already reached this age (figure {{{refplt_p_agedens}}}).


The increase in the first years is likely due to endowments: As the establishment of a museum requires considerable resources, their founders appear to allocate enough resources to keep the risk of closure small in the first years after opening.
#
Given that founders are likely aware that their endeavor is unlikely to generate a profit, they are not vulnerable to the liability of newness [[parencite:&Stinchcombe_1965_structure]].
#
The relative stability of the hazard rate after ten years has no correspondence in classical theories on age dependence:
#
While an increase in mortality as observed here is predicted by the idea of "liability of adolescence" [[parencite:&Carroll_Khessina_2019_demography]], this framework also predicts a decline in mortality after a peak due to becoming established.
# 
Furthermore, while "liability of obsolescence" and "liability of senescence" (ibid.) predict higher mortality for older organizations due to mismatch with the environment and inertia (inflexible internal routines), it seems questionable whether museums would have reached obsolescence or senescence already after ten years.
#
Furthermore, the applicability of obsolescence and senescence might be limited for non-profit organizations.


Overall the entire life span, the average hazard rate is {{{meanhaz_upto_100}}}, which allows comparison to other studies of NPO closure.
# 
While after very cursory search of the literature I did not find a systematic literature review or meta-analysis, a number of individual studies had investigated similar populations (see table \ref{tbl:litreview}).

#+caption: Hazard rates in studies of museums and other non-profits
#+label: tbl:litreview
|------------------------------------------------+--------------+------------------+------------------------|
| study                                          | population   | avg. hazard rate | data source            |
|------------------------------------------------+--------------+------------------+------------------------|
| [[cite:&Hager_2001_vulnerability]]                 | Art Museums  |             2.4% | IRS                    |
| [[cite:&Gordon_etal_2013_insolvency]]              | Museums      |             0.7% | IRS                    |
|------------------------------------------------+--------------+------------------+------------------------|
| cite:&Hager_2001_vulnerability                 | all Art NPOs |             2.8% | IRS                    |
| cite:&Gordon_etal_2013_insolvency              | all Art NPOs |            2.08% | IRS                    |
| cite:&Gordon_etal_2013_insolvency              | all NPOs     |            1.58% | IRS                    |
| [[cite:&Hager_Galaskiewicz_Larson_2007_liability]] | NPOs         |            1.25% | own data               |
| [[cite:&Clifford_2018_reinforcing]]                | Charities    |            2%-5% | Reg. of Charities (UK) |
| [[cite:&Mayer_2022_slimmer]]                       | NPOs         |            0.17% | IRS                    |
|------------------------------------------------+--------------+------------------+------------------------|

# this is kinda the main comparison...
[[textcite:&Hager_2001_vulnerability]] and [[textcite:&Gordon_etal_2013_insolvency]] both study NPOs more generally, but report survival estimates by organizational form.
#
At the moment it is not clear which factors account for their hazard rates to differ substantially, but it might be due to selection criteria.
#
Both these studies also report substantial variation in hazard rates between organizational forms.
#
While preliminary results indicate that private museums have dissolution rates lower or similar to museums and non-profit organizations generally, more research is needed to establish the comparability of these hazard rates.


# The Kaplan-Meier survival probability is around 75% after thirty years (figure {{{refplt_p_surv}}}).






#+latex: \noindent
TODO:
- get confidence interval for hazard rate
- see how age can be integrated into survival models (linear term doesn't work)
- expand comparison to other studies



*** Regression Results

#+INCLUDE: "../tables/t_reg_coxph_wcpF.tex" export latex

Table {{{reftbl_t_reg_coxph}}} shows the results of Cox proportional hazard regression model.
#
Founder-level variables are not substantial, as neither gender nor the death of the founder is associated with a significant difference in private museum closure.
#
While there is no particular reason to expect a gender effect, the not substantially higher likelihood for museums to close after their founder has died indicates that private museums might be less dependent on the mood of a single person (or couple), and have in fact become institutionalized to an extent that heirs of founders feel as motivated to continue the original founders' efforts as these founders themselves.


Museums which include the term "museum" in their name are the least likely to close, while those with the term "foundation" or "collection" have higher closure rates (but not significantly higher).
#
Museums which include neither of these are the most likely to close, and have mortality rates more than three times as high ($e$^1.12 = 3.06 , p<0.01) than institutions including the term "museum".
#
The usage of unconventional names might reflect adherence to museum standards which makes museums more understandable and familiar to third parties (e.g. audiences, other museums, companies or the government) and thereby facilitates interactions which are beneficial for long-term survival (e.g. attracting visitors, cooperations, sponsorships or subsidies).
# 
However, as founders can choose their museum’s name arbitrarily, they might choose a name without reference to organizational forms associated with perpetuity precisely because their intention is not an institution enduring in perpetuity but rather a more temporally bounded project.

Inclusion of founder name is not significantly associated with mortality rates.
#
While generally organizations whose name include the name of their founder might be more centered around the founder, and hence display higher inertia, making them less able to adapt to changing environments (TODO: add reference, very speculative!!), these results indicate that it does not seem to be case for private museums.


Museums included in the Museum of the World Database are $e$^-0.97 = 0.38 times as likely to close than museums which are not, yet this result might be produced by different mechanisms.
#
On the one hand, it might reflect that larger and richer institutions are both more likely to be noticed by the MOW and more likely to survive (MOW inclusion would then be a proxy for resources).
#
On the other hand, similar to unconventional naming patterns, lack of inclusion in the MOW could be an indicator of deviance from museum standards, which could increase the unfamiliarity of the museum vis-a-vis third parties, reducing the chance of survival-enhancing interactions.
#
Thirdly, the MOW effect might be endogenous: As no longitudinal MOW data is available, museums might be absent in the MOW because they have closed (TODO: Because of this I wonder if it even makes even sense to include MOW).

Environmental variables show no association with mortality (TODO: this might be due to no per capita numbers).
#
While the density-dependence paradigm predicts a negative effect of numbers of organizations on closing rate at low numbers (due to legitimacy, i.e. growing familiarity with a new organizational form), and a positive effect at high numbers (due to competition over resources), neither relationship is significant in the case of private museums. 




#+Latex: \begin{sloppypar}
#+Latex: \printbibliography
#+Latex: \end{sloppypar}




* Appendix

{{{ynkplt_p_yeardens}}}

{{{ynkplt_p_agedens}}}


# #+latex: \begin{landscape}
{{{ynkplt_p_coxphdiag_more}}}

# #+latex: \end{landscape}

#+INCLUDE: "../tables/t_coxzph_wcpF.tex" export latex

{{{ynkplt_p_vrblcvrg_ratio}}}
