#+latex_class: article_egos
# erases make title
# #+BIND: org-export-latex-title-command ""

# fucks all the maketitlestuff just to be sure
#+OPTIONS: num:nil
#+OPTIONS: toc:nil
#+OPTIONS: h:5



#+BEGIN_SRC R :session calc :exports none :results values drawer :dir /home/johannes/
library(jtls)
dt_nbrs <- fread("/home/johannes/Dropbox/phd/papers/closing/misc/nbrs.csv")
wd_nbrs(dt_nbrs)
## quit(save="no")
#+end_src

#+RESULTS:
:results:
# descs
#+MACRO: pmdb_n_all 550
#+MACRO: pmdb_n_US 70
#+MACRO: pmdb_n_closed_US 9
#+MACRO: pmdb_open_atm 453
#+MACRO: pm_n_closed 68
#+MACRO: n_pmyears 6096
#+MACRO: pmdb_n_nlpm 25
#+MACRO: pmdb_n_closed 72
#+MACRO: pmdb_n 525
#+MACRO: pmdb_n_closed_NAclosingyear 2
#+MACRO: pmdb_n_closed_before2k 2
#+MACRO: pmdb_n_open_NAopeningyear 1
#+MACRO: pmx_n 505
#+MACRO: n_founder_dead 47
#+MACRO: perc_founder_dead 9.3
#+MACRO: pm_n_used 503
#+MACRO: n_pm_close_after_recent_death 3
#+MACRO: pm_open_from2021 17
#+MACRO: N_slfid_other 140
#+MACRO: N_slfid_museum 190
#+MACRO: N_slfid_foundation 104
#+MACRO: N_slfid_collection 69
#+MACRO: perc_slfid_other 28
#+MACRO: perc_slfid_museum 38
#+MACRO: perc_slfid_foundation 21
#+MACRO: perc_slfid_collection 14
#+MACRO: mow_prop_name_museum 71


# egmus
#+MACRO: own_state_cnt 2264
#+MACRO: own_loc_reg_cnt 7690
#+MACRO: own_publicother_cnt 641
#+MACRO: own_priv_cnt 5052
#+MACRO: own_ttl_cnt 15647
#+MACRO: own_state_perc 14
#+MACRO: own_loc_reg_perc 49
#+MACRO: own_publicother_perc 4.1
#+MACRO: own_priv_perc 32
#+MACRO: own_ttl_perc 100
#+MACRO: perc_entryfees 12
#+MACRO: perc_subsidies 69


# meanhaz
#+MACRO: meanhaz_upto_2 0.10%
#+MACRO: meanhaz_upto_4 0.49%
#+MACRO: meanhaz_upto_5 0.69%
#+MACRO: meanhaz_upto_8 0.73%
#+MACRO: meanhaz_upto_10 0.89%
#+MACRO: meanhaz_upto_20 1.09%
#+MACRO: meanhaz_upto_30 1.16%
#+MACRO: meanhaz_upto_40 0.96%
#+MACRO: meanhaz_upto_100 0.90%
#+MACRO: meanhaz_8onwards 0.92%
#+MACRO: meanhaz_8to30 1.20%
#+MACRO: median_life_expectancy 52


# yearhaz
#+MACRO: yearhaz_all 0.84%
#+MACRO: yearhaz_allw 1.12%
#+MACRO: yearhaz_upto2010 0.21%
#+MACRO: yearhaz_from2010 1.36%


# pltcfgs
#+MACRO: ynkplt_p_vrblcvrg_ugrpd (eval (concat "#+label: fig:p_vrblcvrg_ugrpd\n" "#+caption: PMDB variable coverage by museum status\n" "#+attr_latex: :width 19cm\n" "[[file:../figures/p_vrblcvrg_ugrpd.pdf]]"))
#+MACRO: ynkplt_p_vrblcvrg (eval (concat "#+label: fig:p_vrblcvrg\n" "#+caption: PMDB variable coverage by museum status and variable group\n" "#+attr_latex: :width 19cm\n" "[[file:../figures/p_vrblcvrg.pdf]]"))
#+MACRO: ynkplt_p_vrblcvrg_ratio (eval (concat "#+label: fig:p_vrblcvrg_ratio\n" "#+caption: PMDB variable coverage (abs/rel prop) by museum status and variable group\n" "#+attr_latex: :width 18cm\n" "[[file:../figures/p_vrblcvrg_ratio.pdf]]"))
#+MACRO: ynkplt_p_vrblcvrg_pca (eval (concat "#+label: fig:p_vrblcvrg_pca\n" "#+caption: coverage of variables used in PCA\n" "#+attr_latex: :width 18cm\n" "[[file:../figures/p_vrblcvrg_pca.pdf]]"))
#+MACRO: ynkplt_p_scree (eval (concat "#+label: fig:p_scree\n" "#+caption: Scree plot of PCA dimensionality reduction\n" "#+attr_latex: :width 14cm\n" "[[file:../figures/p_scree.pdf]]"))
#+MACRO: ynkplt_p_pca_loadings (eval (concat "#+label: fig:p_pca_loadings\n" "#+caption: loadings of first 2 PCs\n" "#+attr_latex: :width 14cm\n" "[[file:../figures/p_pca_loadings.pdf]]"))
#+MACRO: ynkplt_p_pca_scores (eval (concat "#+label: fig:p_pca_scores\n" "#+caption: scores on first PCs\n" "#+attr_latex: :width 16cm\n" "[[file:../figures/p_pca_scores.pdf]]"))
#+MACRO: ynkplt_p_surv (eval (concat "#+label: fig:p_surv\n" "#+caption: Private Museum Survival probability\n" "#+attr_latex: :width 14cm\n" "[[file:../figures/p_surv.pdf]]"))
#+MACRO: ynkplt_p_hazard (eval (concat "#+label: fig:p_hazard\n" "#+caption: Private Museum hazard function\n" "#+attr_latex: :width 16cm\n" "[[file:../figures/p_hazard.pdf]]"))
#+MACRO: ynkplt_p_hazard_time (eval (concat "#+label: fig:p_hazard_time\n" "#+caption: Private Museum hazard function by year\n" "#+attr_latex: :width 16cm\n" "[[file:../figures/p_hazard_time.pdf]]"))
#+MACRO: ynkplt_p_agedens (eval (concat "#+label: fig:p_agedens\n" "#+caption: Age distribution of private museums\n" "#+attr_latex: :width 17cm\n" "[[file:../figures/p_agedens.pdf]]"))
#+MACRO: ynkplt_p_yeardens (eval (concat "#+label: fig:p_yeardens\n" "#+caption: Private Museum-year Distribution\n" "#+attr_latex: :width 19cm\n" "[[file:../figures/p_yeardens.pdf]]"))
#+MACRO: ynkplt_p_coxphdiag_more (eval (concat "#+label: fig:p_coxphdiag_more\n" "#+caption: Model Diagnostics\n" "#+attr_latex: :width 19cm\n" "[[file:../figures/p_coxphdiag_more.pdf]]"))
#+MACRO: ynkplt_p_pred_popprxcnt (eval (concat "#+label: fig:p_pred_popprxcnt\n" "#+caption: Predicted Avg. Hazard Rate on Regional PM Density and Population\n" "#+attr_latex: :width 18cm\n" "[[file:../figures/p_pred_popprxcnt.pdf]]"))
#+MACRO: ynkplt_p_pred_proxcntpop (eval (concat "#+label: fig:p_pred_proxcntpop\n" "#+caption: Predicted Avg. Hazard Rate on Regional PM Density and Population\n" "#+attr_latex: :width 18cm\n" "[[file:../figures/p_pred_proxcntpop.pdf]]"))
#+MACRO: ynkplt_p_condmef (eval (concat "#+label: fig:p_condmef\n" "#+caption: Conditional effects of Regional PM Density and Population\n" "#+attr_latex: :width 18cm\n" "[[file:../figures/p_condmef.pdf]]"))
#+MACRO: ynkplt_p_pred_heatmap (eval (concat "#+label: fig:p_pred_heatmap\n" "#+caption: Predicted Avg. Hazard Rate on Regional PM Density and Population (at available values)\n" "#+attr_latex: :width 18cm\n" "[[file:../figures/p_pred_heatmap.pdf]]"))
#+MACRO: ynkplt_p_heatmap_info (eval (concat "#+label: fig:p_heatmap_info\n" "#+caption: heatmap info plots\n" "#+attr_latex: :width 35cm\n" "[[file:../figures/p_heatmap_info.pdf]]"))
#+MACRO: ynkplt_p_pred_heatmap_wocryside (eval (concat "#+label: fig:p_pred_heatmap_wocryside\n" "#+caption: Predicted Avg. Hazard Rate from Regional PM Density and Population (without proxcnt < 2 & popm_circle10 <2)\n" "#+attr_latex: :width 18cm\n" "[[file:../figures/p_pred_heatmap_wocryside.pdf]]"))
#+MACRO: ynkplt_p_pred_heatmap_onlycryside (eval (concat "#+label: fig:p_pred_heatmap_onlycryside\n" "#+caption: Predicted Avg. Hazard Rate from Regional PM Density and Population (only proxcnt < 2 & popm_circle10 <2)\n" "#+attr_latex: :width 18cm\n" "[[file:../figures/p_pred_heatmap_onlycryside.pdf]]"))
#+MACRO: ynkplt_p_pred_heatmap_alt (eval (concat "#+label: fig:p_pred_heatmap_alt\n" "#+caption: Prediction Heatmap of Alternative model specifications\n" "#+attr_latex: :width 18cm\n" "[[file:../figures/p_pred_heatmap_alt.pdf]]"))
#+MACRO: ynkplt_p_surv_death (eval (concat "#+label: fig:p_surv_death\n" "#+caption: Comparison of Survival Estimates by Founder Death (95% CI)\n" "#+attr_latex: :width 18cm\n" "[[file:../figures/p_surv_death.pdf]]"))
#+MACRO: ynkplt_p_lngtdvelp (eval (concat "#+label: fig:p_lngtdvelp\n" "#+caption: Composition of private museum population\n" "#+attr_latex: :width 18cm\n" "[[file:../figures/p_lngtdvelp.pdf]]"))


# figlbls
#+MACRO: refplt_p_vrblcvrg_ugrpd \ref{fig:p_vrblcvrg_ugrpd}
#+MACRO: refplt_p_vrblcvrg \ref{fig:p_vrblcvrg}
#+MACRO: refplt_p_vrblcvrg_ratio \ref{fig:p_vrblcvrg_ratio}
#+MACRO: refplt_p_vrblcvrg_pca \ref{fig:p_vrblcvrg_pca}
#+MACRO: refplt_p_scree \ref{fig:p_scree}
#+MACRO: refplt_p_pca_loadings \ref{fig:p_pca_loadings}
#+MACRO: refplt_p_pca_scores \ref{fig:p_pca_scores}
#+MACRO: refplt_p_surv \ref{fig:p_surv}
#+MACRO: refplt_p_hazard \ref{fig:p_hazard}
#+MACRO: refplt_p_hazard_time \ref{fig:p_hazard_time}
#+MACRO: refplt_p_agedens \ref{fig:p_agedens}
#+MACRO: refplt_p_yeardens \ref{fig:p_yeardens}
#+MACRO: refplt_p_coxphdiag_more \ref{fig:p_coxphdiag_more}
#+MACRO: refplt_p_pred_popprxcnt \ref{fig:p_pred_popprxcnt}
#+MACRO: refplt_p_pred_proxcntpop \ref{fig:p_pred_proxcntpop}
#+MACRO: refplt_p_condmef \ref{fig:p_condmef}
#+MACRO: refplt_p_pred_heatmap \ref{fig:p_pred_heatmap}
#+MACRO: refplt_p_heatmap_info \ref{fig:p_heatmap_info}
#+MACRO: refplt_p_pred_heatmap_wocryside \ref{fig:p_pred_heatmap_wocryside}
#+MACRO: refplt_p_pred_heatmap_onlycryside \ref{fig:p_pred_heatmap_onlycryside}
#+MACRO: refplt_p_pred_heatmap_alt \ref{fig:p_pred_heatmap_alt}
#+MACRO: refplt_p_surv_death \ref{fig:p_surv_death}
#+MACRO: refplt_p_lngtdvelp \ref{fig:p_lngtdvelp}


# reftbl
#+MACRO: reftbl_t_coxzph \ref{tbl:t_coxzph}
#+MACRO: reftbl_t_sumstats \ref{tbl:t_sumstats}
#+MACRO: reftbl_t_selfid \ref{tbl:t_selfid}
#+MACRO: reftbl_t_reg_coxph_deathcfg \ref{tbl:t_reg_coxph_deathcfg}
#+MACRO: reftbl_t_drop1 \ref{tbl:t_drop1}
#+MACRO: reftbl_t_reg_coxph \ref{tbl:t_reg_coxph}
#+MACRO: reftbl_t_reg_coxph_density \ref{tbl:t_reg_coxph_density}
#+MACRO: reftbl_t_reg_coxph_timeslice \ref{tbl:t_reg_coxph_timeslice}
#+MACRO: reftbl_t_reg_coxph_comp \ref{tbl:t_reg_coxph_comp}
#+MACRO: reftbl_t_reg_coxph_dens \ref{tbl:t_reg_coxph_dens}
#+MACRO: reftbl_t_reg_coxph_env \ref{tbl:t_reg_coxph_env}
#+MACRO: reftbl_t_reg_coxph_af \ref{tbl:t_reg_coxph_af}
#+MACRO: reftbl_t_reg_coxph_timecfg \ref{tbl:t_reg_coxph_timecfg}
#+MACRO: reftbl_t_reg_coxph_dimred \ref{tbl:t_reg_coxph_dimred}
#+MACRO: reftbl_t_reg_coxph_reg \ref{tbl:t_reg_coxph_reg}


# coefs
#+MACRO: coef_genderF -0.038
#+MACRO: coef_gendercouple -0.140
#+MACRO: coef_pmdens_cry 0.648
#+MACRO: coef_pmdens_cry_sq -0.027
#+MACRO: coef_slfidfcnfoundation 0.203
#+MACRO: coef_slfidfcncollection -0.454
#+MACRO: coef_slfidfcnother 1.091
#+MACRO: coef_founder_dead_binary 0.280
#+MACRO: coef_muem_fndr_name 0.048
#+MACRO: coef_an_inclusionincluded 0.193
#+MACRO: coef_an_inclusiondropped 0.460
#+MACRO: coef_proxcnt10 0.263
#+MACRO: coef_popm_circle10 0.268
#+MACRO: coef_recession -1.586
#+MACRO: coef_covid 0.423
#+MACRO: coef_proxcnt10:popm_circle10 -0.089
#+MACRO: pvlu_genderF 0.91
#+MACRO: pvlu_gendercouple 0.66
#+MACRO: pvlu_pmdens_cry 0.058
#+MACRO: pvlu_pmdens_cry_sq 0.22
#+MACRO: pvlu_slfidfcnfoundation 0.62
#+MACRO: pvlu_slfidfcncollection 0.40
#+MACRO: pvlu_slfidfcnother 0.00032
#+MACRO: pvlu_founder_dead_binary 0.52
#+MACRO: pvlu_muem_fndr_name 0.87
#+MACRO: pvlu_an_inclusionincluded 0.57
#+MACRO: pvlu_an_inclusiondropped 0.35
#+MACRO: pvlu_proxcnt10 0.00047
#+MACRO: pvlu_popm_circle10 0.0047
#+MACRO: pvlu_recession 0.12
#+MACRO: pvlu_covid 0.15
#+MACRO: pvlu_proxcnt10:popm_circle10 0.0032
#+MACRO: coef_genderF_exp 0.96
#+MACRO: coef_gendercouple_exp 0.87
#+MACRO: coef_pmdens_cry_exp 1.91
#+MACRO: coef_pmdens_cry_sq_exp 0.97
#+MACRO: coef_slfidfcnfoundation_exp 1.23
#+MACRO: coef_slfidfcncollection_exp 0.63
#+MACRO: coef_slfidfcnother_exp 2.98
#+MACRO: coef_founder_dead_binary_exp 1.32
#+MACRO: coef_muem_fndr_name_exp 1.05
#+MACRO: coef_an_inclusionincluded_exp 1.21
#+MACRO: coef_an_inclusiondropped_exp 1.58
#+MACRO: coef_proxcnt10_exp 1.30
#+MACRO: coef_popm_circle10_exp 1.31
#+MACRO: coef_recession_exp 0.20
#+MACRO: coef_covid_exp 1.53
#+MACRO: coef_proxcnt10:popm_circle10_exp 0.92
#+MACRO: coef_genderF_perc 3.9
#+MACRO: coef_gendercouple_perc 15
#+MACRO: coef_pmdens_cry_perc 91
#+MACRO: coef_pmdens_cry_sq_perc 2.8
#+MACRO: coef_slfidfcnfoundation_perc 23
#+MACRO: coef_slfidfcncollection_perc 58
#+MACRO: coef_slfidfcnother_perc 198
#+MACRO: coef_founder_dead_binary_perc 32
#+MACRO: coef_muem_fndr_name_perc 4.9
#+MACRO: coef_an_inclusionincluded_perc 21
#+MACRO: coef_an_inclusiondropped_perc 58
#+MACRO: coef_proxcnt10_perc 30
#+MACRO: coef_popm_circle10_perc 31
#+MACRO: coef_recession_perc 389
#+MACRO: coef_covid_perc 53
#+MACRO: coef_proxcnt10:popm_circle10_perc 9.3


# coefs2
#+MACRO: popm_circle10_marg0 2.97
#+MACRO: proxcnt10_marg0 3.03
#+MACRO: N_below_popm_circle0_marg0 5056
#+MACRO: perc_below_popm_circle10_marg0 83
#+MACRO: N_below_proxcnt10_marg0 4960
#+MACRO: perc_below_proxcnt10_marg0 81
#+MACRO: N_zoneBL 4508
#+MACRO: N_zoneTL 452
#+MACRO: N_zoneBR 548
#+MACRO: N_zoneTR 588
#+MACRO: N_zonebottom 5056
#+MACRO: N_zonetop 1040
#+MACRO: N_zoneleft 4960
#+MACRO: N_zoneright 1136
#+MACRO: perc_zoneBL 74
#+MACRO: perc_zoneTL 7
#+MACRO: perc_zoneBR 9
#+MACRO: perc_zoneTR 10
#+MACRO: perc_zonebottom 83
#+MACRO: perc_zonetop 17
#+MACRO: perc_zoneleft 81
#+MACRO: perc_zoneright 19
:end:


* Stayin' Alive: The unexpected longevity of founder-centered private art museums
# Short-lived legacies: The closure of private art museums
# Non-diversified but stable? The paradox of private museum closing rates
# Johannes Aengenheyster

# #+latex: \noindent
# Phd student at University of Amsterdam

# #+latex: \noindent
# j.aengenheyster@uva.nl


** Introduction

In recent years, private collector-run museums have seen an unprecedented proliferation, with hundreds of organizations founded since the beginning of the millenium [[parencite:&Velthuis_etal_2023_boom;&LarrysList_2015_report]].
#
These museums, run by individual collectors, constitute an addition to established organizational forms of art provision such as museums operated and financed by the state, foundations or associations.
#
While many aspects of this new organizational form has attracted attention, such as their emergence, relations to other institutions or impact on artist consecration (cf. [[cite:&Kolbe_etal_2022_privatemuseum]] for a literature review), the process of closure has received considerably less attention. 
#
Furthermore, the focus that has been given to questions of sustainability has been primarily conducted through case studies; quantitative studies have been mostly absent.
# 
In this paper, I address this gap by investigating the closure event of members of this new organizational form.
#
Analysis which factors are associated with museum closures provides insight not only into the event of closing, but also into the ongoing processes of a private museums, such as dependency relationships.
#
Furthermore, analyzing which museums survive allows to make informed speculations on the future of this recently emerged organizational form.



# #+latex: \bigbreak
# #+latex: \noindent
# *keywords*: museum, closure, identity



*** Contributions :ignhead:
# - Intransparent founder motivations

# Despite their occasionally spectacular/sensationalist press coverage, these institutions and the motivations of their founders have remained remarkably intransparent.
# #
# Financed in large parts by their founders' private wealth, few reporting requirements exists; and while some founders highlight their charitable and distintersted intentions in media coverage, such statements intended for a public audience might not necessarily reflect underlying founder motivations accurately.

# This study (attempts to) elucidate the hard-to-observe collector motivations by studying one of the most decisive actions that their founder can take: the decision to close the museum.
# #
# Besides investigating the longevity of members of this new organizational form, this study gives insights into the motivations and decision making of founders.
# # 
# In other words, what can the factors leading to the closure of private museums tell us about the internal processes and dependence relationships of these institutions, as well as about the motivations of their founders?


While a recent study by [[textcite:&Velthuis_Gera_2024_fragility]] has investigated closing reasons of private museums, I extend/complement this study by using a more elaborate statistical model and additional data sources.
#
In particular, I compare private museum closing rates to those of other museum populations, and analyze the risk associated with variables on the level of the founder, museum and environment. 
#
Taken together, the results show that (at least so far) little evidence exists neither for private museums being overly dependend on their founder, nor having overall higher mortality rates than other non-profit museums.
#
While little evidence points toward private museums being unvoluntarily at risk due to their low diversification, private museums may close due to environmental pressures, which exhibit a complex relationship which for most museums consists of competition from other private museums as well as, unexpectedly, large audiences.
#
Finally, private museums with unconventional names (in particular, without the term "museum" in the name) face a higher closing risk, which may indicate either a temporary intention by their founders from the very beginning and/or limited recognition by third parties as potential closing reasons.


This study furthermore combines museum research with quantitative non-profit management literature, a link which has so far been weak. 

** Private museums definition and dependency relations


*** definition

While private collectors have existed for centuries, and have already founded a number of notable museums in the gilded age [[parencite:&diMaggio_1982_boston;&Higonnet_2003_sight;&Duncan_1995_civilizing]], in the recent decades they have substantially expanded their activities into the museum sphere by founding their own museums as individuals, rather than e.g. loaning or donating their collection or opening museums as a group.
#
This phenomenon of private collectors taking the initiative in setting up a museum of their own has become increasingly widespread, with around 80% of currently open private museums having opened since 2000 [[parencite:&Velthuis_etal_2023_boom]].
#
To be considered as a private museum for this study, a collector needs to have amassed a substantial art collection, which he exhibits in a building in a way that is accessible to the public, all while receiving limited public and corporate funding.
#
The central role of the founder delimits a private museum from other organizational forms such as public museums supported by local or state governments, corporate museums run by companies or other non-profit museums operated by associations or foundations with more dispersed ownership and control.[fn::Which is not to say that for an institution to be considered a private museum, it has to be legal personal ownership of the founder. Insted the distinguishing criterion is the central role of the collector, which can be the case under a wide range of organizational forms; generally this has to be assessed on a case-by-case basis.]



*** chronic lack of money of NPOs :ignhead:

Due to the founders central role, private museums have been argued to be highly dependent on their founder for their continuing existence, as museums generally cannot cover expenses via revenues from ticket prices, museum shops and cafes:
#
The [[textcite:&IMLS_2008_funding]] found that for non-profit American art museums, less than half (48.1%) the revenues come from earned income, leaving substantial gaps in the budgets that are filled by a mix of private donations (23.0%), investment (18.5%) and government support (10.4%) (p.27).
#
Outside of the United States, the reliance on revenue streams beyond operations is even larger:
#
German museums in the 1990s covered on average only around 30% of their budget by their income [[parencite:&Martin_1993_museen]][fn::Own calculations based on table p.233], with private museums however requiring less support as operations provide around 47% of their budget (ibid.).
#
In the Germany cultural sector, non-profit organizations more widely  draw around 50% of their funding from public support [[parencite:&Zimmer_Priller_2007_gemeinnuetzig p.82]].
#
On a European level, only {{{perc_entryfees}}}% of museum incomes are generated by entry fees, whereas {{{perc_subsidies}}}% originate from subsidies [[parencite:&EGMUS_2024_complete]].[fn::Own calculations from on EGMUS data, based on all countries with income data from 2015 onwards.]


Given that operating at "the margin of financial sustainability" is the "ordinary condition" for cultural NPOs, [[parencite:&Licci_BaraldiBonini_2024_sustainability p.2]], it is not surprising that costs have been listed as a primary reason for private museum closure:
# 
[[textcite:&Adam_2021_rise]] argues that "most of the cases of defunct private museums come back to the issue of cost" (p.79); a sentiment shared by [[textcite:&Walker_2019_collector]] who notes that "private institutions struggle to contain escalating costs that are associated with running a museum" (p.234).
#
In other studies, "insufficient funding, high maintenance costs and lack of strong government support" [[parencite:&Zennaro_2017_shanghai p.7]], a "shortage of fundings and interruptions in cash" [[parencite:&Song_2008_private p.45]], bankruptcies [[parencite:&Velthuis_Gera_2024_fragility;&Liu_2019_identities;&DeNigris_2018_museums]], costly legal battles [[parencite:&Velthuis_Gera_2024_fragility]], stock devaluations [[parencite:&Walker_2019_collector]] or failing auction sales [[parencite:&Bechtler_Imhof_2018_future]] were central reasons that forced private museums to close.
#
In a systematic review of closing reasons given in newspapers, magazines, social media accounts and personal exchanges, [[textcite:&Velthuis_Gera_2024_fragility]] find financial issues as the most commonly mentioned reasons for private museum closing.

*** diversification
**** founder reliance -> diversification :ignhead:

#
A central reason for financial vulnerability has been argued to be the crucial reliance on the single founder, who, as the iniators of their private museums, likely have to contribute a large part of their institution's non-operating income [[parencite:&Frey_Meier_2002_beyeler]]:
# 
[[textcite:&Adam_2021_rise]] argues that "ultimately, many of these failures demonstrate the fragility of spaces that rely on a single founder, whose motivations and financial stability may change, or who may not have realised the difficulties inherent in establishing their own art space" (p.82).
# 
[[textcite:&Velthuis_Gera_2024_fragility]] similarly argue that "because of their funding models and reliance on a sole founder, [private museums] are inherently fragile organizations" (p.1).
#
[[textcite:&Bechtler_Imhof_2018_future]] also characterize "the dependency on single individuals only" as one of main reasons that "make these private museums fragile" (p.53).
#
[[textcite:&StylianouLambert_etal_2014_museums]] similarly describe many private institutions as "small individual museums that depend too much on their creators to guarantee their sustainability" (p.582).
#
Beyond a direct financial component, private museums have been also been characterized as fragile since they can only rely on their founder for "taste", "vision and drive" [[parencite:&Adam_2021_rise p.77]], "passion" [[parencite:&Walker_2019_collector p.234]] or "skills and knowledge" [[parencite:&StylianouLambert_etal_2014_museums p.580]].



**** diversification in general :ignhead:
Existing research on private museum is conducted primarily by scholars of the art field or market as well as art historians.
#
Nethertheless, the identification of the centrality of the founder as a critical source of vulnerability corresponds strongly to the finding in non-profit management of a relation between diversification and mortality [[parencite:&Tuckman_Chang_1991_vulnerability]].
#
For example, [[cite:&Bielefeld_1994_survival]] finds that nonprofits with a larger number of funding sources (e.g. from foundations, individuals, federated funders, corporations, trusts, government at federal, state, county and municipal level as well as self-generated sources such as dues, interests, and service revenue, p.31) are more likely to survive.
#
Other studies have measured diversification as the Herfindahl Index (a measure of concentration) of income sources such as public support, program service revenues, dues and assessments, net fundraising income and profits from sale of inventory [[parencite:&Hager_2001_vulnerability p.381]] or contributions, program service revenue, investment income, other revenues [[parencite:&Lu_Shon_Zhang_2019_dissolution p.37]], with both studies finding a positive association between diversification and survival; in the case of [[cite:&Hager_2001_vulnerability]] also specifically for art museums.
# 
Next to diversification, volatility, i.e. fluctuation in revenue streams has been associated with mortality as well [[parencite:&Mayer_2022_simmer]].
#
Despite limited reception of this research stream in the private museum literature, identifying the high reliance on the founder as a source of risk thus corresponds to management insights. 



**** death :ignhead:

Lack of diversification is then argued to pose a problem in particular in the case of the founder's death:
#
textcite:&Walker_2019_collector argues that "the death of the original founder and creator can [...] place the future of private museums and collections in jeopardy" as "seldom do heirs share a similar passion or wish to take on the financial burden of maintaining private museums indefinitely" (p.234). 
#
[[textcite:&Bechtler_Imhof_2018_future]] argue that in order to ensure private museum longevity, "flexible, easily adapted designs for private museums" are necessary "to reduce the financial burden on their heirs" (p.188).
# can't find it online by koolhaas
# [[cite:&Koolhaas_2008_ideology]] is more about using public museums as storage
# 
[[textcite:&Adam_2021_rise]] argues that succession introduces financial strains as "collectors’ successors may not look kindly on what may well be a money pit when [...] they will have to pick up the bills" (p.77), and also highlights the aesthetic dimension as "the nature of contemporary art is to be fresh and new, but what is ‘fresh and new’ for the founder might seem ‘old hat’ to their heirs". (p.76).
#
[[textcite:&Velthuis_Gera_2024_fragility]] similarly argue that "the founder’s death will almost inevitably have a direct impact on the financial health of the museum" (p.10).
# this is not about closing, just health
#
[[textcite:&StylianouLambert_etal_2014_museums]], after discussing a case of a private museum whose owner "does not believe that anyone else could love the museum as much as she does", argue that this "generates questions regarding the cultural sustainability of small private museums in cases where their initiators are not able to care for them any longer" (p.580).

**** comparison lacking :ignhead:

# Overall, two related arguments emerge from the current literature on private museum sustainability:
#

Private museums heavily rely on their founders for survival; events that interrupt the founders ability to provide resources are therefore associated with a highler likelihood of closing.

*Hypothesis 1*: Events which disrupt the founder's ability to provide resources to their private museums increase the risk of closing, in particular:

The death of the founder is a clearly financial and organizational disruption for the museum, and as previous research has seen it as a precursor of museum closure, a hypothesis can be formulated as: 
*Hypothesis 1a*: Private museums are more likely to close after the death of the founder.


# A less obvious, but nonetheless possible event that reduces a founder's capability to provide resources for their museum, which in turn would limit its longevity, could be a decline in status.
# #
# Recognition by key art world authorities bestows the recognition of "cultural expertise" [[parencite:&Braden_2016_recognition p.1486]],  validating a collector's owner's good taste, and thus constitutes symbolic capital which can be converted into tangible benefits such as cooperations with other institutions and larger audiences, which in turn could enhance museum survival prospects.
# #
# Loss of recognition might then, next to possibly demotivating the founder personally, also limit such opportunities.


A less obvious yet possibly impactful event that can jeopardize a founder's ability to sustain their museum and potentially shorten its lifespan is a decline of status of the collector within the art world.
#
Recognition bestowed by prominent art world authorities confers the acknowledgment of "cultural expertise" [[parencite:&Braden_2016_recognition p.1486]], thus validating the collector-founder's refined taste, which constitutes a form symbolic capital that might yield tangible benefits [[parencite:&Bourdieu_1993_production]].
# 
This symbolic capital might provide opportunities to acquire material advantages such as collaborations with other institutions and access to broader audiences, ultimately bolstering the museum's longevity.


In the face of a loss of recognition, the consequences can extend beyond the personal demotivation it may cause the founder.
#
Such a decline could also curtail potential opportunities for cooperation with other institutions and limit the museum's reach to larger audiences, thus posing a risk to the museum's continued operation and survival in the long term.
# 


*Hypothesis 1b*: Private museums are more likely to close after a decline of their founder's status, measured by exclusion from a prestigious ranking.

# #
# Second, due to their low diversification (high reliance on the founder), private museums are more fragile than museums where single individuals are not comparably central figures.



# While private museums are thus generally characterized as fragile, it is not always clear in relation to whom.
# # FIXME: relation to whom?
# #
# Among the most explicit is [[textcite:&Walker_2019_collector]], who characterizes public institutions as relatively stable (which constitutes the reason why private collectors aim to form cooperations with them); [[textcite:&Bechtler_Imhof_2018_future]] implicitly also highlight the longevity of state-run institutions.
# #
# However, no systematic data is used to estimate public museum longevity, and while some
# remarks are made that public spending cuts might result in problems for public museum operations (p.233), the overall characterization of them remains as immortal [[parencite:&Frey_Meier_2002_beyeler]].
# #
# Responsible for the characterization of private museums as fragile might also be implicit reliance on the ICOM definition [[parencite:&ICOM_2024_definition]] of museums as "permanent institutions" (according to which every closing is indicative of fragility), which is echoed by an interviewee of [[textcite:&Walker_2019_collector]] who expresses (his perspective on) the prevalent perspective as "we assume museums are forever" (p.235).
# #


# *Hypothesis 1*: Private museums have higher closing chance than non-profit museums generally.
# *Hypothesis 2*: A founder's death increases the risk of closing.
# *Hypothesis 2*: Private museums with higher reliance on the founder are more likely to close




# Reliance on the founder is the mechanism through which PMs are exposed to a higher closing risk, thus founder-related variables predict closing, in particular: 
# - *Hypothesis 2a*: 
# - *Hypothesis 2b*: 
# - *Hypothesis 2c*: Private museums which carry their founder's name in the museum name are more likely to close.




*** environment :ignhead:

While the low diversification, i.e. the centrality of the founder for museum finances, has been argued to constitute the key feature of private museum vulnerability, it is also important to consider the other ways in which private museums, as (non-profit) organizations, are entangled with their environments.
#
Its ability to attract audiences, which may involve competition with other museums, secure cooperations with other museums, acquire sponsorships from cooperations and fundings from governments and other foundations possibly constitute factors that contribute to its viability and hence longevity.
# 
While some of these aspects can be influenced by the founder (in particular the museum's location and strategies) , other are less so.
#
In particular when they rely on the decision-making of other art-field actors, such as competition with other museums and sponsorship/funding choices, the influence of the individual founder is severely limited.
#
# The image that these parties have of the private museum might be substantial importance in guiding their decision-making.


**** Competition



# mechanism: losing motivation?


Private museums have been characterized as highly competitive.
#
While some self-descriptions focus on collaborative aspect, previous studies have highlighted how private museums compete with public museums over art works, audiences, sponsoring and donors [[parencite:&Kolbe_etal_2022_privatemuseum p.4]]. 
#
So far the primary interest of investigating competition has been to evaluate whether private museums pose a threat to art provision by public institutions.
#
However, less focus has been given to the fact that operating in a competitive environment may also have consequences for the private museums themselves, in particular their survival aspects.
# 
While private museums presumably depend on their founder to a large extent, income from tickets and facilities, as well sponsorships and public support possibly also constitute other non-negligible revenue streams.
# 
While competition directly has not yet been investigated as a cause for private museum closing, a possible mechanism of competition, "insufficient interest from the public", has been identified as the second most mentioned closure reason by [[textcite:&Velthuis_Gera_2024_fragility p.6]]. 
#
Lack of interest by the public can be a consequence of multiple processes.
#
While competition is one such processes, and applies if nearby competing institutions capture large portions of the audience, lack of interest can also result from a lack of audience (in the absence of competing institutions), which may be the case for private museums located in sparsely populated areas.
#
In both these cases, the resources that a private museum is able to receive from actors in its environment are limited. 



Previous research into non-profit dissolution has often investigated competition as a cause of closure, with both qualitative and quantitative studies indeed identifying competition as a frequent closure reason.
#
Qualitative studies which trace the history and/or closing reasons for each organization individually have highlighted competition over funding.
# 
textcite:&Hager_1999_demise reports that "both individual donations/subscriptions and community and corporate grants tended to go to the singular, most reputable arts organizations of their types", resulting in "strong competitive pressures" for the vast majority of organizations (ibid.).
#
Similarly, [[textcite:&HernandezOrtiz_2022_discontinuity]] found that an "[increasingly] crowded niche increased the competition and limited [NPOs'] access to resources and clients" (p.116) with an informant stating that "there was less money to go around and more organizations seeking the money [...] we had a full-time grant writer, we were always applying for grants. But there are so many organizations applying for the same grants" (ibid.).
#
Quantitative studies have identified a relation between competition and non-profit closing primarily via measuring competition over density [[parencite:&Park_Shon_Lu_2021_mortality;&Haugh_etal_2021_nascent;&Lu_Shon_Zhang_2019_dissolution]], with higher number of non-profits increasing the chance of non-profit dissolution.
#
Thus, a hypothesis regarding competition can be formulated as:

*Hypothesis 3*: A private museum is more likely to close in a more competitive environment.
  
  

**** Identity 
# provide legitimacy

The mere availability of audiences and other potential donors might however not be sufficient if a museum is not perceived as deserving support; i.e. if its identity is perceived as inappropriate. 
#
An identity that is legitimate (understandable) and favorable (positive) has been argued to have a vast number of positive outcomes for organizations [[parencite:&Lange_Lee_Dai_2010_reputation]].
# 
As gaining the approval of different stakeholders is necessary for being understood and/or supported by other organizations in the environment, having a clearly defined and favorable identity influences resource acquisition and thereby survival prospects [[parencite:&Rao_1994_reputation]].
#
Even for non-profit organizations such as museums, which do not produce tangible goods (a domain where identity-related effects are especially prevalent, e.g. [[cite:&Hsu_2015_granted;&Bogaert_etal_2014_ecological]]), a clear and positive identity might be helpful in a number of ways:
# 
In the context of private museums, a negative identity could lead to lower visitor numbers, less discounts from art dealers, less government grants or lower chances on collaborations with other museums or corporations, resulting in lower revenues and higher acquisition costs.


The empirical record of the link between identity and survival for non-profit organizations however is mixed: 
# 
For example [[textcite:&Bielefeld_1994_survival]] finds that NPOs who pursue less legitimation strategies (obtaining endorsements, lobbying or contributing to local causes) are more likely to close, and [[textcite:&HernandezOrtiz_2022_discontinuity]] observes a declining image or reputation as a cause of closure in a number of non-profits (p.115).
#
Nonetheless, other studies find little to no effect of legitimacy on survival, both when measured via density parencite:&Bogaert_etal_2014_ecological or from archival sources and interviews [[parencite:&Fernandez_2007_dissolution]].


Legitimacy might be obtained by isomorphism, i.e. adopting features associated with blueprints [[parencite:&diMaggio_1983_iron]].
#
Next to material organizational features, adherence to naming conventions has been found to enhance legitimacy [[parencite:&Glynn_Abzug_2002_names]]; organizations that adhere to field norms about name length, name ambiguity (usage of artificial names) and name domain specificity (mentioning industry) were judged more legitimate. 
# 
However, the category of museums could be relatively flexible (for example, the term "museum" is generally not subject to state regulation in the US or Germany parencite:&Museumsbund_ICOMDE_2006_standards;&Lister_2023_marketing), which might result in a relatively high tolerance of diversity and hence limited devaluation of non-conforming, atypical members [[parencite:&Bogaert_etal_2014_ecological]].


# Furthermore, identity of a private museum may be influenced by the identity of persons most closely affiliated with it, in particular the identity of its founders.
# #
# Given that founders are the very reason behind the existence of these organizations, and sometimes plan these as their personal legacies [[parencite:&Walker_2019_collector]], founder status gains or losses may reflect on the wider organization and affect its survival propspects.


#+latex: \bigbreak
#+latex: \noindent
*Hypothesis 4*: Private museums with more understandable identities, indicated by adherence to naming conventions, are less likely to close. 


# FIXME
It is however necessary to consider that in particular the name of a museum might be associated with a museum's survival via identity, but also reflect founder intentions regarding the institutions longevity; this possibility is discussed in more detail in the results section.

# Furthermore, inferring the status of the museum via the reputaton of the founder again explores the extent to which the founder is a figure of central importance for the private museum.




** Methods and Data 


A newly constructed database, assembled from a wide range of sources, is used to measure the survival of private museums (cf. [[textcite:&Velthuis_etal_2023_boom]] for details).
#
Currently, the database includes {{{pmdb_n_all}}} museums, of which {{{pmdb_open_atm}}} are currently open, {{{pmdb_n_closed}}} have closed and {{{pmdb_n_nlpm}}} have transformed into other organizational forms.[fn:: The {{{pmdb_n_nlpm}}} institutions which were private museums at some point and have since been transformed into other organizational forms are not included in this analysis and discussed in the limitations.]
#
Using this database, in particular year of opening and, if available, closing, it is possible to reconstruct the life course of the each institution with museum-year as the unit of analysis.
#
While the database is not limited to private museums of a particular time period, due to the recency of the private museum boom in the last two decades 80% of the museums included in it have opened after 2000.
#
As the databse was constructed retrospectively from 2020 to 2022, I focus here on closing events from 2000 to 2021 to limit the possibility that some institutions were missed, as such risks are likely higher for earlier time periods.
#
Furthermore, a small number of museums are excluded, in particular {{{pmdb_n_closed_NAclosingyear}}} museums for which the closing date could not be found, {{{pm_open_from2021}}} museums which opened in 2021 and later (as survival analyses requires positive survival times), {{{pmdb_n_open_NAopeningyear}}} museum the opening year of which could not be determined, as well as {{{pmdb_n_closed_before2k}}} museums which closed before 2000 and thereby fall outside the period under investigation.
#
This leaves {{{pm_n_used}}} private museums at risk which have accumulated {{{n_pmyears}}} museum-years and {{{pm_n_closed}}} closures.
#
This data allows to conduct survival analysis (also known as event history analysis), the most common statistical technique to investigate hazard rates and identify mortality-assocated covariates parencite:&Moore_2015_survival;&Allison_2014_event.




# Hypothesis 1 (comparing closing risk between private museums and other, more diversified institutions) ideally would use a complete population of museums to identify the effect of institutional form on closing rate.
# #
# However, as no institutions are maintaining museum databases on a global scale, I use existing quantitative studies of museum closure to compare to these private museums in terms of their closing rates.
# 


In particular, Cox proportional hazard models allows to identify the risk that a number of variables pose for a museum's chance of closing. 
# which differentiate the private museum population according to a number of risk factors, are investigated via . 
#
The dependent variable is an indicator of museum closure, which takes the value of 1 for the museums which close in the year of their closure, and 0 otherwise.
#
Typically for survival data, museums that do not close during the observation period are right-censored, i.e. for such museums the dependent variable is zero for all years as their closing has not been observed.
#
The Cox-proportional hazard model has the form $h(t,\mathbf{x}) = h_0(t) \psi$, where $\psi = \exp(\sum_{j} \mathbf{x}_j \beta_j)$; with $h(t)$ as the hazard rate, $h_0(t)$ as the baseline hazard rate, $\mathbf{x}$ as the set of variables indexed by $j$, and $\beta$ as the coefficient vector.
#
Partial maximum likelihood estimation allows calculating \beta without defining the baseline hazard rate, which therefore is not constrained to a parametric form parencite:&Moore_2015_survival.
 



*** Main Predictors (Cox Proportional Hazards Model)

# The organizational identity of a museum is measured primarily in terms of its legitimacy, i.e. its adherence to museum standards, and reputation of its founders.

**** Founder death
:PROPERTIES:
:CREATED:  [2024-04-07 zo 15:06]
:ID:       764f17aa-0bd3-400b-a3ee-d72770e988f1
:END:

A measure of founder death is constructed as a time-varying covariate, which takes the value of 1 from the year of the founder's death onwards.

# should I have founder name here as well? would tie in to diversification


**** Legitimacy

#+include: "../tables/t_selfid_wcpF.tex" export latex

Two measures are constructed that aim to capture an effect of legitimacy on closing.
#
First, self-identification measures whether a the name of a museum includes the term "Museum", "Foundation", "Collection", or other (such as "Villa", "Institute", "Center" or "Gallery", which are grouped together as they are less frequent, see table {{{reftbl_t_selfid}}}).
#
Since the name is one of the first aspects that stakeholders perceive when engaging with an organization, it might shape expectations and influence forms of engagement.
#
In particular, it might be that museums that also refer to themselves as museums are seen as more favorable and worthy of visits, collaborations and support than other museums.


To ensure that inclusion of the word "museum" corresponds to the naming convention of the museum population, the names of the "Museums of the World" (MOW) database [[parencite:&deGruyter_2021_MOW]], a database containing over 55,000 museums, are analyzed.
#
In this database, {{{mow_prop_name_museum}}}% of museum names contain the term "museum" (or its equivalent in other languages), which indicates a substantial convention by founders to include the term museum in the name of their institution.[fn::While it would also be possible to construct inclusion in the MOW as an indicator of legitimacy, as it represents recognition of the organization as a museum by experts [[parencite:&Zuckerman_1999_illegitimacy]], preliminary investigations of the database indicated that it has been  updated only sparsely in recent years; thereby inclusion in it (or the lack therefore) does not constitute an accurate measurement of the extent of an institutions' recognition as a museum.]


# Secondly, a binary predictor measures whether the museum is included in the 
# #
# While the exact criteria of the research process leading to the MOW database are not known, it is plausible that museums who correspond to an ideal-typical museum are more likely to be included.
# #
# Assuming that museums are seen similarly by the creators of the MOW database and other audiences, inclusion in the MOW database constitutes a proxy for adherence to museum standards. 


**** Reputation

Reputation is measured via inclusion of the founder in the Artnews top 200 collector ranking [[parencite:&Artnews_ranking]].
#
This ranking, established in 1990, lists each year the 200 collectors the editors of the magazine consider most relevant.
#
For each year, a museums can have one of three values: "Not included"; in which case the founder is not included in the year in question and has not been so in the past, "Included"; when the founder is included, or "Dropped", for cases where the founder was included at some point in the past but is no longer included in the current year.
#
Cases where multiple individuals are involved in the founding of a private museum are resolved by aggregating the Artnews ranking inclusion history to the founder level (i.e., if only one of two founders is dropped from the Artnews ranking but the other remains included, the founder couple as a whole is considered included).
#
The variable is lagged by one year to avoid reverse causality, i.e. to exclude the possibility that an association is observed which is present due to founders being dropped from the ranking as a consequence of the closure of their museum.



**** Competition
:PROPERTIES:
:CREATED:  [2024-04-07 zo 15:07]
:ID:       e891980a-d6c2-400a-8770-238a1c68eb09
:END:

On a national level, density of private museum is calculated as the number of private museums per million population.
# 
To measure competition on a local level, I first determine the coordinates of museum using the Google Maps API; the coordindates of museums which are not found that way (particularly those located in countries with limited Google presence such as South Korea, China and Russia) are searched manually (often using other map services such as Kakao Maps, Baidu Maps and Yandex Maps).
#
For closed museums, which often are not included in the current map databases, coordinates are also determined via addresses mentioned on snapshots in the Wayback Machine.
# 
I then use the Global Human Settlement Layer [[parencite:&EC_2023_GHSL]] to estimate the number of private museums and population counts inside a radius of ten kilometers around each private museum for each year.
#
To be able to estimate both competition and demand/audience/population separately, I do not calculate densities as per capita rates, but include the local museum counts, local population in millions as well as an interaction between the two.

*** Control variables

#+latex: \bigbreak
#+latex: \noindent
A number of control variables are used: 
# 
On the level of the founder, gender constitutes a time-invariant variable; with possible values being male, female and couple.
#
Women constitute a minority of the private museums founders, thus from a typicality perspective [[parencite:&Rosch_1975_family]] museums by female founders would be expected to close more often as female founders would have a greater difficulties in securing resources third parties, presumably primarily governments and corporate sponsors.
#
However, women may also be particularly associated with philanthropic initiatives - in contrast to corporate activities [[parencite:&Milam_2013_artgirls]] - to such an extent that devaluation of female initiatives may not necessarily be present.

#
# Organizational transformation, such as change of authority has been to increase chances of closure both generally [[parencite:&Carroll_Khessina_2019_demography]] and in the case of private museums specifically ([[cite:&Walker_2019_collector p.234]]: "seldom do heirs share a similar passion or wish to take on the financial burden of maintaining private museum indefinitely").
# Therefore, a measure of founder death is constructed as a time-varying covariate, and is set to 1 for museum-years after the death of the founder. 
#
# Centrality of the founder's vision is measured via the proxy of whether the name of the founder is included in the name of the museum.




External shocks might interrupt operations, which reduces income from tickets, as well as make other donors more hesitant to commit money in uncertain times.
#
However, museums, including private museums, might also be relatively resilient as they can adopt measures such as tightening their belt, additional fundraising, and expanding their marketing efforts [[parencite:&Geller_Salamon_2010_resilience]], which might bolster their resilience.
#
To account for two prevalent shocks in the recent decades, the Great Recession and the Covid-19 pandemic, I thus include two dummy variables for 2008/2009 and 2020/2021; respectively.


** Results

*** Summary statistics

#+INCLUDE: "../tables/t_sumstats_wcpF.tex" export latex

Table {{{reftbl_t_sumstats}}} shows summary statistics for all variables.
#


*** Hazard rate and Age Dependence 

{{{ynkplt_p_hazard}}}

{{{ynkplt_p_surv}}}


Before discussing the regression models, I provide a descriptive account on private museum closure using the hazard and survival functions which describe variation the closing risk over the museum life-course.
# 
The hazard rate is a non-parametric function which describes the probability of exiting at age $t_i$ (conditional on being alive), in the context of museum-years as units of analysis it can be formulated as $h(t_i) = \frac{d_i}{n_i}$, with $n_i$ as the number of units at risk at age $t_i$ and $d_i$ as the number of exits at age $t_i$.
#
The survival function is the product of these conditional probabilities ($S(t) = \prod_{t_i \geq t} \left(1-h(t_i) \right)$) and describes the chance of surviving up to age $t_i$. 


Figure {{{refplt_p_hazard}}} shows the hazard rate over time, figure {{{refplt_p_surv}}} the corresponding survival probability.
#
The hazard rate increases strongly from {{{meanhaz_upto_2}}} in the first two years, to {{{meanhaz_upto_5}}} in the first 5 years, to {{{meanhaz_8to30}}} at year 8, around which it then fluctuates, leading to an average hazard of {{{meanhaz_upto_30}}} for the first 30 years[fn::While it is possible to calculate the average hazard over longer periods (e.g. the overall average hazard rate is {{{meanhaz_upto_100}}}), for ages above 30 only few observations are available, which make these predictions rather uncertain.].
# 
The increase in the first years is likely explained by the fact that as the establishment of a museum requires considerable resources, their founders have allocated enough resources to keep the risk of closure minimal in the first years after opening.

Such analysis can be used to estimate the average life expectancy of a private museum.
#
While only a fraction of all opened museums has closed ({{{pm_n_closed}}} out of {{{pm_n_used}}}), and even the complete survival function has not reached 0.5, under the assumption of average closing risk of {{{meanhaz_upto_8}}} in the first 8 years and {{{meanhaz_8to30}}} onwards, it is possible to predict the median life expectancy as approximately {{{median_life_expectancy}}} years (yet as only around half of this range is observed for a large number of museums, the certainty of such measurement is clearly limited).

**** comparison :ignhead:

Calculating such survival statistics allows (to a degree) to assess whether private museums differ in their longevity from comparable institutions.
#
So far only a small number of studies has investigated museum closing rates, and these have focused on the United States, likely primarily due to data availability reasons: 
#
Larger non-profits in the US have to file the IRS form 990 (or its variants) to maintain their tax-deductible status, and form data is publicly available [[parencite:&Lecy_2023_core;&Lecy_2023_core]].
# 
This data has been used in many studies of non-profit populations, and constitutes an effective comparison group for private museums as both share the same organizational form (non-profit) and unprofitable cultural sector environment.
#
So far three studies have used this data to investigate museum closure by calculating hazard rates not as a function of age age but of calendar year:
- [[textcite:&Bowen_etal_1994_charitable]] investigate the closing of 501(c)(3) museums in the 1981-1991 time period and, based on 271 (9.8%) closures of a population of 2755, calculate average annual exit rates as 1.1% (p.103).
- textcite:&Gordon_etal_2013_insolvency observe 35 closures over the years of 2000-2003 with 5,167 museum-years (p.368), resulting in an average annual closing rate of 0.68% (p.377).
- textcite:&Hager_2001_vulnerability has conducted the only study specifically on art museums (NTEE code A51); he observes 42 closures over a period of four years (1994-1997) from a starting populaton of 448 (p.383), corresponding to an average yearly closing rate of 2.4%, or around 1.9% under the more realistic assumption of effectively using a five-year time period.

Construcing private museum closing rates in a similar manner (as average of proportion closed each calendar year, rather than at each age) results in average closing rates of {{{yearhaz_all}}} overall, {{{yearhaz_from2010}}} for the period 2010-2011 and {{{yearhaz_allw}}} when weighing yearly closing proportions by the number of museums at risk.
#
Private museum closing rates thus do not appear substantially higher than the range of possible values established by previous studies, and in particular not higher than the closing rate of the most direct comparison group of non-profit art museums by [[textcite:&Hager_2001_vulnerability]]. 


**** comparison limitations :ignhead:
However, a number of limitations complicate such a comparison.
#
First, this measure of overall museum closing rates cannot take museum-level variables into account, thus direct comparability hinges on the assumption that on private museums display a similar distribution of survival-relevant attributes to US non-profit museums.
#
More specifically, private museums might have such disproportionately high assets and/or revenues that the appropriate comparison group would not be the entire (art) museum population, but rather only its in wealthiest half, third or quarter, which in turn could be characterized by substantially higher survival rates (such a size difference likely explains the difference between the hazard rates of [[textcite:&Gordon_etal_2013_insolvency]] and [[textcite:&Bowen_etal_1994_charitable]], as the former only includes museums with operational revenues above 150,000 USD).
#
Secondly, as previous studies have focused exclusively on the US, survival rates for non-profits in other countries might differ, for example in particular in Europe one possible reason might be more public support for non-profits.
#
While additional analyses, reported in the supplementary materials, do not indicate a substantial influence of time-invariant country (or region) factors on private museum closing, mortality of non-private museums might be stronger influenced by these country-level factors.
#
Thirdly, a number of limitations of form 990 data might lead to inaccurate mortality estimates in the first place.
# 
As closure is generally estimated from non-filing for a number of years, incorect closing assessments and mortality estimates can arise as organizations continue operations without filing, file but continue to exist only on paper, or transform thus producing records of several organizations while effectively only a single organization exists [[parencite:&Bielefeld_1994_survival]].
#
Taken together, these factors substantially limit the extent to which a lack of difference in closing rates between private museum and American non-profit museums in general is indicative of similar sustainability of these different organizational populations. 




*** Regression Results

#+INCLUDE: "../tables/t_reg_coxph_wcpF.tex" export latex

#
To investigate which covariates are associated with increased risk of closing, table {{{reftbl_t_reg_coxph}}} shows the results of Cox proportional hazard regression model.
#
Coefficients are interpeted as log hazard ratios, i.e. as multipliers of the baseline hazard rate.

**** Control Variables

#
Neither gender of the founder nor external shocks (the Great Recession and the Covid-19 Pandemic) are associated with significantly higher closing rates.
# 
Given the non-significant gender difference, it can be expected that the population of private museums will continue to remain a man-dominated affair, unless a strong increase in museum founding by women takes place.
# 
At the same time, this finding also provides no evidence that female founders face gender-specific challenges, at least not to an extent that these decrease the survival prospects of their private museums.
#
The insignificance of the coefficients of the external shocks indicate that museums are overall relatively resilient; possibly unlike other types of art organizations with lower assets and higher reliance on earned incomes [[parencite:&Bowen_etal_1994_charitable p.102]].   

# 
# inclusion of founder name is significantly associated with mortality rates.
#
# (TODO: add reference, very speculative!!)
# While generally organizations whose name include the name of their founder might be more centered around the founder, and hence display higher inertia, making them less able to adapt to changing environments, these results indicate that it does not seem to be case for private museums.



**** Founder dependence (H2)

***** death :ignhead:
#+INCLUDE: "../tables/t_reg_coxph_deathcfg_wcpF.tex" export latex

{{{ynkplt_p_surv_death}}}

The death of the founder is not associated with a significant difference (p={{{pvlu_founder_dead_binary}}}) in private museum closure, i.e. museums are not significantly more likely to close after their founder has died, which provides little support to H2a.
#
While the point estimate is positive ({{{coef_founder_dead_binary}}}, corresponding to a  {{{coef_founder_dead_binary_perc}}}% increase in mortality for museums whose founders have died compared to those who have not), the low risk overall means that despite the cumulative character even decade-long survival times do not differ substantially (figure {{{refplt_p_surv_death}}}).


# 
It is in principle possible to construct an alternative measure of founder death by partioning the time after the death in a short-term and long-term period; the short-term period might then capture the disruption by the founder, whereas the long-term period would only be reached by museums who have successfully acquired alternative funding models and are hence relatively viable.
#
However, the choice of choosing a cut-off point between the short- and long-term periods is relatively arbitrary.


Table \ref{tbl:t_reg_coxph_deathcfg} shows coefficients of both periods with different cut-off points.
#
While the coefficient in the short-term period is consistently higher than both the overall death coefficient and the long-term period coefficients, so far the evidence is inconclusive as only few cases are statistically significant[fn:: P-values are also not adjusted for multiple tests].
#
Furthermore, such a shock passes quickly relative to the predicted median life time of museums of {{{median_life_expectancy}}} years, thus "giving" the founder death little time to lead to many museum closures. 
# 



Considering the numbers underlying the death effect estimates illustrates the uncertainty of the determning the effect of the death of the founder on aclosing: 
# 
While {{{n_founder_dead}}} private museums have seen the death of their founders, only {{{n_pm_close_after_recent_death}}} of these have closed in the following 5 years; given such low numbers it cannot be ruled out that the statistical significance in a few configurations of founder death time results from random fluctuations rather than an underlying pattern.
#


***** artnews ranking :ignhead:

Other founder-level characteristics also do not indicate that founder-related variables are strongly associated to museum closure, as the coefficients of ARTnews ranking inclusion (measuring reputation) and inclusion of founder's name in the museum name are not statistically significant.
#
Museums whose founders are not included in the ARTnews collector ranking (reference category) are the least likely to close, followed by museums whose founders are included ({{{coef_an_inclusionincluded_perc}}}% elevated closing risk) and by founders who were included at some point but are no longer included ({{{coef_an_inclusiondropped_perc}}}% elevated closing risk).
#
However as none of the differences are statistically significant, they provide little support for hypothesis 2b.
#
It is also worth to point out that the order of the categories does not fully correspond to the expected order, according to which museums whose collectors are not included would be more likely to close than collectors who are.
#
However, as all differences are not statistically significant, there is no strong evidence that this reflects unexpected status mechanisms rather than randomness.
#

***** name :ignhead:


Museums whose name contain the name of the founder face a non-significantly {{{coef_muem_fndr_name_perc}}}% elevated risk of closure, which indicates that there is little evidence that founders face greater difficulties to secure a long-term future for their museums by choosing to emphasize their personal contribution; thus providing no support for hypothesis 2c.
#
# It was hypothesized that such central positioning of the founder might limit longevity by disincentivizing contributions by other parties.
#
# However, as the direct mechanism of declining contributions cannot be observed, its absence cannot be assumed either.
#
A possible explanation might be that even when other parties do indeed feel less inclined to contribute, these gaps are filled by a stronger commitment of the founder, who having committed her name to the initiative, wants to keep the museum open event at great costs.

***** founder conclusion :ignhead:



Taken together, the inability to explain private museum closing with the death of founder, her exclusion from a prestitious ranking and the presence of her name in the museum's name question the hypothesized central role of the founder (Hypothesis 2).
#
In other words, so far little evidence points to low diversification, i.e. reliance on founders, as a substantial source of involuntary closing risk for private museums.
#


**** Competition (H3)

{{{ynkplt_p_condmef}}}


Country-level measures of the private museum population show a marginally significant association with mortality (b={{{coef_pmdens_cry}}}, p={{{pvlu_pmdens_cry}}}).
#
While these results provide a support for evidence of competition on the country level leading to closure, it is worth noting that the observed relationship does not correspond to the generally accepted non-monotonic relationship between density and closures (as the linear term is positive, and the squared term not significant at p = {{{pvlu_pmdens_cry_sq}}}), which postulates that density increases at low densities reduce closing risk (corresponding to a negative linear coefficient), and increases at high numbers increase risk (corresponding to a positive squard term).


{{{ynkplt_p_pred_heatmap}}}


At the local level, the number of private museum and population numbers predict survival chances as the main effects of population and number of private museums as well as its interaction are significant.
#
The particular pattern however is complex:
#
As both main terms are positive and the interaction negative, at low values increases in either variable are associated with increases in mortality (figure {{{refplt_p_condmef}}}).
#
Thus, for population values of 0 to {{{popm_circle10_marg0}}} million people, an increase in the number of private museums corresponds to an increase in mortality (bottom half of figure {{{refplt_p_pred_heatmap}}}), which provides support for hypothesis 3 according to which competition leads to museum closure, in particular as this range includes {{{N_zonebottom}}} museums years, or {{{perc_zonebottom}}}% of the dataset. 
#
Yet at the same time, at low private museums numbers (0 to 3 private museums, left half of figure {{{refplt_p_pred_heatmap}}}), increases in population also increase mortality; this range also includes a large number of museum-years ({{{N_zoneleft}}} museum years; {{{perc_zoneleft}}}% of the data).
#
Such a relationship is unexpected insofar as it is unclear why a larger potential audience would be associated with a higher risk of closure.[fn::Alternative approaches of modeling competition are discussed in the supplementary materials, but cannot answer this question.]
#
A possible explanation might be that collectors in less densely populated areas are more committed than those in less populated areas precisely because they know they cannot count on visitors to contribute substantially.
#
Alternatively, areas with high population and low private museum numbers might more generally lack cultural infrastructure; which one could see supported by closures in Jakarta, Istanbul and Mexico City, but less so by closings in Paris, Tokyo or Madrid.
#
However, low private museums numbers indicating lack of cultural infrastructure might also explain the decrease in mortality associated with increases in private museum numbers at high population values (figure {{{refplt_p_pred_heatmap}}}, upper half), as such pattern does not correspond to that predicted by competition.
#
# maybe add something here that at high pop numbers competition might be harder to identify
# 
More in line with expectation is however the association between increases of population numbers and lower mortality at higher numbers of private museums (right half), as it indicates that audiences can facilitate museum survival.


Taken together, figure {{{refplt_p_pred_heatmap}}} indicates two niches as particular supportive of private museum survival, on the one hand remote areas with low population and no competing private museums, and on the other densely populated areas with at least some other private museums.


While not all associations correspond to predictions made by resource dependence, the most direct measurement of increased competition, number of private museums in the local surrounding, is associated with higher closing chances for a large part of the sample, which in turn supports the substantial role of competition (H3).



**** Identity (H4)

Museums which include the term "collections" in their name are the least likely to close ({{{coef_slfidfcncollection_exp}}} times the rate of museums with the name "museum", while those with the term foundation experience {{{coef_slfidfcnfoundation_perc}}}% elevated closure rates (but not significantly higher).
#
However, institutions which include neither of these are the most likely to close, and have mortality rates almost three times as high ({{{coef_slfidfcnother_perc}}}%) than institutions including the term "museum".
# 
The usage of unconventional names might reflect adherence to museum standards which makes museums more understandable and familiar to third parties (e.g. audiences, other museums, companies or the government) and thereby facilitates interactions which are beneficial for long-term survival (e.g. attracting visitors, cooperations, sponsorships or subsidies).
# 
However, as founders can choose the name of their museum arbitrarily, they might choose a name without reference to organizational forms associated with perpetuity precisely because their intention is not an institution enduring in perpetuity but rather a more temporally bounded project.
#
Some support for the latter interpretaton is given by the fact that two of the three museums for which [[textcite:&Velthuis_Gera_2024_fragility]] identify a temporal intention as the closing reason do not self-identify as museum, collection or foundation.
#
A temporal intentions are however the exceptions among closing reasons identified by [[textcite:&Velthuis_Gera_2024_fragility]] (p.6), and as similarly only a small fraction of private museum chooses such a name ({{{N_slfid_other}}} museums, or {{{perc_slfid_other}}}%), the overall proportion of these types of voluntary closures compared to all closures is presumably limited.
# oof is actually more than I thought.. FIXME




** Discussion and Conclusion

*** discusson :ignhead:

Previously the dozens of closures have been seen as indicator of their vulnerability and short-livedness [[parencite:&Adam_2020_close]], however this analysis shows the importance studying closing not in isolaton but in comparison to both non-closures and closures of comparable institutions.
#
While the booming numbers of private museums themselves have received substantial attention, less consideration has been given to the fact that large populations can generate dozens of closures without requiring high closing rates, especially when cloures are considered over a span of several years or decades.
#
In other words, the sheer size to which the private museum population has grown over the last decades has made it all but inevitable that some of them would close, and do so after only a few years.
#
Based on the current analysis, private museums will continue to close in the years to come; at hazard rates of around 1% on average a handful of closures every year are to be expected.



Comparing private museums closures to closures of other organizational form advances our understanding of the sustainability of this new organizational form.
#
While private museums do close, the comparison to previous studies of museum closing rates provides no evidence that dependence on single founders constitutes a less stable organizational form than reliance on less centralized foundations, associations or corporate sponsorship.
#
Multiple reasons might be the at play that mitigate this risk of low diversification.
#
First, it might take more commitment to open a museum as an individual or couple compared to less involved art patronage of being a board member in existing institutions or donating works, which would result in private museums founders being more motivated to secure the continued existence of their institutions.
# 
Furthermore, the centrality of the founder might leave little room to question who is responsible to provide additional funds in times of financial difficulties, whereas in organizations without a central figure each member may feel less responsible.
#
It might also be such commitment that leads founder to plan the future of their museum to such an extent that their death is not significantly associated with unvoluntary closing.
 



While so far little evidence points toward low diversification, i.e. reliance on the founder, as a key vulnerability of private museums to unvoluntary closures, the centrality of the founder may be more pronounced in voluntary closures. 
#
Indicated by unconventional naming choice, a subset of founders might from the very beginning envision the museum as temporary.
#
On the other hand, higher closing rates for unconventionally named museums might reflect absence of recognition and support by third parties in the environment.
#
A dimension where the influence of the environment can however be ascertained with greater certainty is the role of audiences and other private museums.
#
While the overall relationship is complex, for the majority of private museums increases in both variables are associated with higher closing rates.
#
Whereas it is plausible that the association between higher institution counts and closing rates reflects competitive pressures, it is less obvious what may lay behind observing a positive association behind larger population and closing risk. 








*** Limitations


**** little founder death :ignhead:
A number of limitations are worth considering:
# 
So far only a small fraction ({{{n_founder_dead}}} museums, {{{perc_founder_dead}}}%) of museums has experienced the death of their founder, one of the primary reasons hypothesized to lead to the private museum closure. 
#
While so far these museums have not seen substantially elevated closing risks, these estimates will become more precise as more founders pass away.
# 
As the currently large confidence interval (figure {{{refplt_p_surv_death}}}) for museums whose founders have died allows a wide range of survival chances, it is entirely possible that previous scholars have indeed correctly identified a key dependency (the current absence of evidence of it should not be taken as evidence of absence) and that therefore later analyses will a significantly association between founder death and closing risk as well as a higher average closing risk for private museums.[fn::Similarly, as 80% of private museums have been founded in the new millenium, only a few museums have so far reached an age above 30 years, which makes the estimation of the age-dependent hazard for this age range highly speculative.]
#
# This research shows that while it is important to use theory to predict relationships, the systematic empirical investigation of these should not be relegated either
#
At the same time, it is also possible that private museums are generally less dependent on a single person (or couple) than has been assumed, and have in fact become institutionalized to an extent that most heirs of founders feel as motivated to continue the original founders' efforts as these founders themselves.


**** comparison limited to american NPOs :ignhead:
# FIXME better integration to previous paragraph
While overall private museum closing rates are generally not diverging from museums in general, it has to be kept in mind that this comparison is based on American non-profit museums.
#
To my knowledge, currently no data sources exist that allow estimation of closing rates of (European) public, state-funded museums.
#
Although I argue that the American non-profit museums serve as a better comparison to evaluate private museum surival rates than state-funded museums because the comparison allows to focus on the centrality of the founder, the contrast to public museums would still provide additional insights into the relationship between ownership and survival rates.
#
While public museums have been characterized to some extent as very stable due to government picking up deficits [[parencite:&Meier_Frey_2003_faces;&Bechtler_Imhof_2018_future]], [[textcite:&Walker_2019_collector]] argues that due to declining cultural spending even public museums might face hard times.
#
Most national public flagship institutions might remain sufficiently funded to survive, however this may not be the case for the much larger of smaller museums in less touristic regions who rely on more limited municipal funding ({{{own_loc_reg_perc}}}% of the European museum population, [[cite:&EGMUS_2024_complete]]), as textcite:&StylianouLambert_etal_2014_museums explore for a number of smaller publicly funded ethnography museums in Cyprus.
#
Yet without access to museum registers comparable to the IRS/NCCS datasets, such questions of the relation between a wider range of organizational form and survival remain speculative.
#


**** lack of financials :ignhead:

The primary mechanism that has been argued to lead to museum closure is costs, and while this study measures it indirectly, primarily through indicators on the level of the founder, museum and environment, the financial situation of a museum is not used directly.
#
The primary reason for this is data availability.
#
While centralized non-profit financial information is available for American non-profits through the IRS/NCCS files, the much larger private museum population in the rest of the world is not subject to similar reporting requirements.
#
The effort to compile such information on a global scale ranges from extremely challenging (harmonizing different reporting standards, language barriers) to outright impossible for institutions who do not even (have to) report public financial information.
#
Similarly, other museum characteristics which were not considered here, such as as museum size, facilities, as well as marketing and outreach activities, might be related to long-term survival prospects.[fn::While the original data collection included the assessment of various museum characteristics, such as floor and collection size, facilities, and cooperations, it became clear during data analysis that the data collected was unsuitable to construct accurate indicators from these findings due to difficulty in assessing them in many cases.
Especially for closed museums data collection proved difficult, as in many cases websites had been shut down, and while in many cases snapshots of the main website were available in the Wayback machine, less central pages (such as those with information about facilities and activities), were archived much less frequently, and sometimes inaccessible despite being archived due to changes in webtechnology (such as the retirement of Adobe flash).]
#
As such, private museums remain relatively intransparent, which does not prevent, but to some extent limits the identification of risk factors. 


**** no transformation :ignhead:
For this study, I only investigated the occurence of closure events.
#
However, private museums can stop existing as private museums not just by closing down, but also by being transformed into other organizational forms.
#
One way in which this can happen is when other parties, such as local governments, other philanthropists, foundations, or corporations become substantially involved in the ownership, governance and/or funding of the museum.
#
Sometimes this involves changes in the composition of the board of directors (or equivalent), with new parties gaining seats and hence influence in decision-making, thereby diminishing the private character of the museum to an extent that it no longer fits the working definition.
#
Museums which experienced this trajectory have been excluded from the analysis as explorative investigation showed that it was not possible to consistently determine the date of such transitions.[fn:: Consequently they are excluded from the analysis alltogether, and thus also not contributing to the the hazard rate for closing, despite being entities at risk for closing for at least some time. However, as their numbers are limited to {{{pmdb_n_nlpm}}} entries in the database, the bias this introduces into closing risks is likely not substantial.]
#
The main issues that made the determination of the date impossible was the intransparency of these organizations, the gradual process of the transition, as well as that these events life often years or decades in the past.
# 
The possibility of other outcomes than surival and closures has been investigated for NPOs more generally
[[parencite:&Searing_2020_zombies;&HernandezOrtiz_2022_discontinuity;&Helmig_Ingerfurth_Pinz_2013_nonprofit]], and for private museums specifically on a case study basis: 
#
[[textcite:&Walker_2019_collector]] argues that in the case of Germany, private museum founders turn to the state to ensure the survival of their projects in the form of public-private partnerships.
#
Investigating this process of transformation into a different organizational form thus provides fruitful avenue for further research. 


**** environment :ignhead:
While this study has already included measures of both the national and local environment, the ability to clearly observe spatial museum location allows to measure environmental influences in greater detail.
#
For once, so far competition has been limited to other private museums, but geocoding of a wider range of institutions would lead to a more encompassing assessment of competitive and dynamics.
#
Furthermore, including wider institutional changes such as tax incentives, government subsidies, but also political changes and censorship would lead to a more complete description of risk factors, and in more detail identify niches which are particularly suited for private museums.





 
# *** future research
# The US register data on NPO tax filings constitutes a promising source for data for museum research (while this data source has seen frequent usage in non-profit management, it remains underexploited in the field of museum research). 
# #
# While the United States private museum population with {{{pmdb_n_US}}} museums and {{{pmdb_n_closed_US}}} closings might not be sufficient to test whether private museums have a a higher closing risks than other museums, it still hosts a large population of museums.
# #
# Thus this data can be used to establish average mortality estimates for museums generally as well as different types of museums, which can be compared to those observed for private museums globally. 
# #
# The availability of financial data for American institutions through the NCCS/IRS may also provide tentative insights into the finances of private museums. 




#+Latex: \begin{sloppypar}
#+Latex: \printbibliography
#+Latex: \end{sloppypar}


