#+latex_class: article_egos
# erases make title
# #+BIND: org-export-latex-title-command ""

# fucks all the maketitlestuff just to be sure
#+OPTIONS: num:nil
#+OPTIONS: toc:nil
#+OPTIONS: h:5



#+BEGIN_SRC R :session calc :exports none :results values drawer :dir /home/johannes/
library(jtls)
dt_nbrs <- fread("/home/johannes/Dropbox/phd/papers/closing/misc/nbrs.csv")
wd_nbrs(dt_nbrs)
## quit(save="no")
#+end_src

#+RESULTS:
:results:
# descs
#+MACRO: pmdb_n_all 548
#+MACRO: pmdb_open_atm 451
#+MACRO: pm_n_closed 68
#+MACRO: n_pmyears 6096
#+MACRO: pmdb_n_nlpm 25
#+MACRO: pmdb_n 523
#+MACRO: pmx_n 505
#+MACRO: n_founder_dead 47
#+MACRO: n_pm_close_after_recent_death 3
#+MACRO: pm_open_from2021 15
#+MACRO: pm_n_used 503
#+MACRO: mow_prop_name_museum 71


# meanhaz
#+MACRO: meanhaz_upto_2 0.10%
#+MACRO: meanhaz_upto_4 0.49%
#+MACRO: meanhaz_upto_5 0.69%
#+MACRO: meanhaz_upto_8 0.73%
#+MACRO: meanhaz_upto_10 0.89%
#+MACRO: meanhaz_upto_20 1.09%
#+MACRO: meanhaz_upto_30 1.16%
#+MACRO: meanhaz_upto_40 0.96%
#+MACRO: meanhaz_upto_100 0.90%
#+MACRO: meanhaz_8onwards 0.92%
#+MACRO: meanhaz_8to30 1.20%
#+MACRO: median_life_expectancy 52


# yearhaz
#+MACRO: yearhaz_all 0.84%
#+MACRO: yearhaz_allw 1.12%
#+MACRO: yearhaz_upto2010 0.21%
#+MACRO: yearhaz_from2010 1.36%


# pltcfgs
#+MACRO: ynkplt_p_vrblcvrg_ugrpd (eval (concat "#+label: fig:p_vrblcvrg_ugrpd\n" "#+caption: PMDB variable coverage by museum status\n" "#+attr_latex: :width 19cm\n" "[[file:../figures/p_vrblcvrg_ugrpd.pdf]]"))
#+MACRO: ynkplt_p_vrblcvrg (eval (concat "#+label: fig:p_vrblcvrg\n" "#+caption: PMDB variable coverage by museum status and variable group\n" "#+attr_latex: :width 19cm\n" "[[file:../figures/p_vrblcvrg.pdf]]"))
#+MACRO: ynkplt_p_vrblcvrg_ratio (eval (concat "#+label: fig:p_vrblcvrg_ratio\n" "#+caption: PMDB variable coverage (abs/rel prop) by museum status and variable group\n" "#+attr_latex: :width 18cm\n" "[[file:../figures/p_vrblcvrg_ratio.pdf]]"))
#+MACRO: ynkplt_p_surv (eval (concat "#+label: fig:p_surv\n" "#+caption: Private Museum Survival probability\n" "#+attr_latex: :width 14cm\n" "[[file:../figures/p_surv.pdf]]"))
#+MACRO: ynkplt_p_hazard (eval (concat "#+label: fig:p_hazard\n" "#+caption: Private Museum hazard function\n" "#+attr_latex: :width 16cm\n" "[[file:../figures/p_hazard.pdf]]"))
#+MACRO: ynkplt_p_hazard_time (eval (concat "#+label: fig:p_hazard_time\n" "#+caption: Private Museum hazard function by year\n" "#+attr_latex: :width 16cm\n" "[[file:../figures/p_hazard_time.pdf]]"))
#+MACRO: ynkplt_p_agedens (eval (concat "#+label: fig:p_agedens\n" "#+caption: Age distribution of private museums\n" "#+attr_latex: :width 17cm\n" "[[file:../figures/p_agedens.pdf]]"))
#+MACRO: ynkplt_p_yeardens (eval (concat "#+label: fig:p_yeardens\n" "#+caption: Private Museum-year Distribution\n" "#+attr_latex: :width 19cm\n" "[[file:../figures/p_yeardens.pdf]]"))
#+MACRO: ynkplt_p_coxphdiag_more (eval (concat "#+label: fig:p_coxphdiag_more\n" "#+caption: Model Diagnostics\n" "#+attr_latex: :width 19cm\n" "[[file:../figures/p_coxphdiag_more.pdf]]"))
#+MACRO: ynkplt_p_pred_popprxcnt (eval (concat "#+label: fig:p_pred_popprxcnt\n" "#+caption: Predicted Avg. Hazard Rate on Regional PM Density and Population\n" "#+attr_latex: :width 18cm\n" "[[file:../figures/p_pred_popprxcnt.pdf]]"))
#+MACRO: ynkplt_p_pred_proxcntpop (eval (concat "#+label: fig:p_pred_proxcntpop\n" "#+caption: Predicted Avg. Hazard Rate on Regional PM Density and Population\n" "#+attr_latex: :width 18cm\n" "[[file:../figures/p_pred_proxcntpop.pdf]]"))
#+MACRO: ynkplt_p_condmef (eval (concat "#+label: fig:p_condmef\n" "#+caption: Conditional effects of Regional PM Density and Population\n" "#+attr_latex: :width 18cm\n" "[[file:../figures/p_condmef.pdf]]"))
#+MACRO: ynkplt_p_pred_heatmap (eval (concat "#+label: fig:p_pred_heatmap\n" "#+caption: Predicted Avg. Hazard Rate on Regional PM Density and Population (at available values)\n" "#+attr_latex: :width 18cm\n" "[[file:../figures/p_pred_heatmap.pdf]]"))
#+MACRO: ynkplt_p_heatmap_info (eval (concat "#+label: fig:p_heatmap_info\n" "#+caption: heatmap info plots\n" "#+attr_latex: :width 35cm\n" "[[file:../figures/p_heatmap_info.pdf]]"))
#+MACRO: ynkplt_p_pred_heatmap_wocryside (eval (concat "#+label: fig:p_pred_heatmap_wocryside\n" "#+caption: Predicted Avg. Hazard Rate from Regional PM Density and Population (without proxcnt < 2 & popm_circle10 <2)\n" "#+attr_latex: :width 18cm\n" "[[file:../figures/p_pred_heatmap_wocryside.pdf]]"))
#+MACRO: ynkplt_p_pred_heatmap_onlycryside (eval (concat "#+label: fig:p_pred_heatmap_onlycryside\n" "#+caption: Predicted Avg. Hazard Rate from Regional PM Density and Population (only proxcnt < 2 & popm_circle10 <2)\n" "#+attr_latex: :width 18cm\n" "[[file:../figures/p_pred_heatmap_onlycryside.pdf]]"))
#+MACRO: ynkplt_p_surv_death (eval (concat "#+label: fig:p_surv_death\n" "#+caption: Comparison of Survival Estimates by Founder Death (95% CI)\n" "#+attr_latex: :width 18cm\n" "[[file:../figures/p_surv_death.pdf]]"))
#+MACRO: ynkplt_p_lngtdvelp (eval (concat "#+label: fig:p_lngtdvelp\n" "#+caption: Composition of private museum population\n" "#+attr_latex: :width 18cm\n" "[[file:../figures/p_lngtdvelp.pdf]]"))


# figlbls
#+MACRO: refplt_p_vrblcvrg_ugrpd \ref{fig:p_vrblcvrg_ugrpd}
#+MACRO: refplt_p_vrblcvrg \ref{fig:p_vrblcvrg}
#+MACRO: refplt_p_vrblcvrg_ratio \ref{fig:p_vrblcvrg_ratio}
#+MACRO: refplt_p_surv \ref{fig:p_surv}
#+MACRO: refplt_p_hazard \ref{fig:p_hazard}
#+MACRO: refplt_p_hazard_time \ref{fig:p_hazard_time}
#+MACRO: refplt_p_agedens \ref{fig:p_agedens}
#+MACRO: refplt_p_yeardens \ref{fig:p_yeardens}
#+MACRO: refplt_p_coxphdiag_more \ref{fig:p_coxphdiag_more}
#+MACRO: refplt_p_pred_popprxcnt \ref{fig:p_pred_popprxcnt}
#+MACRO: refplt_p_pred_proxcntpop \ref{fig:p_pred_proxcntpop}
#+MACRO: refplt_p_condmef \ref{fig:p_condmef}
#+MACRO: refplt_p_pred_heatmap \ref{fig:p_pred_heatmap}
#+MACRO: refplt_p_heatmap_info \ref{fig:p_heatmap_info}
#+MACRO: refplt_p_pred_heatmap_wocryside \ref{fig:p_pred_heatmap_wocryside}
#+MACRO: refplt_p_pred_heatmap_onlycryside \ref{fig:p_pred_heatmap_onlycryside}
#+MACRO: refplt_p_surv_death \ref{fig:p_surv_death}
#+MACRO: refplt_p_lngtdvelp \ref{fig:p_lngtdvelp}


# reftbl
#+MACRO: reftbl_t_coxzph \ref{tbl:t_coxzph}
#+MACRO: reftbl_t_reg_coxph \ref{tbl:t_reg_coxph}
#+MACRO: reftbl_t_sumstats \ref{tbl:t_sumstats}
#+MACRO: reftbl_t_selfid \ref{tbl:t_selfid}
#+MACRO: reftbl_t_reg_coxph_density \ref{tbl:t_reg_coxph_density}
#+MACRO: reftbl_t_reg_coxph_timeslice \ref{tbl:t_reg_coxph_timeslice}
#+MACRO: reftbl_t_reg_coxph_deathcfg \ref{tbl:t_reg_coxph_deathcfg}
#+MACRO: reftbl_t_drop1 \ref{tbl:t_drop1}
#+MACRO: reftbl_t_reg_coxph_timecfg \ref{tbl:t_reg_coxph_timecfg}


# coefs
#+MACRO: coef_genderF -0.038
#+MACRO: coef_gendercouple -0.140
#+MACRO: coef_pmdens_cry 0.648
#+MACRO: coef_I(pmdens_cry^2) -0.027
#+MACRO: coef_slfidfcnfoundation 0.203
#+MACRO: coef_slfidfcncollection -0.454
#+MACRO: coef_slfidfcnother 1.091
#+MACRO: coef_founder_dead_binary 0.280
#+MACRO: coef_muem_fndr_name 0.048
#+MACRO: coef_an_inclusionincluded 0.193
#+MACRO: coef_an_inclusiondropped 0.460
#+MACRO: coef_proxcnt10 0.263
#+MACRO: coef_popm_circle10 0.268
#+MACRO: coef_recession -1.586
#+MACRO: coef_covid 0.423
#+MACRO: coef_proxcnt10:popm_circle10 -0.089
#+MACRO: coef_genderF_exp 0.96
#+MACRO: coef_gendercouple_exp 0.87
#+MACRO: coef_pmdens_cry_exp 1.91
#+MACRO: coef_I(pmdens_cry^2)_exp 0.97
#+MACRO: coef_slfidfcnfoundation_exp 1.23
#+MACRO: coef_slfidfcncollection_exp 0.63
#+MACRO: coef_slfidfcnother_exp 2.98
#+MACRO: coef_founder_dead_binary_exp 1.32
#+MACRO: coef_muem_fndr_name_exp 1.05
#+MACRO: coef_an_inclusionincluded_exp 1.21
#+MACRO: coef_an_inclusiondropped_exp 1.58
#+MACRO: coef_proxcnt10_exp 1.30
#+MACRO: coef_popm_circle10_exp 1.31
#+MACRO: coef_recession_exp 0.20
#+MACRO: coef_covid_exp 1.53
#+MACRO: coef_proxcnt10:popm_circle10_exp 0.92
#+MACRO: coef_genderF_perc 3.9
#+MACRO: coef_gendercouple_perc 15
#+MACRO: coef_pmdens_cry_perc 91
#+MACRO: coef_I(pmdens_cry^2)_perc 2.8
#+MACRO: coef_slfidfcnfoundation_perc 23
#+MACRO: coef_slfidfcncollection_perc 58
#+MACRO: coef_slfidfcnother_perc 198
#+MACRO: coef_founder_dead_binary_perc 32
#+MACRO: coef_muem_fndr_name_perc 4.9
#+MACRO: coef_an_inclusionincluded_perc 21
#+MACRO: coef_an_inclusiondropped_perc 58
#+MACRO: coef_proxcnt10_perc 30
#+MACRO: coef_popm_circle10_perc 31
#+MACRO: coef_recession_perc 389
#+MACRO: coef_covid_perc 53
#+MACRO: coef_proxcnt10:popm_circle10_perc 9.3
:end:


* It's so over
# Short-lived legacies: The closure of private art museums
# Non-diversified but stable? The paradox of private museum closing rates
# Johannes Aengenheyster

# #+latex: \noindent
# Phd student at University of Amsterdam

# #+latex: \noindent
# j.aengenheyster@uva.nl


** Introduction

In recent years, private collector-run museums have seen an unprecedented proliferation, with hundreds of organizations founded since the beginning of the millenium [[parencite:&Velthuis_etal_2023_boom;&LarrysList_2015_report]].
#
These museums, run by individual collectors, constitute an addition to established organizational forms of art provision such as museums operated and financed by the state, foundations or associations.
#
While the emergence of this organizational form has attracted attention (cf. [[cite:&Kolbe_etal_2022_privatemuseum]] for a literature review), the process of closure has received considerably less attention.
#
In this paper, I address this gap by investigating the closure event of members of this new organizational form.
#
Analysis which factors are associated with museum closures provides insight not only into the event of closing, but also into the ongoing processes of a private museums, such as dependency relationships.
#
Furthermore, analyzing which museums survive allows to make informed speculations on the future of this recently emerged organizational form.


# too variable-based
# A number of findings emerge from this.
# #
# Museums that close are characterized by a name that does not include the term museum, foundation, or collection; a museums chance to close is also higher if it is located in an area with low population density and meany other museums.
# #
# On the flipside, a number of variables show no association with closing:
# #
# Whether a founder dies or is excluded from a prestigious ranking does not significantly influence a museums survival prospects, nor does the founders gender or whether the founder's name is included in the museum name.
# #
# The death of the founder, their gender, whether


# A number of findings highlight the role of identity in the process of private museum closure. 
# # 
# First, I find that museums which are recognized by an international museum database are less likely to close than those which are not.
# #
# Secondly, the results furthermore indicate that museums with more ambiguous names are more likely to close.
# #
# Both these findings possibly indicate that adherence to museum standards enhances legitimacy, which in turn improves survival prospects.
# #
# Finally, founder reputation, in particular its loss, is found to be substantial as museums whose founders are dropped from a collector ranking are more likely to close than museums whose founders both are and are not included.

# #+latex: \bigbreak
# #+latex: \noindent
# *keywords*: museum, closure, identity




*** Contributions :noexport:
- Intransparent founder motivations

Despite their occasionally spectacular/sensationalist press coverage, these institutions and the motivations of their founders have remained remarkably intransparent.
#
Financed in large parts by their founders' private wealth, few reporting requirements exists; and while some founders highlight their charitable and distintersted intentions in media coverage, such statements intended for a public audience might not necessarily reflect underlying founder motivations accurately.

This study (attempts to) elucidate the hard-to-observe collector motivations by studying one of the most decisive actions that their founder can take: the decision to close the museum.
#
Besides investigating the longevity of members of this new organizational form, this study gives insights into the motivations and decision making of founders.
# 
In other words, what can the factors leading to the closure of private museums tell us about the internal processes and dependence relationships of these institutions, as well as about the motivations of their founders?


- comparison to other forms (more descriptively)
- NPM angle:
  - environment
  - quantitative
  - legitimation

- voluntary vs non-voluntary closing

# interrelated question of sustainability/longevity and collector decision making

# Thinking about private museums can take place along several discourses:
# - celebratory, disinterested, giving back to community 
# - critical: self-promotional, focus on inequality/legitimacy/status

  


** Private museums definition

#+latex: \bigbreak
#+latex: \noindent
Private museums:
- founded by collector -> needs to have amassed substantial art collection
- building of its own, limited public/corporate funding, has to be visitable -> requires substantial resources




** Private museums dependencies

*** chronic lack of money of NPOs :ignhead:
:PROPERTIES:
:CREATED:  [2024-08-23 vr 12:03]
:ID:       746567b9-2f82-4a7e-afa9-726c2646812b
:END:
Private museums have been argued to be highly dependent on their founder for their continuing existence, as museums generally cannot cover expenses via revenues from ticket prices, museum shops and cafes.
#
The [[textcite:&IMLS_2008_funding]] found that for non-profit American art museums, less than half (48.1%) the revenues come from earned income, leaving substantial gaps in the budgets that are filled by a mix of private donations (23.0%), investment (18.5%) and government support (10.4%) (p.27).
#
Outside of the United States, the reliance on revenue streams beyond operations is even larger:
#
German museums have had on average only 27% of their expenses covered by operations [[parencite:&Martin_1993_museen p.233]], and even the more market-oriented NPOs in the cultural sector draw around 50% of their funding from public support [[parencite:&Zimmer_Priller_2007_gemeinnuetzig p.82]].


Given that operating at "the margin of financial sustainability" is the "ordinary condition" for cultural NPOs, [[cite:&Licci_BaraldiBonini_2024_sustainability p.2]], it is not surprising that costs have been listed as a primary reason for private museum closure:
# 
[[textcite:&Adam_2021_rise]] argues that "most of the cases of defunct private museums come back to the issue of cost" (p.79); a sentiment shared by [[textcite:&Walker_2019_collector]] who notes that "private institutions struggle to contain escalating costs that are associated with running a museum" (p.234).
#
In other studies, "insufficient funding, high maintenance costs and lack of strong government support" [[parencite:&Zennaro_2017_shanghai p.7]], a "shortage of fundings and interruptions in cash" [[parencite:&Song_2008_private p.45]], bankruptcies [[parencite:&Velthuis_Gera_2024_fragility;&Liu_2019_identities;&DeNigris_2018_museums]], costly legal battles [[parencite:&Velthuis_Gera_2024_fragility]], stock devaluations [[parencite:&Walker_2019_collector]] or failing auction sales [[parencite:&Bechtler_Imhof_2018_future]] were central reasons that forced private museums to close.
#
In a systematic review of closing reasons given in newspapers, magazines, social media accounts and personal exchanges, [[textcite:&Velthuis_Gera_2024_fragility]] find financial issues as the most commonly mentioned reasons for private museum closing.

*** diversification
**** founder reliance -> diversification :ignhead:

#
A central reason for financial vulnerability has been argued to be the crucial reliance on the single founder, who, as the iniators of their private museums, likely have to contribute a large part of their institution's non-operating income [[parencite:&Frey_Meier_2002_beyeler]]:
# 
[[textcite:&Adam_2021_rise]] argues that "ultimately, many of these failures demonstrate the fragility of spaces that rely on a single founder, whose motivations and financial stability may change, or who may not have realised the difficulties inherent in establishing their own art space" (p.82).
# 
[[textcite:&Velthuis_Gera_2024_fragility]] similarly argue that "because of their funding models and reliance on a sole founder, [private museums] are inherently fragile organizations" (p.1).
#
[[textcite:&Bechtler_Imhof_2018_future]] also characterize "the dependency on single individuals only" as one of main reasons that "make these private museums fragile" (p.53).
#
[[cite:&StylianouLambert_etal_2014_museums]] also characterizes many private institutions as "small individual museums that depend too much on their creators to guarantee their sustainability" (p.582).
#
Beyond a direct financial component, private museums have been also been characterized as fragile since they can only rely on their founder for "taste", "vision and drive" [[parencite:&Adam_2021_rise p.77]], "passion" [[parencite:&Walker_2019_collector p.234]] or "skills and knowledge" [[parencite:&StylianouLambert_etal_2014_museums p.580]].
#
The link between diversification and mortality, i.e. higher survival chances for more diversified organizations, has been found for non-profit organizations more generally parencite:&Fernandez_2007_dissolution;&Bielefeld_1994_survival;&Hager_2001_vulnerability;&Lu_Shon_Zhang_2019_dissolution[fn::An larger literature exists shows a link between diversification and measures of financial health and sustainability besides survival [[parencite:&Licci_BaraldiBonini_2024_sustainability]]]; it is thus plausible to apply to museums as well.



**** death :ignhead:

Lack of diversification is then argued to pose a problem in particular in the case of the founder's death:
#
textcite:&Walker_2019_collector argues that "the death of the original founder and creator can [...] place the future of private museums and collections in jeopardy" as "seldom do heirs share a similar passion or wish to take on the financial burden of maintaining private museums indefinitely" (p.234). 
#
[[textcite:&Bechtler_Imhof_2018_future]] argue that in order to ensure museum longevity, "flexible, easily adapted designs for private museums" are necessary "to reduce the financial burden on their heirs" (p.188).
# can't find it online by koolhaas
# [[cite:&Koolhaas_2008_ideology]] is more about using public museums as storage
# 
[[textcite:&Adam_2021_rise]] argues that succession introduces strains in financial aspects ("Collectors’ successors may not look kindly on what may well be a money pit when [...] they will have to pick up the bills", p.77), which also concerns an aesthetic dimension ("the nature of contemporary art is to be fresh and new, but what is ‘fresh and new’ for the founder might seem ‘old hat’ to their heirs", p.76).
#
[[textcite:&Velthuis_Gera_2024_fragility]] similarly argue that "the founder’s death will almost inevitably have a direct impact on the financial health of the museum" (p.10).
# this is not about closing, just health
#
[[cite:&StylianouLambert_etal_2014_museums]], after discussing a case of a private museum whose owner "does not believe that anyone else could love the museum as much as she does", argues that this "generates questions regarding the cultural sustainability of small private museums in cases where their initiators are not able to care for them any longer" (p.580).

**** comparison lacking :ignhead:

Overall, two related arguments emerge from the current literature:
#
First, individual private museums rely on heavily on their founders for survival; events that interrupt the founders ability to provide resources are therefore associated with a highler likelihood of closing.
#
Second, due to their low diversification (high reliance on the founder), private museums have are more fragile than museums where single individuals are not comparably central figures.



While private museums are thus generally characterized as fragile, it is not always clear in relation to whom.
# FIXME: relation to whom?
#
Among the most explicit is [[textcite:&Walker_2019_collector]], who characterizes public institutions as relatively stable (which constitutes the reason why private collectors aim to form cooperations with them); [[textcite:&Bechtler_Imhof_2018_future]] implicitly also highlight the longevity of state-run institutions.
#
However, no systematic data is used to estimate public museum longevity, and while some
remarks are made that public spending cuts might result in problems for public museum operations (p.XX), the overall characterization of them remains as immortal [[parencite:&Frey_Meier_2002_beyeler]].
#
Responsible for the characterization of private museums as fragile might also be implicit reliance on the ICOM definition [[parencite:&ICOM_2024_definition]] of museums as "permanent institutions", according to which every closing is indicative of fragility.
#
So far a third comparison has been absent, namely that to other non-profit museums which are not initiated and run by a single collector, but by a wider group of founders or foundations.
#
As these share with private museums a common organizational form of the non-profit organization or foundation  and a similarly harsh environment, yet and differ primarily in regards to their diversification, i.e. their reliance on a single founder as central authority and income stream, they provide a effective way of investigating the effect of diversification on museum survival. 


*Hypothesis 1*: Private museums have higher closing chance than non-profit museums generally.

# *Hypothesis 2*: A founder's death increases the risk of closing.
# *Hypothesis 2*: Private museums with higher reliance on the founder are more likely to close

*Hypothesis 2*: Reliance on the founder is the mechanism through which PMs are exposed to a higher closing risk, thus founder-related variables predict closing, in particular
- *Hypothesis 2a*: Private museums are more likely to close after the death of the founder.
- *Hypothesis 2b*: Private museums are more likely to close after their founder is excluded from a prestigious ranking.
- *Hypothesis 2c*: Private museums which carry their founder's name in the museum name are more likely to close.




*** environment :ignhead:

While the low diversification, i.e. the centrality of the founder for museum finances, has been argued to constitute the key feature of private museum vulnerability, it is also important to consider the other ways in which private museums, as (non-profit) organizations, are entangled with their environments.
#
Its ability to attract audiences, which may involve competition with other museums, secure cooperations with other museums, acquire sponsorships from cooperations and fundings from governments and other foundations are likely factors that contribute to its viability and hence longevity.
# 
While some of these aspects can be influenced by the founder (in particular the available audience, via being able to decide a location and the extent to which a museum should organize exhibitions), other are less so.
#
In particular when they rely on the decision-making of other art-field actors, such as competition with other museums and sponsorship/funding choices, the influence of the individual founder is severely limited.
#
# The image that these parties have of the private museum might be substantial importance in guiding their decision-making.


**** Competition



mechanism: losing motivation?


Private museums have been characterized as highly competitive.
#
While some self-descriptions focus on collaborative aspect, previous studies have highlighted how private museums compete with public museums over art works, audiences, sponsoring and donors [[parencite:&Kolbe_etal_2022_privatemuseum p.4]]. 
#
So far the primary interest of investigating competition has been to evaluate whether private museums pose a threat to art provision by public institutions.
#
However, less focus has been given to the fact that operating in a competitive environment may also have consequences for the private museums themselves, in particular their survival aspects.
# 
While private museums presumably depend on their founder to a large extent, income from tickets and facilities, as well sponsorships and public support possibly also constitute other non-negligible revenue streams.
# 
While competition directly has not yet been investigated as a cause for private museum closing, a possible mechanism of competition, "insufficient interest from the public", has been identified as the second most mentioned closure reason by [[textcite:&Velthuis_Gera_2024_fragility p.6]]. 
#
Lack of interest by the public can be a consequence of multiple processes.
#
While competition is one such processes, and applies if nearby competing institutions capture large portions of the audience, lack of interest can also result from a lack of audience (in the absence of competing institutions), which may be the case for private museums located in sparsely populated areas [[parencite:&Foster_2015_cube]].
#
In both these cases, the resources that a private museum is able to receive from actors in its environment are limited. 



Previous research into non-profit dissolution has often investigated competition as a cause of closure, with both qualitative and quantitative studies indeed identifying competition as a frequent closure reason.
#
Qualitative studies which trace the history and/or closing reasons for each organization individually have highlighted competition over funding.
# 
textcite:&Hager_1999_demise reports that "both individual donations/subscriptions and community and corporate grants tended to go to the singular, most reputable arts organizations of their types", resulting in "strong competitive pressures" for the vast majority of organizations (ibid.).
#
Similarly, [[textcite:&HernandezOrtiz_2022_discontinuity]] found that an "[increasingly] crowded niche increased the competition and limited [NPOs'] access to resources and clients" (p.116) with an informant stating that "there was less money to go around and more organizations seeking the money [...] we had a full-time grant writer, we were always applying for grants. But there are so many organizations applying for the same grants" (ibid.).
#
Quantitative studies have identified a relation between competition and non-profit closing primarily via measuring competition over density [[cite:&Park_Shon_Lu_2021_mortality;&Haugh_etal_2021_nascent;&Lu_Shon_Zhang_2019_dissolution]], with higher number of non-profits increasing the chance of non-profit dissolution.



*Hypothesis 3*: A private museum is more likely to close in a more competitive environment.
  
  

**** Identity 
# provide legitimacy

The mere availability of audiences and other potential donors might however not be sufficient if a museum is not perceived as deserving support; i.e. if its identity is found lacking. 
#
An identity that is legitimate (understandable) and favorable (positive) has been argued to have a vast number of positive outcomes for organizations [[parencite:&Lange_Lee_Dai_2010_reputation]].
# 
As gaining the approval of different stakeholders is necessary for being understood and/or supported by other organizations in the environment, having a clearly defined and favorable identity influences resource acquisition and thereby survival prospects [[parencite:&Rao_1994_reputation]].
#
Even for non-profit organizations such as museums, which do not produce tangible goods (a domain where identity-related effects are especially prevalent, e.g. [[cite:&Hsu_2015_granted;&Bogaert_etal_2014_ecological]]), a clear and positive identity might be helpful in a number of ways:
# 
In the context of private museums, decline of legitimacy or reputation could lead to lower visitor numbers, less discounts from art dealers, less government grants or lower chances on collaborations with other museums or corporations, resulting in lower revenues and higher acquisition costs.


The empirical record of the link between identity and survival for non-profit organizations is mixed: 
# 
For example [[textcite:&Bielefeld_1994_survival]] finds that NPOs who pursue less legitimation strategies (obtaining endorsements, lobbying or contributing to local causes) are more likely to close, and [[textcite:&HernandezOrtiz_2022_discontinuity]] observes a declining image or reputation as a cause of closure in a number of non-profits (p.115).
#
However, other studies find little to no effect of legitimacy on survival, both when measured via density parencite:&Bogaert_etal_2014_ecological or from archival sources and interviews [[parencite:&Fernandez_2007_dissolution]].
# 
# Thus, even while this study cannot conclusively answer the overall link between idenity and survival, it nevertheless contributes insights into which dimensions of organizational identity do, and which do not contribute to survival in a particular organizational population; namely that of private art museums.


Legitimacy might be obtained by isomorphism, i.e. adopting features associated with blueprints [[parencite:&diMaggio_1983_iron]].
#
# Understandability [[parencite:&Glynn_Abzug_2002_names]] might thus be limited if an organization is atypical [[parencite:&Rosch_1975_family]], i.e. displays an unusual combination of features.
# #
# In the case of private museums, such cases might be combinations of features from house museums (e.g. accessibility only by appointment) with full-service museums (e.g. extensive activities). 
#
Next to "hard" organizational features, adherence to naming conventions has been found to enhance legitimacy [[parencite:&Glynn_Abzug_2002_names]]; organizations that adhere to field norms about name length, name ambiguity (usage of artificial names) and name domain specificity (mentioning industry) were judged more legitimate. 
# 
However, the category of museums could be relatively flexible (for example, it is generally not subject to state regulation), which might result in a relatively high tolerance of diversity as "anything goes" and hence limited "devaluation" of non-conforming, atypical members [[parencite:&Bogaert_etal_2014_ecological]].


Furthermore, identity of a private museum may be influenced by the identity of persons most closely affiliated with it, in particular the identity of its founders.
#
Given that founders are the very reason behind the existence of these organizations, and sometimes plan these as their personal legacies [[parencite:&Walker_2019_collector]], founder status gains or losses may reflect on the wider organization and affect its survival propspects.


#+latex: \bigbreak
#+latex: \noindent
*Hypothesis 4*: Private museums with identities more understandable and favorable are less likely to close. 


# FIXME
It is however necessary to consider that in particular the name of a museum might be associated with a museum's survival via identity, but also reflect founder intentions regarding the institutions longevity.
#
This is discussed in more detail below.
#
Furthermore, inferring the status of the museum via the reputaton of the founder again explores the extent to which the founder is a figure of central importance for the private museum.




** Data and Methods


A newly constructed database, assembled from different sources,  is used to measure the survival of private museums (cf. [[textcite:&Velthuis_etal_2023_boom]] for details).
#
Currently, the database includes {{{pmdb_n_all}}} museums (of which {{{pmdb_open_atm}}} are currently open, the remainder having closed or transformed into other organizational forms).
#
Using this database, in particular year of opening and, if available, closing, it is possible to reconstruct the life course of the each institution with museum-year as the unit of analysis.
#
This data allows to conduct survival analysis (also known as event history analysis), the most common statistical technique to investigate hazard rates and identify mortality-assocated covariates parencite:&Moore_2015_survival;&Allison_2014_event.



Hypothesis 1 (comparing closing risk between private museums and other, more diversified institutions) ideally would use a complete population of museums to identify the effect of institutional form on closing rate.
#
However, as no institutions are maintaining museum databases on a global scale, I use existing quantitative studies of museum closure to compare to these  private museums in terms of their closing rates.
# 
This non-parametric method estimates the hazard rate as the conditional probability of exiting at time t_i given being alive as $h(t_i) = \frac{d_i}{n_i}$, (with $n_i$ as the number of units at risk at time $t_i$ and $d_i$ as the number of exits at time $t_i$), and the survival function as the product of these conditional probabilities as $S(t) = \prod_{t_i \geq t} \left(1-h(t_i) \right)$.


Hypothesis 2 to 4, which differentiate the private museum population according to a number of risk factors, are investigated via Cox proportional hazard models. 
#
The main dependenent variable is here indicator of museum closure, which takes the value of 1 for the museums which close in the year of their closure, and 0 otherwise.
#
Typically for survival data, museums that do not close during the observation period are right-censored, i.e. for such museums the dependent variable is zero for all years.
#
The Cox-proportional hazard model has the form $h(t,\mathbf{x}) = h_0(t) \psi$, where $\psi = \exp(\sum_{j} \mathbf{x}_j \beta_j)$; with $h(t)$ as the hazard rate, $h_0(t)$ as the baseline hazard rate, $\mathbf{x}$ as the set of variables indexed by $j$, and $\beta$ as the coefficient vector.
#
Partial maximum likelihood estimation allows calculating \beta without defining the baseline hazard rate, which therefore is not constrained to a parametric form parencite:&Moore_2015_survival.
 



*** Main Predictors (Cox Proportional Hazards Model)

# The organizational identity of a museum is measured primarily in terms of its legitimacy, i.e. its adherence to museum standards, and reputation of its founders.

**** Founder death
:PROPERTIES:
:CREATED:  [2024-04-07 zo 15:06]
:ID:       764f17aa-0bd3-400b-a3ee-d72770e988f1
:END:

A measure of founder death is constructed as a time-varying covariate, which can take the values of the founder being alive, having deceased recently (the year in question and the year after that), and having been deceased for more than 2 years.
#
While it would have been possible to model founder death as a binary variable, two separate stages of death allows to separately investigate the short- and long-term impacts.


# should I have founder name here as well? would tie in to diversification


**** Legitimacy

#+include: "../tables/t_selfid_wcpF.tex" export latex

Two measures are constructed that aim to capture an effect of legitimacy on closing.
#
First, self-identification measures whether a the name of a museum includes the term "Museum", "Foundation", "Collection", or other (such as "Villa", "Institute", "Center" or "Gallery", which are grouped together as they are less frequent, see table {{{reftbl_t_selfid}}}).
#
Since the name is one of the first aspects that stakeholders perceive when engaging with an organization, it might shape expectations and influence forms of engagement.
#
In particular, it might be that museums that also refer to themselves as museums are seen as more favorable and worthy of visits, collaborations and support than other museums.


To ensure that inclusion of the word "museum" corresponds to the naming convention of the museum population, the names of the "Museums of the World" (MOW) database [[parencite:&deGruyter_2021_MOW]], a database containing over 55.000 museums, are analyzed.
#
In this database, {{{mow_prop_name_museum}}}% of museum names contain the term "museum" (or its equivalent in other languages), which indicates a substantial naming convention. 

prevalence of museum founders to include the term museum in the name of their institution[fn::While it would also be possible to construct inclusion in the MOW as an indicator of legitimacy, as it represents recognition of the organization as a museum by experts [[parencite:&Zuckerman_1999_illegitimacy]], preliminary investigations of the database indicated that it has been  updated only sparsely in recent years; thereby inclusion in it (or the lack therefore) does not constitute an accurate measurement of the extent of an institutions' recognition as a museum].


# Secondly, a binary predictor measures whether the museum is included in the 
# #
# While the exact criteria of the research process leading to the MOW database are not known, it is plausible that museums who correspond to an ideal-typical museum are more likely to be included.
# #
# Assuming that museums are seen similarly by the creators of the MOW database and other audiences, inclusion in the MOW database constitutes a proxy for adherence to museum standards. 


**** Reputation

Reputation is measured via inclusion of the founder in the Artnews top 200 collector ranking [[parencite:&Artnews_ranking]].
#
This ranking, established in 1990, lists each year the 200 collectors the editors of the magazine consider most relevant.
#
For each year, a museums can have one of three values: "Not included"; in which case the founder is not included in the year in question and has not been so in the past, "Included"; when the founder is included, or "Dropped", for cases where the founder was included at some point in the past but is no longer included in the current year.
#
Cases where multiple individuals are involved in the founding of a private museum are resolved by aggregating the Artnews ranking inclusion history to the founder level (i.e., if only one of two founders is dropped from the Artnews ranking but the other remains included, the founder couple as a whole is considered included).
#
The variable is lagged by one year to avoid reverse causality, i.e. to exclude the possibility that an association is observed which is present due to founders being dropped from the ranking as a consequence of the closure of their museum.



**** Competition
:PROPERTIES:
:CREATED:  [2024-04-07 zo 15:07]
:ID:       e891980a-d6c2-400a-8770-238a1c68eb09
:END:

On a national level, density of private museum is calculated as the number of private museums per million.
#
On a local level, I use the Global Human Settlement Layer [[parencite:&EC_2023_GHSL]] to estimate the number of private museums and population counts inside a radius of ten kilometers around each private museum for each year.
#
To be able to estimate both competition and demand/audience/population separately, I do not calculate densities as per capita rates, but include the local museum counts, local population in millions as well as an interaction between the two.

*** Control variables

#+latex: \bigbreak
#+latex: \noindent
A number of control variables are used: 
# 
On the level of the founder, gender constitutes a time-invariant variable; with possible values being male, female and couple.
#
Women constitute a minority of the private museums founders, thus from a typicality perspective [[parencite:&Rosch_1975_family]] museums by female founders would be expected to close more often as female founders would have a greater difficulties in securing resources third parties, presumably primarily governments and corporate sponsors.
#
However, women may also be particularly associated with philanthropic initiatives (unlike e.g. corporate activities, [[cite:&Milam_2013_artgirls]]) to such an extent that devaluation of female initiatives may not necessarily be present.

#
# Organizational transformation, such as change of authority has been to increase chances of closure both generally [[parencite:&Carroll_Khessina_2019_demography]] and in the case of private museums specifically ([[cite:&Walker_2019_collector p.234]]: "seldom do heirs share a similar passion or wish to take on the financial burden of maintaining private museum indefinitely").
# Therefore, a measure of founder death is constructed as a time-varying covariate, and is set to 1 for museum-years after the death of the founder. 
#
Centrality of the founder's vision is measured via the proxy of whether the name of the founder is included in the name of the museum.




External shocks might interrupt operations, which reduces income from tickets, as well as make other donors more hesitant to commit money in uncertain times.
#
However, museums, including private museums, might also be relatively resilient as they can adopt measures such as tightening their belt, additional fundraising, and expanding their marketing efforts [[parencite:&Geller_Salamon_2010_resilience]], which might bolster their resilience.
#
To account for two prevalent shocks in the recent decades, the Great Recession and the Covid-19 pandemic, I thus include two dummy variables for 2008/2009 and 2020/2021; respectively.




*** Analytical framework


First, I investigate the relationship between age and closing descriptively using hazard rates and the Kaplan-Meier survival function.
#
This non-parametric method estimates the hazard rate as the conditional probability of exiting at time t_i given being alive as $h(t_i) = \frac{d_i}{n_i}$, (with $n_i$ as the number of units at risk at time $t_i$ and $d_i$ as the number of exits at time $t_i$), and the survival function as the product of these conditional probabilities as $S(t) = \prod_{t_i \geq t} \left(1-h(t_i) \right)$.





# In a second step,
Secondly, we use Cox proportional hazard models which estimate the relationship between covariates and the hazard rate.
#
 



** Results

*** Summary statistics

#+INCLUDE: "../tables/t_sumstats_wcpF.tex" export latex

In total, {{{pmdb_n}}} private museums are included in the dataset which are either open or have closed[fn:: This does not include {{{pmdb_n_nlpm}}} institutions which were private museums at some point and have since been transformed into other organizational forms; these cases are discussed in the limitations.].
#
A small number of museums are excluded, in particular three museums for which the closing date could not be found, {{{pm_open_from2021}}} museums which opened in 2021 and later (as survival analyses requires positive survival times), as well as two which closed before 2000 as they fall outside the period under investigation.
#
This leaves {{{pm_n_used}}} private museums at risk, of which {{{pm_n_closed}}} have closed.
#
{{{n_pmyears}}} museum-years are observed; table {{{reftbl_t_sumstats}}} shows summary statistics for all variables.


*** Calendar Year hazard
:PROPERTIES:
:CREATED:  [2024-08-28 wo 15:14]
:ID:       3a7b6903-0a1e-44b9-98e7-f89535b6fd6e
:END:

{{{ynkplt_p_hazard_time}}}

While typically in survival analysis closing risk is seen as a function of age, previous studies have not done so, instead focusing on average yearly closing rates.
#
To ensure comparability with these, I first analyze closing rates the same, and discuss age-related closing rate below.
#
Summary yearly closing results in an average closing rate of {{{yearhaz_all}}}; i.e. on average each year {{{yearhaz_all}}} of the private museum population closes (weighing the yearly mortality rate by number of museums at risk results in an estimate of {{{yearhaz_allw}}}).
#
It is worth pointing out however that closing rates appear to vary substantially over time (figure {{{refplt_p_hazard_time}}}); with an average closing rate of {{{yearhaz_upto2010}}} from 2000 to 2010 (with only 4 closures taking place in that time period), and a rate of {{{yearhaz_from2010}}} from 2010 onwards.





While I did not find a systematic literature review or meta-analysis, a number of individual studies had investigated similar populations based on IRS data (see table \ref{tbl:litreview})[fn::IRS data is not without limitations, such as only being required from larger organizations, misreporting, and the difficulty of inferring closing from non-filing. Nevertheless, it constitutes the most fine-grained data source to investigate non-profit survival].
#
None of these focus specifically on art museums ([[textcite:&Hager_2001_vulnerability]] focuses on Art NPOs, [[textcite:&Bowen_1994_charitable]] and [[cite:&Gordon_etal_2013_insolvency]] on NPOs generally), but report survival estimates by organizational form, including museums.
#
[[textcite:&Bowen_1994_charitable]] reports average annual exit rates for all 501(c)(3) museums in the 1981-1991 time period of 1.1% (p.103)
#
# (rather than only institutions with revenues exceeding 25,000 USD).
#
[[textcite:&Gordon_etal_2013_insolvency]] observes 35 closures over the years of 2000-2003 with 5,167 "firm-years" (p.368), resulting in an annual "average insolvency rate" of 0.68% (p.377).
#
Some of this difference may be explained by higher shares of smaller organizations in [[textcite:&Bowen_1994_charitable]], where NPOs of any size are included, whereas [[textcite:&Gordon_etal_2013_insolvency]] excluded NPOs with operational revenues below 150,000 USD by, as smaller non-profits are at higher risk of closing [[parencite:&Harrison_Laincz_2008_nonprofit;&Helmig_Ingerfurth_Pinz_2013_nonprofit]].
#
Focusing directly on Art museums, rather than museum generally, [[textcite:&Hager_2001_vulnerability]] observes 42 closures over a period of 4 years (1994-1997) from a starting populaton of 448 (p.383).
#
As his way of delineating the population (having "filed an annual Form 990 tax return with the IRS for the 1990, 1991, or 1992 tax year", p.380) does not rule out that some closings took place in 1991, 1992 or 1993[fn::In particular it is unclear why 1993 is not treated as belonging to the observation period], attributing some closings to these years is likely appropriate, and presumably roughly equivalent to assuming an observation period of five (rather than four) years, which corresponds to an average yearly closing rate of $1-\sqrt[5]{406/448}$ = 1.9%[fn::So far it is hard to tell why art museums appear to have higher closing rates than museums generally.
#
According to [[textcite:&IMLS_2008_funding]], art museums have above-average reliance on earned income (46.1% compared to 43.7% on average, p.26), and [[textcite:&Bowen_1994_charitable]] argue that a higher reliance on income is associated with exit rates (p.102), but it is questionable whether such an a small difference in percent earned can explain a 1.7-2.7 times higher closing risk.
#
Similarly, while art museums do not have the largest coffers (in particular museums of natural history and science are substantially larger [[cite:&IMLS_2008_funding;&Bowen_1994_charitable]]), art museums have substantially higher incomes than the history museums (which are more frequent), historical societies and botanical gardens [[parencite:&IMLS_2008_funding]] as well as "other museums" with more specialized and/or local focuses parencite:Bowen_1994_charitable.
#
Especially the larger number of history museums, and the more restrictive inclusion by [[textcite:&Hager_2001_vulnerability]] in comparison to [[textcite:&Bowen_1994_charitable]] make the higher mortality rate for art museums than museums generally puzzling.] 





#+caption: Hazard rates in studies of museums and art NPOs
#+label: tbl:litreview
|-----------------------------------+---------------------+-------------------------|
| Study                             | Population          | Average Yearly Closings |
|-----------------------------------+---------------------+-------------------------|
| [[cite:&Hager_2001_vulnerability]]    | Art Museums         | 1.9%                    |
| [[cite:&Gordon_etal_2013_insolvency]] | Museums             | 0.7%                    |
| [[cite:&Bowen_1994_charitable]]       | Museums             | 1.1%                    |
| current study                     | Private Art Museums | {{{yearhaz_all}}} (overall)         |
|                                   |                     | {{{yearhaz_from2010}}} (2010-2021)       |
|                                   |                     | {{{yearhaz_allw}}} (weighted)        |
|-----------------------------------+---------------------+-------------------------|


Results are summarized in table \ref{tbl:litreview}.
#
Average annual closing rates fall within closing rates found in previous studies, and even the 2010-2021 time periods with higher risk is below the general estimate for art museums by [[textcite:&Hager_2001_vulnerability]].
#
There is thus overall little support to the idea that private museums are exposed to higher closing risk than museums, thus refuting Hypothesis 1.




*** Hazard rate and Age Dependence 

{{{ynkplt_p_hazard}}}

{{{ynkplt_p_surv}}}


Next to average yearly closing rates, private museum closing can also be investigated over its age (unfortunately, no comparison to previous studies can be done as age-dependent mortality estimates are not reported).
# 
Figure {{{refplt_p_hazard}}} shows the hazard rate over time, figure {{{refplt_p_surv}}} the corresponding survival probability.
#
The hazard rate increases strongly from {{{meanhaz_upto_2}}} in the first two years, to {{{meanhaz_upto_5}}} in the first 5 years, to {{{meanhaz_8to30}}} at year 8, around which it then fluctuates, leading to an average hazard of {{{meanhaz_upto_30}}} for the first 30 years. [fn::While it is possible to calculate the average hazard over longer periods (e.g. the overall average hazard rate is {{{meanhaz_upto_100}}}), for ages above 30 only few observations are available, which make these predictions rather uncertain.]


# FIXME endowment definition
The increase in the first years is likely due to what has been called "initial resource endowments" in organizational research [[cite:&Carroll_Khessina_2019_demography;&Hannan_1998_mortality]] (not to be confused with the practice of a particular endowment for e.g. a museum REF, i.e. a stock of money, often invested in stocks, whose capital gains are used for operations).
# 
As the establishment of a museum requires considerable resources, their founders appear to allocate enough resources to keep the risk of closure small in the first years after opening.
#
Given that founders are likely aware that their endeavor is unlikely to generate a profit, they are not vulnerable to the liability of newness [[parencite:&Stinchcombe_1965_structure]].


Such analysis can be used to estimate the average life expectancy of a private museum.
#
While only a fraction of all opened museums has closed ({{{pm_n_closed}}} out of {{{pm_n_used}}}), under the assumption of average closing risk of {{{meanhaz_upto_8}}} in the first 8 years and {{{meanhaz_8to30}}} onwards, median life expectancy can be estimated as approximately {{{median_life_expectancy}}} years.
#
On first sight such findings seems to differ from a previous quantitative analysis of the database, which argued that "the median number of years that private museums were open before they closed is 10 years" [[parencite:&Velthuis_Gera_2024_fragility p.5]], as previously only closed museums were considered.
#
Focusing on the entire population of private museums instead, this analysis provides additional insights into the expected longevity of private art museums.






# #+latex: \noindent
# TODO:
# - get confidence interval for hazard rate
# - see how age can be integrated into survival models (linear term doesn't work)
# - expand comparison to other studies



*** Regression Results

#+INCLUDE: "../tables/t_reg_coxph_wcpF.tex" export latex

#
To investigate which covariates are associated with increased risk of closing, table {{{reftbl_t_reg_coxph}}} shows the results of Cox proportional hazard regression model.
#
Coefficients are interpeted as log hazard ratios, i.e. as multipliers of the baseline hazard rate.

**** Control Variables

#
Neither gender nor external shocks (the Great Recession and the Covid-19 Pandemic) are associated with higher closing rates.

inclusion of founder name is significantly associated with mortality rates.
#
# (TODO: add reference, very speculative!!)
While generally organizations whose name include the name of their founder might be more centered around the founder, and hence display higher inertia, making them less able to adapt to changing environments, these results indicate that it does not seem to be case for private museums.



**** Founder dependence

***** death :ignhead:
#+INCLUDE: "../tables/t_reg_coxph_deathcfg_wcpF.tex" export latex

{{{ynkplt_p_surv_death}}}

The death of the founder is not associated with a significant difference in private museum closure, i.e. museums are not significantly more likely to close after their founder has died.
#
While the point estimate is positive, with {{{coef_death}}}, corresponding to a {{{coef_death_perc}}}% increase in mortality for museums whose founders have died compared to those who have not, the low risk overall means that despite the cumulative character even decade-long survival times do not differ substantially (figure {{{refplt_p_surv_death}}}).


# 
It is in principle possible to construct an alternative measure of founder death by partioning the time after the death in a short-term and long-term period; the short-term period might then capture the disruption by the founder, whereas the long-term period would only be reached by museums who have successfully acquired alternative funding models and are hence relatively viable.
#
However, the choice of choosing a cut-off point between the short- and long-term periods is relatively arbitrary.


Table \ref{tbl:t_reg_coxph_deathcfg} shows coefficients of both periods with different cut-off points.
#
While the coefficient in the short-term period is consistently higher than both the overall death coefficient and the long-term period coefficients, so far the evidence is inconclusive as only few cases are statistically significant[fn:: P-values are also not adjusted for multiple tests].
#
Furthermore, such a shock passes quickly relative to the median life-time of museums of {{{median_life_expectancy}}} years, thus "giving" the founder death little time to lead to many museum closures. 
# 



Considering the numbers underlying the death effect estimates illustrates the uncertainty of the determning the effect of the death of the founder on aclosing: 
# 
While {{{n_founder_dead}}} private museums have seen the death of their founders, only {{{n_pm_close_after_recent_death}}} of these have closed in the following 5 years; given such low numbers it cannot be ruled out that the statistical significance in a few configurations of founder death time results from random fluctuations rather than an underlying pattern.
#


***** artnews ranking :ignhead:


The reputation of the founder is not statistically related to closure. 
#
Museums whose founders are not included in the ARTnews collector ranking (reference category) are the least likely to close, followed by museums whose founders are included ({{{coef_an_inclusionincluded_perc}}}% elevated closing risk) and by founders who were included at some point but are no longer included ({{{coef_an_inclusiondropped_perc}}}% elevated closing risk), however none of the differences are statistically significant.
#
It is also worth to point out that the order of the categories does not fully correspond to the expected order, according to which museums whose collectors are not included would be more likely to close than collectors who are.
#
However, as all differences are not statistically significant, there is no strong evidence that this reflects unexpected status mechanisms rather than randomness.
#


it nevertheless provides some evidence that status matters; as in particular the loss of status appears to be substantially associated with museum closure.

***** founder name :ignhead:

Museums whose name contain the name of the founder face a non-significantly {{{coef_muem_fndr_name_perc}}}% elevated risk of closure, which indicates that there is little evidence that founders face greater difficulties to secure a long-term future for their museums by choosing to emphasize their personal contribution.
#
It might have been expected that such central positioning of the founder might limit longevity by disincentivizing contributions by other parties.
#
However, as the direct mechanism of declining contributions cannot be observed, its absence cannot be assumed either.
#
It might be the case that other parties do indeed feel less inclined to contribute but that these gaps are filled by a stronger commitment of the founder, who having committed her name to the enterprise, wants to keep her museum open event at great costs.

***** founder conclusion



Taken together, the inability to explain private museum closing with the death of founder, her exclusion from a prestitious ranking and the presence of her name in the museum's name question the hypothesized central role of the founder.
#
In other words, so far little evidence points to founders constituting a substantial source of involuntary closing risk.
#




**** Competition
{{{ynkplt_p_pred_popprxcnt}}}



Country-level measures of the private museum population show no association with mortality.
#
However, at the local level the number of private museum and population density predicts survival chances as the main effects of population and number of private museums as well as its interaction is significant.
#
Figure {{{refplt_p_pred_popprxcnt}}} shows average predicted survival prospects for the value range of regional PM density and population numbers.
#
Museums located in less densely populated areas have (at low PM densities) lower hazard rates than museums in more densely populated areas. 
#
However, these museums in less densely populated regions see an increase in the risk of closing for each additional private museum present within 10 kilometers, whereas the risk of closing decreases with each additional private museum in the local environment for museums in more densely-populated areas.
#
The increase in mortality in less densely populated regions when the number of nearby private museums increases could indicate competition:
#
As the potential pool of resources is somewhat limited, each new museum trying to claim its share limits the average resources available to other institutions, leading to higher mortality.
#
In the more densely populated regions with larger resources the marginal impact of an additional private museum appears declines and eventually turns negative (i.e., enhances survival chances).
#


The absence of private museums in otherwise densely populated areas might also reflect the absence of a wider cultural infrastructure; thus even a large potential audience might not be able to sustain private museums in the absence of other foundations, public or corporate museums.

#


#
# However, they have at low PM density lower closing rates than museum in more populated areas.

# #
# While the density-dependence paradigm predicts a negative effect of numbers of organizations on closing rate at low numbers (due to legitimacy, i.e. growing familiarity with a new organizational form), and a positive effect at high numbers (due to competition over resources), neither relationship is significant in the case of private museums.

**** Identity Variables

Museums which include the term "collections" in their name are the least likely to close ({{{coef_slfidfcncollection_exp}}} times the rate of museums with the name "museum", while those with the term foundation experience {{{coef_slfidfcnfoundation_perc}}}% elevated closure rates (but not significantly higher).
#
However, institutions which include neither of these are the most likely to close, and have mortality rates almost three times as high ({{{coef_slfidfcnother_perc}}}%) than institutions including the term "museum".
# 
The usage of unconventional names might reflect adherence to museum standards which makes museums more understandable and familiar to third parties (e.g. audiences, other museums, companies or the government) and thereby facilitates interactions which are beneficial for long-term survival (e.g. attracting visitors, cooperations, sponsorships or subsidies).
# 
However, as founders can choose the name of their museum arbitrarily, they might choose a name without reference to organizational forms associated with perpetuity precisely because their intention is not an institution enduring in perpetuity but rather a more temporally bounded project.







** Discussion


Investigating the survival prospects of private museum furthermore illucidates the long-term development of the organizational form as a whole, as it provides insights into factors related to variation of sustainability and thereby into trends in composition. 

*** gender :ignhead:
#
# While the composition of private museums is not only influenced by closures, but also by foundings,
# 
Given the non-significant gender difference, it can be expected that (unless given a strong increase in founding by women) the population of private museums will continue to remain a man-dominated affair.
# [fn::The point estimates, which are higher for women and couples, albeit not significantly so, even point towards a slight expansion of the proportion of museums established by men.] # add this if gender - female is substantially positive
#
This finding also provides no evidence that female founders face gender-specific challenges that decrease the survival prospects of their private museums. 


*** audience/competition :ignhead:



# FIXME: rewrite with focus on audience/competition
# The effects of location might be seen
# #
# On the one hand, museum location is chosen by the founder at the time of founding (or rather, several years in advance).
# #
# This gives founders substantial choice in the size and composition of the potential audience who will be able to easily assess the museum.
# #
# On the other hand, collectors are less able to influence what plans other collectors might have.
# #
# What may have been at one point been identified as a promising location without substantial competition may turn out to be a much less fertile ground as soon as other collectors start eyeing the same region for their own private museum projects.
# # 
# In particular private museum in rural locations with low population densities seem to be at risk when other museums open in the neighborhood. 
# #
# This is not to say that private museums cannot endure in areas with low population densities. 
# #
# In fact, at low numbers of private museums in the neighborhood their survival prospects are better than those located in larger cities.
# #
# These larger cities with low private museum counts are possibly also characterized by lower numbers of other cultural institutions as well as an audience less interested in postmaterial art consumption.


{{{ynkplt_p_pred_heatmap}}}



*** facilities/size :ignhead:
# FIXME: rewrite with 


The lack of a relation between temporary exhibitions and survival prospect is somewhat unexpected.
#
It was expected that as temporary exhibitions constitute one of the main tasks of a museums operations, organizing them would benefit a museum financially (via visitor fees) and symbolically (via prestige of other art field actors, which might be developed into further contacts), leading to higher survival chances[fn::Furthermore, the ability to organization exhibitions likely reflects museum resources, which should also enhance survival.]
# not sure this follows
However, organizing exhibitions does not seem to bestow benefits for the museums which organize them, nor do organizations seem to be organized only by established/sustainable/secure organizations.
#
One possibility for this discrepancy could be that exhibitions are expensive, and whatever benefits gained from them are offset by the associated costs.
#
One might see in this association again the importance of the founder:
#
Founders who are committed to their museums will keep them alive, regardless of whether or not they plan to organize temporary exhibitions.







*** founder
:PROPERTIES:
:CREATED:  [2024-05-29 wo 12:08]
:ID:       676af2e2-9b94-489e-88a8-6a87397c864a
:END:



It has been widely argued that the death of the founder would lead to his or her private museum to close, while this analysis has not found conclusive evidence for this relationship.
#
It is important to keep in mind that the lack of observing a clear relationship between the death of the founder and museum closure does not imply that no relationship exists.
#
It is possible that previous scholars who argued for such an association have correctly identified the dependency relationships in private museums, which will become visible once more founder deaths have occurred.
#
At the same time, it is possible that private museums are indeed generally less dependent on the mood of a single person (or couple), and have in fact become institutionalized to an extent that heirs of founders feel as motivated to continue the original founders' efforts as these founders themselves.



# FIXME: rewrite from observation level to process level
# The role of the founder is two sided.
# #
# Death and exclusion from a prestigious ranking are not associated with a higher risk of closure, which indicates that private museums have attained a substantial degree of institutionalization.
# #
# On the other hand, self-identifying as an institution which is not a museum, foundation or collection possibly reflects a kind of founder attitudes which substantially influences survival chances.
# #
# Founders who are less interested in establish institutions might be more inclined to choose a name which less reflects this ambition. 
# #
# One way of conceptualizing this distinction might then be that whereas involuntary, externally imposed events are less able to close museums of otherwise motivated founders, some founders might from the very beginning voluntarily decide to not establish a museum that is intended for perpetuity.


# However, this group is somewhat small.
# #
# Of the XXX museums included in the database, XXX do not carry the term museum, foundation or collection.
# #
# Thus given this low share, and the corresponding  higher closing rate, a possible future for the private museum population might be increased institutionalization and consolidation of relatively robust organizations.
# #


** Conclusion
# The conducted analysis shows a substantial association between private museum identity and closures.
# #
# While alternative explanations cannot be completely ruled out, a clearly understandable identity and a favorable founder reputation emerge as important predictors of the chance of a private museum to close.
# #
# Future research can expand on these findings by in more detail investigating the resource perspective of private museums, the intransparency of which has so far aggravated insights about budgetary aspects, in particular how these financial and material characteristics are moderated or mediated by processes of organizational identity.

Private museum have been characterized as fragile institutions due to their reliance on a single founder.
#
However, my analysis finds neither a higher substantially higher mortality rates for private museums compared to (art) museums generally, nor a conclusive relationship between museum closure and a number of founder characteristics, such as founder gender, death, exclusion from the Artnews collector ranking or inclusion of founder name in the museum name.
# 
While Self-identification and audience/competition are significantly associated with higher mortality, and possibly reflect or influence founder motivations, they are also subject to alternative mechanisms, namely devaluation by third parties and competition, respectively (self-identification furthermore concerns a relatively small group of institutions).
#
Furthermore, even if they reflect founder motivations, these are likely cases of voluntary closure; there is thus no large evidence that private museums are at a higher risk of unvoluntary closure than more diversified museums as a consequence of their reliance on a single founder. 



A possible explanation of the characterization of private museums as fragile might be due to the focus on case studies, which disregards the much larger population who don't experience closing.
#
Due to the "private museum boom", some museums will experience closing over a period of around two decades even if the underlying closing probability is low.





It cannot be stated whether private museums experience higher mortality rates than publicly funded museums (for which European countries would be the most natural comparison).
#
While public museums have been characterized to some extent as very stable due to government picking up deficits [[parencite:&Meier_Frey_2003_faces;&Bechtler_Imhof_2018_future]], [[textcite:&Walker_2019_collector]] argues that due to declining cultural spending even public museums might face hard times.
#
While national public flagship institutions will likely remain sufficiently funded to survive, this might not be the case for the vast majority of smaller museums in less touristic regions who rely on limited municipal funding, as textcite:&StylianouLambert_etal_2014_museums demonstrates for a number of smaller publicly funded ethnography museums in Cyprus.
#
Without access to museum register comparable to the IRS/NCCS datasets, such questions regarding the relation between type of ownership and survival remain speculative.


#+Latex: \begin{sloppypar}
#+Latex: \printbibliography
#+Latex: \end{sloppypar}



*** Limitations

**** no transformation :ignhead:
For this study, I only investigated the occurence of closure events.
#
However, private museums can stop existing as private museums not just by closing down, but also by being transformed into other organizational forms.
#
One way in which this can happen is when other parties, such as local governments other philanthropists, foundations, or corporations become substantially involved in the ownership, governance and/or funding of the museum.
#
Sometimes this involves changes in the composition of the board of directors (or equivalent), with new parties gaining seats and hence influence in decision-making, thereby diminishing the private character of the museum to an extent that it no longer fits the working definition.
#
Museums which experienced this trajectory have been excluded from the analysis as explorative investigation showed that it was not possible to generally determine the date of such transitions[fn:: Consequently they are excluded from the analysis alltogether, and thus also not contributing to the the hazard rate for closing, despite being entities at risk for closing. However, as their numbers are limited to {{{pmdb_n_nlpm}}} entries in the database, the bias this introduces into closing risks is likely not substantial.]
#
The main issues that made the determination of the date impossible was the intransparency of these organizations (~event in the past, no track of organizational history~), as well as the gradual process.
# 
As the presence of non-founder members does not categorically exclude a museum from being categorized as private museum as long as third-party influence is limited, this influence can grow until the museum bears little resemblance to its former self.
#
The possibility of other outcomes than surival and closures has been investigated for NPOs more generally
[[parencite:&Searing_2020_zombies;&HernandezOrtiz_2022_discontinuity;&Helmig_Ingerfurth_Pinz_2013_nonprofit]], and for private museums specifically: 
#
[[textcite:&Walker_2019_collector]] argues that in the case of Germany, private museum founders turn to the state to ensure the survival of their projects in the form of public-private partnerships.
#
Investigating this process of transformation into a different organizational form thus provides fruitful avenue for further research. 

**** closing reasons not as rich as previous studies
:PROPERTIES:
:CREATED:  [2024-08-23 vr 10:34]
:ID:       45725b05-928c-4633-a690-9095ef61b849
:END:

The extent to which closing factors are investigated does not reach the level of detail by [[cite:&Velthuis_Gera_2024_fragility]], who investigate each closing separately.
#
On the other hand, the inclusion of the museums who do not close results in a more more complete comparatison. 
#
A research approach that would combine the strengths of both approaches could for example consist of leveraging additional data sources, such as financial histories of founder companies to investigate financial issues or search engine results, media reports or social media posts to assess interest from the public. 

# maybe move to future research

founder age bracket


**** environment :ignhead:
environment can be measured more
- geocoding of other institutiosn
- tax incentives
- government spending
- government: political changes, censorship, persecution  
-> this might futher specify the niches in which PMs can endure

**** facilities/size :ignhead:
:PROPERTIES:
:CREATED:  [2024-08-23 vr 10:32]
:ID:       4b290835-a2d9-4d50-915f-1eb90d8a7cf5
:END:

remain intransparent



Museum characteristics might influence closing to a larger extent than has been considered here.
#
For example, museum size, facilities, as well as marketing and outreach activities might be related to long-term survival prospect.
#
For example, museums with more XXX might be more expensive to run, but on the other hand attract higher visitor numbers, cooperations and sponsorships. ~liability of smallness~
#
Furthermore, having XXX might reflect founder commitment/resources.
# 
While the original data collection included the measurement of various museum characteristics, such as floor and collection size, facilities, and cooperations, it became clear in the process that desk research was unsuitable to construct reliabile indicators from these findings due to difficulty in assessing them in many cases.
#
Especially for closed museums data collection proved difficult, as in many cases websites had been shut down, and while in many cases snapshots of the main website were available in the Internet archive, ~subdomains~ were archived much less frequently, and sometimes inaccessible despite being archived due to changes in webtechnology (such as flash).
#
While it would be possible to
absence of evidence as evidence of absence

*supplementary material*






covid effect may take longer to be effective

 
*** future research
The US register data on NPO tax filings constitutes a promising source for data for museum research (while this data source has seen frequent usage in non-profit management, it remains underexploited in the field of museum research). 
#
While the United States private museum population with XX museums and YY closings might not be sufficient to test whether private museums have a a higher closing risks than other museums, it still hosts a large population of museums.
#
Thus this data can be used to establish average mortality estimates for museums generally as well as different types of museums, which can be compared to those observed for private museums globally. 
#
Its furthermore a rich source of financial data

egmus doesn't have that



