#+latex_class: article_egos
# erases make title
# #+BIND: org-export-latex-title-command ""

# fucks all the maketitlestuff just to be sure
#+OPTIONS: num:nil
#+OPTIONS: toc:nil
#+OPTIONS: h:5



#+BEGIN_SRC R :session calc :exports none :results values drawer :dir /home/johannes/
library(jtls)
dt_nbrs <- fread("/home/johannes/Dropbox/phd/papers/closing/misc/nbrs.csv")
wd_nbrs(dt_nbrs)
## quit(save="no")
#+end_src

#+RESULTS:
:results:
# descs
#+MACRO: pmdb_n_nlpm 25
#+MACRO: mow_prop_name_museum 71


# meanhaz
#+MACRO: meanhaz_upto_2 0.10%
#+MACRO: meanhaz_upto_4 0.49%
#+MACRO: meanhaz_upto_5 0.69%
#+MACRO: meanhaz_upto_10 0.89%
#+MACRO: meanhaz_upto_20 1.09%
#+MACRO: meanhaz_upto_30 1.16%
#+MACRO: meanhaz_upto_40 0.96%
#+MACRO: meanhaz_upto_100 0.90%


# pltcfgs
#+MACRO: ynkplt_p_vrblcvrg_ugrpd (eval (concat "#+label: fig:p_vrblcvrg_ugrpd\n" "#+caption: PMDB variable coverage by museum status\n" "#+attr_latex: :width 19cm\n" "[[file:../figures/p_vrblcvrg_ugrpd.pdf]]"))
#+MACRO: ynkplt_p_vrblcvrg (eval (concat "#+label: fig:p_vrblcvrg\n" "#+caption: PMDB variable coverage by museum status and variable group\n" "#+attr_latex: :width 19cm\n" "[[file:../figures/p_vrblcvrg.pdf]]"))
#+MACRO: ynkplt_p_vrblcvrg_ratio (eval (concat "#+label: fig:p_vrblcvrg_ratio\n" "#+caption: PMDB variable coverage (abs/rel prop) by museum status and variable group\n" "#+attr_latex: :width 18cm\n" "[[file:../figures/p_vrblcvrg_ratio.pdf]]"))
#+MACRO: ynkplt_p_surv (eval (concat "#+label: fig:p_surv\n" "#+caption: Private Museum Survival probability\n" "#+attr_latex: :width 14cm\n" "[[file:../figures/p_surv.pdf]]"))
#+MACRO: ynkplt_p_hazard (eval (concat "#+label: fig:p_hazard\n" "#+caption: Private Museum hazard function\n" "#+attr_latex: :width 16cm\n" "[[file:../figures/p_hazard.pdf]]"))
#+MACRO: ynkplt_p_hazard_time (eval (concat "#+label: fig:p_hazard_time\n" "#+caption: Private Museum hazard function by year\n" "#+attr_latex: :width 16cm\n" "[[file:../figures/p_hazard_time.pdf]]"))
#+MACRO: ynkplt_p_agedens (eval (concat "#+label: fig:p_agedens\n" "#+caption: Age distribution of private museums\n" "#+attr_latex: :width 17cm\n" "[[file:../figures/p_agedens.pdf]]"))
#+MACRO: ynkplt_p_yeardens (eval (concat "#+label: fig:p_yeardens\n" "#+caption: Private Museum-year Distribution\n" "#+attr_latex: :width 19cm\n" "[[file:../figures/p_yeardens.pdf]]"))
#+MACRO: ynkplt_p_coxphdiag_more (eval (concat "#+label: fig:p_coxphdiag_more\n" "#+caption: Model Diagnostics\n" "#+attr_latex: :width 19cm\n" "[[file:../figures/p_coxphdiag_more.pdf]]"))
#+MACRO: ynkplt_p_pred_popprxcnt (eval (concat "#+label: fig:p_pred_popprxcnt\n" "#+caption: Predicted Avg. Hazard Rate on Regional PM Density and Population\n" "#+attr_latex: :width 18cm\n" "[[file:../figures/p_pred_popprxcnt.pdf]]"))
#+MACRO: ynkplt_p_pred_proxcntpop (eval (concat "#+label: fig:p_pred_proxcntpop\n" "#+caption: Predicted Avg. Hazard Rate on Regional PM Density and Population\n" "#+attr_latex: :width 18cm\n" "[[file:../figures/p_pred_proxcntpop.pdf]]"))
#+MACRO: ynkplt_p_condmef (eval (concat "#+label: fig:p_condmef\n" "#+caption: Conditional effects of Regional PM Density and Population\n" "#+attr_latex: :width 18cm\n" "[[file:../figures/p_condmef.pdf]]"))
#+MACRO: ynkplt_p_pred_heatmap (eval (concat "#+label: fig:p_pred_heatmap\n" "#+caption: Predicted Avg. Hazard Rate on Regional PM Density and Population\n" "#+attr_latex: :width 18cm\n" "[[file:../figures/p_pred_heatmap.pdf]]"))
#+MACRO: ynkplt_p_heatmap_info (eval (concat "#+label: fig:p_heatmap_info\n" "#+caption: heatmap info plots\n" "#+attr_latex: :width 35cm\n" "[[file:../figures/p_heatmap_info.pdf]]"))
#+MACRO: ynkplt_p_pred_heatmap_wocryside (eval (concat "#+label: fig:p_pred_heatmap_wocryside\n" "#+caption: Predicted Avg. Hazard Rate from Regional PM Density and Population (without proxcnt < 2 & popm_circle10 <2)\n" "#+attr_latex: :width 18cm\n" "[[file:../figures/p_pred_heatmap_wocryside.pdf]]"))
#+MACRO: ynkplt_p_lngtdvelp (eval (concat "#+label: fig:p_lngtdvelp\n" "#+caption: Composition of private museum population\n" "#+attr_latex: :width 18cm\n" "[[file:../figures/p_lngtdvelp.pdf]]"))


# figlbls
#+MACRO: refplt_p_vrblcvrg_ugrpd \ref{fig:p_vrblcvrg_ugrpd}
#+MACRO: refplt_p_vrblcvrg \ref{fig:p_vrblcvrg}
#+MACRO: refplt_p_vrblcvrg_ratio \ref{fig:p_vrblcvrg_ratio}
#+MACRO: refplt_p_surv \ref{fig:p_surv}
#+MACRO: refplt_p_hazard \ref{fig:p_hazard}
#+MACRO: refplt_p_hazard_time \ref{fig:p_hazard_time}
#+MACRO: refplt_p_agedens \ref{fig:p_agedens}
#+MACRO: refplt_p_yeardens \ref{fig:p_yeardens}
#+MACRO: refplt_p_coxphdiag_more \ref{fig:p_coxphdiag_more}
#+MACRO: refplt_p_pred_popprxcnt \ref{fig:p_pred_popprxcnt}
#+MACRO: refplt_p_pred_proxcntpop \ref{fig:p_pred_proxcntpop}
#+MACRO: refplt_p_condmef \ref{fig:p_condmef}
#+MACRO: refplt_p_pred_heatmap \ref{fig:p_pred_heatmap}
#+MACRO: refplt_p_heatmap_info \ref{fig:p_heatmap_info}
#+MACRO: refplt_p_pred_heatmap_wocryside \ref{fig:p_pred_heatmap_wocryside}
#+MACRO: refplt_p_lngtdvelp \ref{fig:p_lngtdvelp}


# reftbl
#+MACRO: reftbl_t_coxzph \ref{tbl:t_coxzph}
#+MACRO: reftbl_t_reg_coxph \ref{tbl:t_reg_coxph}
#+MACRO: reftbl_t_sumstats \ref{tbl:t_sumstats}
#+MACRO: reftbl_t_selfid \ref{tbl:t_selfid}
#+MACRO: reftbl_t_reg_coxph_density \ref{tbl:t_reg_coxph_density}
#+MACRO: reftbl_t_reg_coxph_timeslice \ref{tbl:t_reg_coxph_timeslice}
#+MACRO: reftbl_t_reg_coxph_timecfg \ref{tbl:t_reg_coxph_timecfg}
:end:


* It's so over
# Short-lived legacies: The closure of private art museums
# Non-diversified but stable? The paradox of private museum closing rates
# Johannes Aengenheyster

# #+latex: \noindent
# Phd student at University of Amsterdam

# #+latex: \noindent
# j.aengenheyster@uva.nl


** Introduction

In recent years, private collector-run museums have seen an unprecedented proliferation, with hundreds of organizations founded since the beginning of the millenium [[parencite:&Velthuis_etal_2023_boom;&LarrysList_2015_report]].
#
These museums, run by individual collectors, constitute an addition to established organizational forms of art provision such as museums operated and financed by the state, foundations or associations.
#
While the emergence of this organizational form has attracted attention (cf. [[cite:&Kolbe_etal_2022_privatemuseum]] for a literature review), the process of closure has received considerably less attention.
#
In this paper, I address this gap by investigating the closure event of members of this new organizational form.
#
Analysis which factors are associated with museum closures provides insight not only into the event of closing, but also into the ongoing processes of a private museums, such as dependency relationships.
#
Furthermore, analyzing which museums survive allows to make informed speculations on the future of this recently emerged organizational form.


# too variable-based
# A number of findings emerge from this.
# #
# Museums that close are characterized by a name that does not include the term museum, foundation, or collection; a museums chance to close is also higher if it is located in an area with low population density and meany other museums.
# #
# On the flipside, a number of variables show no association with closing:
# #
# Whether a founder dies or is excluded from a prestigious ranking does not significantly influence a museums survival prospects, nor does the founders gender or whether the founder's name is included in the museum name.
# #
# The death of the founder, their gender, whether


# A number of findings highlight the role of identity in the process of private museum closure. 
# # 
# First, I find that museums which are recognized by an international museum database are less likely to close than those which are not.
# #
# Secondly, the results furthermore indicate that museums with more ambiguous names are more likely to close.
# #
# Both these findings possibly indicate that adherence to museum standards enhances legitimacy, which in turn improves survival prospects.
# #
# Finally, founder reputation, in particular its loss, is found to be substantial as museums whose founders are dropped from a collector ranking are more likely to close than museums whose founders both are and are not included.

# #+latex: \bigbreak
# #+latex: \noindent
# *keywords*: museum, closure, identity




*** Contributions :noexport:
- Intransparent founder motivations

Despite their occasionally spectacular/sensationalist press coverage, these institutions and the motivations of their founders have remained remarkably intransparent.
#
Financed in large parts by their founders' private wealth, few reporting requirements exists; and while some founders highlight their charitable and distintersted intentions in media coverage, such statements intended for a public audience might not necessarily reflect underlying founder motivations accurately.

This study (attempts to) elucidate the hard-to-observe collector motivations by studying one of the most decisive actions that their founder can take: the decision to close the museum.
#
Besides investigating the longevity of members of this new organizational form, this study gives insights into the motivations and decision making of founders.
# 
In other words, what can the factors leading to the closure of private museums tell us about the internal processes and dependence relationships of these institutions, as well as about the motivations of their founders?


- comparison to other forms (more descriptively)
- NPM angle:
  - environment
  - quantitative
  - legitimation

- voluntary vs non-voluntary closing

# interrelated question of sustainability/longevity and collector decision making

# Thinking about private museums can take place along several discourses:
# - celebratory, disinterested, giving back to community 
# - critical: self-promotional, focus on inequality/legitimacy/status

  


** Private museums definition

#+latex: \bigbreak
#+latex: \noindent
Private museums:
- founded by collector -> needs to have amassed substantial art collection
- building of its own, limited public/corporate funding, has to be visitable -> requires substantial resources




** Private museums dependencies

*** chronic lack of money of NPOs :ignhead:
:PROPERTIES:
:CREATED:  [2024-08-23 vr 12:03]
:ID:       746567b9-2f82-4a7e-afa9-726c2646812b
:END:
Private museums have been argued to be highly dependent on their founder for their continuing existence, as museums generally cannot cover expenses via revenues from ticket prices, museum shops and cafes.
#
The [[textcite:&IMLS_2008_funding]] found that for non-profit American art museums, less than half (48.1%) the revenues come from earned income, leaving substantial gaps in the budgets that are filled by a mix of private donations (23.0%), investment (18.5%) and government support (10.4%) (p.27).
#
Outside of the United States, the reliance on revenue streams beyond operations is even larger:
#
German museums have had on average only 27% of their expenses covered by operations [[parencite:&Martin_1993_museen p.233]], and even the more market-oriented NPOs in the cultural sector draw around 50% of their funding from public support [[parencite:&Zimmer_Priller_2007_gemeinnuetzig p.82]].


Given that operating at "the margin of financial sustainability" is the "ordinary condition" for cultural NPOs, [[cite:&Licci_BaraldiBonini_2024_sustainability p.2]], it is not surprising that costs have been listed as a primary reason for private museum closure:
# 
[[textcite:&Adam_2021_rise]] argues that "most of the cases of defunct private museums come back to the issue of cost" (p.79); a sentiment shared by [[textcite:&Walker_2019_collector]] who notes that "private institutions struggle to contain escalating costs that are associated with running a museum" (p.234).
#
In other studies, "insufficient funding, high maintenance costs and lack of strong government support" [[parencite:&Zennaro_2017_shanghai p.7]]. or a "shortage of fundings and interruptions in cash [[parencite:&Song_2008_private p.45]]  were central reasons that forced private museums to close.
#
In a systematic review of closing reasons given in newspapers, magazines, social media accounts and personal exchange, [[textcite:&Velthuis_Gera_2024_fragility]] find financial issues as the most commonly mentioned reasons for private museum closing.
#
Scholars have traced the closure of private museums to numerous types of declining financial situations, such as bankruptcies [[parencite:&Velthuis_Gera_2024_fragility;&Liu_2019_identities;&DeNigris_2018_museums]], costly legal battles [[parencite:&Velthuis_Gera_2024_fragility]], stock devaluations [[parencite:&Walker_2019_collector]], failing auction sales [[parencite:&Bechtler_Imhof_2018_future]] or lack of government support [[parencite:&Zennaro_2017_shanghai;&Velthuis_Gera_2024_fragility]].

*** diversification
**** founder reliance -> diversification :ignhead:

#
A central reason for financial vulnerability has been argued to be the crucial reliance on the single founder, who, as the iniators of their private museums, likely have contribute a large part of their institution's non-operating income [[parencite:&Frey_Meier_2002_beyeler]]:
# 
[[textcite:&Adam_2021_rise]] argues that "ultimately, many of these failures demonstrate the fragility of spaces that rely on a single founder, whose motivations and financial stability may change, or who may not have realised the difficulties inherent in establishing their own art space" (p.82).
# 
[[textcite:&Velthuis_Gera_2024_fragility]] similarly argue that "because of their funding models and reliance on a sole founder, [private museums] are inherently fragile organizations" (p.1).
#
[[textcite:&Bechtler_Imhof_2018_future]] also characterize "the dependency on single individuals only" as one of main reasons that "make these private museums fragile" (p.53).
#
[[cite:&StylianouLambert_etal_2014_museums]] also characterizes many private institutions as "small individual museums that depend too much on their creators to guarantee their sustainability" (p.582).
#
Beyond a direct financial component, private museums have been also
characterized as fragile since they can only rely on their founder for "taste", "vision and drive" [[parencite:&Adam_2021_rise p.77]], "passion" [[parencite:&Walker_2019_collector p.234]] or "skills and knowledge" [[parencite:&StylianouLambert_etal_2014_museums p.580]].
#
The link between diversification and mortality, i.e. higher survival chances for more diversified organizations, has been found for non-profit organizations more generally parencite:&Fernandez_2007_dissolution;&Bielefeld_1994_survival;&Hager_2001_vulnerability;&Lu_Shon_Zhang_2019_dissolution[fn::An larger literature exists shows a link between diversification and measures of financial health and sustainability besides survival [[parencite:&Licci_BaraldiBonini_2024_sustainability]]]; it is thus plausible to apply to museums as well.

**** death :ignhead:

Lack of diversification is then argued to pose a problem in particular in the case of the founder's death:
#
textcite:&Walker_2019_collector argues that "the death of the original founder and creator can [...] place the future of private museums and collections in jeopardy" as "seldom do heirs share a similar passion or wish to take on the financial burden of maintaining private museums indefinitely" (p.234). 
#
[[textcite:&Bechtler_Imhof_2018_future]] argue that in order to ensure museum longevity, "flexible, easily adapted designs for private museums" are necessary "to reduce the financial burden on their heirs" (p.188).
# can't find it online by koolhaas
# [[cite:&Koolhaas_2008_ideology]] is more about using public museums as storage
# 
[[textcite:&Adam_2021_rise]] argues that succession introduces strains in financial aspects ("Collectors’ successors may not look kindly on what may well be a money pit when [...] they will have to pick up the bills", p.77), which also concerns an aesthetic dimension ("the nature of contemporary art is to be fresh and new, but what is ‘fresh and new’ for the founder might seem ‘old hat’ to their heirs", p.76).
#
[[textcite:&Velthuis_Gera_2024_fragility]] similarly argue that "the founder’s death will almost inevitably have a direct impact on the financial health of the museum" (p.10).
# this is not about closing, just health
#
[[cite:&StylianouLambert_etal_2014_museums]], after discussing a case of a private museum whose owner "does not believe that anyone else could love the museum as much as she does", argues that this "generates questions regarding the cultural sustainability of small private museums in cases where their initiators are not able to care for them any longer" (p.580).

**** comparison lacking :ignhead:
While private museums are thus generally characterized as fragile, it is not always clear in relation to whom.
# FIXME
#
Among the most explicit is [[textcite:&Walker_2019_collector]], who characterizes public institutions as relatively stable (which constitutes the reason why private collectors aim to form cooperations with them); [[textcite:&Bechtler_Imhof_2018_future]] implicitly also highlight the longevity of state-run institutions.
#
However, no systematic data is used to estimate public museum longevity, and while some
remarks are made that public spending cuts might result in problems for public museum operations (p.XX), the overall characterization of them remains as immortal [[parencite:&Frey_Meier_2002_beyeler]].
#
Responsible for the characterization of private museums as fragile might also be implicit reliance on the ICOM definition [[parencite:&ICOM_2024_definition]] of museums as "permanent institutions", according to which every closing is indicative of fragility.
#
So far a third comparison has been absent, namely that to other non-profit museums which are not initiated and run by a single collector, but by a wider group of founders or foundations.
#
As these share with private museums a common organizational form of the non-profit organization or foundation  and a similarly harsh environment, yet and differ primarily in regards to their diversification, i.e. their reliance on a single founder as central authority and income stream, they provide a effective way of investigating the effect of diversification on museum survival. 


*** environment :ignhead:

While the low diversification, i.e. the centrality of the founder for museum finances, has been argued to constitute the key feature of private museum vulnerability, it is also important to consider the other ways in which private museums, as (non-profit) organizations, are entangled with their environments.
#
Its ability to attract audiences, which may involve competition with other museums, secure cooperations with other museums, acquire sponsorships from cooperations and fundings from governments and other foundations are likely factors that contribute to its viability and hence longevity.
# 
While some of these aspects can be influenced by the founder (in particular the available audience, via being able to decide a location and the extent to which a museum should organize exhibitions), other are less so.
#
In particular when they rely on the decision-making of other art-field actors, such as competition with other museums and sponsorship/funding choices, the influence of the individual founder is severely limited.
#
# The image that these parties have of the private museum might be substantial importance in guiding their decision-making.


**** Competition

needs to write out: 
- [[cite:&Hager_1999_demise]]:
  - p.173: Ten organizations cited an inability to compete as a proximate cause for closure, making it the most popular proximate cause of organizational closure.
  - p.173: Both [art organizations] noted that the majority of the community’s arts dollars, both individual donations/subscriptions and community and corporate grants, tended to go to the singular, most reputable arts organizations of their types (e.g. museums, orchestras, dance troupes) in the metro area. Other arts organizations faced strong competitive pressures from these flagship organizations, a factor which caused the demise of Organizations 276 and 293
- [[cite:&Lecy_2010_nonprofit]]:
  - p.27: The analysis shows that a period of rapid sector expansion – a period where many additional resources are being poured into the sector – creates a more competitive environment as evidenced by higher rates of organizational mortality.
- [[cite:&Park_Shon_Lu_2021_mortality]]
  - p.844: Furthermore, nonprofits that run their business in a county with greater organizational density and population size are more likely to dissolve, which implies that competition, as well as demand for service, prevents nonprofits from surviving
- [[cite:&HernandezOrtiz_2022_discontinuity]]
  - p.116:  A crowded niche increased the competition and limited their access to resources and clients. As reported by informant of organization #C07: "Well, there was less money to go around and more organizations seeking the money. Here we have the same, the same group of people that were supporting the organization, you know, donating to it and that only goes so far. So, we had a full-time grant writer, we were always applying for grants. But there are so many organizations applying for the same grants". (P31, Pos. 49-51)
- [[cite:&Lu_Shon_Zhang_2019_dissolution]]
  - p.43: For example, nonprofits operating in a more competitive environment with a higher degree of organizational density would experience a higher chance of dissolution.
- [[cite:&Haugh_etal_2021_nascent]]:
  - p.1227: SEs are likely to compete with non-profit organizations for grants,donations, and programme-related investments. Second,both SEs and non-profit organizations serve the disadvantaged and socially excluded and thus may also compete for service users. Although collaboration between SEs and charities could increase the supply of services to those in need (Smiddy 2010), they compete with each other for resources and beneficiaries. The more similar the resource needs and markets served, the greater the competition between the organizational forms (Baum and Haveman 1997). Hence, the population density ofregistered non-profit organizations will thus have a detrimental effect on SE survival.    

resource-based: lack of audience, or many other people competing for audience
[[cite:&Velthuis_Gera_forthcoming_fragility]]:
p.23: In other cases, the location of the museum is a factor in limited visitor interest. On the
one hand, private museums located in metropolitan art centers tend to face competition over
visitors  from  well-established  other  museums  in  the  vicinity.  On  the  other  hand,  private
museums located outside of those centers can be confronted with a small local audience, and
difficulties in attracting visitors from afar.



mechanism: losing motivation? 

Private museums have been characterized as highly competitive.
#
While some self-descriptions focus on collaborative aspect, previous studies have highlighted how private museums compete with public museums over art works, audiences, sponsoring and donors [[parencite:&Kolbe_etal_2022_privatemuseum p.4]]. 
#
So far the primary interest of investigating competition has been to evaluate whether art provision by public institutions is threathed.
#
However, competition may also have consequences for the private museums themselves.
#
The extent to which a competitive environment may lead to museum closure has not yet been investigated.
#
However, a possible mechanism/consequence of competition, "lack of interest by the public", has been identified as the second most mentioned closure reason by [[parencite:&Velthuis_Gera_2024_fragility]].
#
As lack of interest can also result from a lack of audience, such as in sparsely populated areas. 
#
Disentangling how visitor 
#

#
 
#



*Hypothesis 3*: A private museum is more likely to close in a more competitive environment.
  
  

**** Identity and the survival prospects of non-profit organizations
# provide legitimacy

An identity that is legitimate (understandable) and favorable (positive) has been argued to have a vast number of positive outcomes for organizations [[parencite:&Lange_Lee_Dai_2010_reputation]].
# 
As gaining the approval of different stakeholders is necessary for being understood and/or supported by other organizations in the environment, having a clearly defined and favorable identity influences resource acquisition and thereby survival prospects [[parencite:&Rao_1994_reputation]].
#
Even for non-profit organizations such as museums, which do not produce tangible goods (a domain where identity-related effects are present, e.g. [[cite:&Hsu_2015_granted;&Bogaert_etal_2014_ecological]]), a clear and positive identity might be helpful in a number of ways:
# 
In particular in the context of private museums, decline of legitimacy or reputation could lead to lower visitor numbers, less discounts from art dealers, less government grants or lower chances on collaborations with other museums or corporations, resulting in lower revenues and higher acquisition costs.


The empirical record of the link between identity and survival for non-profit organizations is mixed: 
# 
For example [[textcite:&Bielefeld_1994_survival]] finds that NPOs who pursue less legitimation strategies (obtaining endorsements, lobbying or contributing to local causes) are more likely to close.
#
However, other studies find limited impact of legitimacy on survival, both when measured via density parencite:&Bogaert_etal_2014_ecological or from archival sources and interviews [[parencite:&Fernandez_2007_dissolution]].
# 
# Thus, even while this study cannot conclusively answer the overall link between idenity and survival, it nevertheless contributes insights into which dimensions of organizational identity do, and which do not contribute to survival in a particular organizational population; namely that of private art museums.


Legitimacy might be obtained by isomorphism, i.e. adopting features associated with blueprints [[parencite:&diMaggio_1983_iron]].
#
# Understandability [[parencite:&Glynn_Abzug_2002_names]] might thus be limited if an organization is atypical [[parencite:&Rosch_1975_family]], i.e. displays an unusual combination of features.
# #
# In the case of private museums, such cases might be combinations of features from house museums (e.g. accessibility only by appointment) with full-service museums (e.g. extensive activities). 
#
Next to "hard" organizational features, adherence to naming conventions has been found to enhance legitimacy [[parencite:&Glynn_Abzug_2002_names]]; organizations that adhere to field norms about name length, name ambiguity (usage of artificial names) and name domain specificity (mentioning industry) were judged more legitimate. 
# 
However, the category of museums could be relatively flexible (for example, it is generally not subject to state regulation), which might result in a relatively high tolerance of diversity as "anything goes" and hence limited "devaluation" of non-conforming, atypical members [[parencite:&Bogaert_etal_2014_ecological]].


Furthermore, identity of a private museum may be influenced by the identity of persons most closely affiliated with it, in particular the identity of its founders.
#
Given that founders are the very reason behind the existence of these organizations, and sometimes plan these as their personal legacies [[parencite:&Walker_2019_collector]], founder status gains or losses may reflect on the wider organization and affect its survival propspects.


#+latex: \bigbreak
#+latex: \noindent
*Hypothesis 1*: Private museums with identities more understandable, legitimate and favorable are less likely to close. 





**** Shocks
External shocks can 


Museums, including private museums, might be relatively resilient [[cite:&Geller_Salamon_2010_resilience]]: 
#
tightening belt, fundraising, entrepreneurial strategies, downsizing
#
The form of museums also implies commitment of resources, larger than that of other NPOs, which in turn provides capabilities, e.g. staff that is able to search for alternative revenue sources.
#

**** Other predictors of organizational survival
***** Age 


The age of an organization is considered in different ways to be related to closing.
#
What started with liability of newness [[parencite:&Stinchcombe_1965_structure]], which posited that organizational mortality decreases over time due to acquisition of capabilities and connections, has lead to a number of extensions [[parencite:&Carroll_Khessina_2019_demography;&Hannan_1998_mortality]]:
#
Liability of adolescence argues that shortly after foundings organizations can still draw on endowments, the expiration of which leads to a peak of mortality some time after opening.
#
While according to this view mortality still decreases after the peak as the organization becomes more established, other perspectives argue also for a positive relationship between age and mortality:
# 
According to the liability of obsolescence paradigm the environment changes faster than organizations which are seen as relatively constrained by inertia, which therefore leads to declining fitness and survival chances.
#
Similar, according to "liability of senescence" capabilities/routines/coalitions can constrain the actions of organizations.
#
Given such conflicting predictions, [[textcite:&Carroll_Khessina_2019_demography]] propose to model age dependence with piece-wise constant hazard models (rather than parametric models) to estimate age-specific effects which can, but do not have to, indicate a relationship between age and mortality.




** Data and Methods

*** Dependent Variable
A newly constructed database, assembled from different sources,  is used to measure the survival of private museums (cf. [[textcite:&Velthuis_etal_2023_boom]] for details).
#
First, existing databases of private art museums are harmonized.
#
Secondly, the online presences of 14 English art publications were exhaustively searched for any mention of private museums.
#
After identifying unique institutions, data on these organizations was collected such as opening year, closing year (of those which closed) and founder information.
# 
Currently, the database includes 547 museums (of which 446 are currently open, the remainder having closed or transformed into other organizational forms).
#
Using this database allows to reconstruct the lifecourse of the each institution with the the unit of analysis as museum-year:
#
The main dependenent variable is thus an indicator of museum closure, which takes the value of 1 for the museums which close in the year of their closure, and 0 otherwise.
#
Typically for survival data, museums that do not close during the observation period are right-censored, i.e. for such museums the dependent variable is zero for all years.


*** Main Predictors

# The organizational identity of a museum is measured primarily in terms of its legitimacy, i.e. its adherence to museum standards, and reputation of its founders.

**** Legitimacy

#+include: "../tables/t_selfid_wcpF.tex" export latex

Two measures are constructed that aim to capture an effect of legitimacy on closing.
#
First, self-identification measures whether a the name of a museum includes the term "Museum", "Foundation", "Collection", or other (such as "Villa", "Institute", "Center" or "Gallery", which are grouped together as they are less frequent, see table {{{reftbl_t_selfid}}}).
#
Since the name is one of the first aspects that stakeholders perceive when engaging with an organization, it might shape expectations and influence forms of engagement.
#
In particular, it might be that museums that also refer to themselves as museums are seen as more favorable and worthy of visits, collaborations and support than other museums.


To ensure that inclusion of the word "museum" corresponds to the naming convention of the museum population, the names of the "Museums of the World" (MOW) database [[parencite:&deGruyter_2021_MOW]], a database containing over 55.000 museums, are analyzed.
#
In this database, {{{mow_prop_name_museum}}}% of museum names contain the term "museum" (or its equivalent in other languages), which indicates a substantial naming convention. 

prevalence of museum founders to include the term museum in the name of their institution[fn::While it would also be possible to construct inclusion in the MOW as an indicator of legitimacy, as it represents recognition of the organization as a museum by experts [[parencite:&Zuckerman_1999_illegitimacy]], preliminary investigations of the database indicated that it has been  updated only sparsely in recent years; thereby inclusion in it (or the lack therefore) does not constitute an accurate measurement of the extent of an institutions' recognition as a museum].


# Secondly, a binary predictor measures whether the museum is included in the 
# #
# While the exact criteria of the research process leading to the MOW database are not known, it is plausible that museums who correspond to an ideal-typical museum are more likely to be included.
# #
# Assuming that museums are seen similarly by the creators of the MOW database and other audiences, inclusion in the MOW database constitutes a proxy for adherence to museum standards. 


**** Reputation

Reputation is measured via inclusion of the founder in the Artnews top 200 collector ranking [[parencite:&Artnews_ranking]].
#
This ranking, established in 1990, lists each year the 200 collectors the editors of the magazine consider most relevant.
#
For each year, a museums can have one of three values: "Not included"; in which case the founder is not included in the year in question and has not been so in the past, "Included"; when the founder is included, or "Dropped", for cases where the founder was included at some point in the past but is no longer included in the current year.
#
Cases where multiple individuals are involved in the founding of a private museum are resolved by aggregating the Artnews ranking inclusion history to the founder level (i.e., if only one of two founders is dropped from the Artnews ranking but the other remains included, the founder couple as a whole is considered included).
#
The variable is lagged by one year to avoid reverse causality, i.e. to exclude the possibility that an association is observed which is present due to founders being dropped from the ranking as a consequence of the closure of their museum.


**** Organizational transformation 
:PROPERTIES:
:CREATED:  [2024-04-07 zo 15:06]
:ID:       764f17aa-0bd3-400b-a3ee-d72770e988f1
:END:

A measure of founder death is constructed as a time-varying covariate, and is set to 1 for museum-years after the death of the founder. 

**** Competition
:PROPERTIES:
:CREATED:  [2024-04-07 zo 15:07]
:ID:       e891980a-d6c2-400a-8770-238a1c68eb09
:END:

On a national level, density of private museum is calculated as the number of private museums per million.
#
On a local level, I use the Global Human Settlement Layer [[parencite:&EC_2023_GHSL]] to estimate the number of private museums and population counts inside a radius of ten kilometers around each private museum for each year.
#
To be able to estimate both competition and demand/audience/population separately, I do not calculate densities as per capita rates, but include the local museum counts, local population in millions as well as an interaction between the two.

*** Control variables

#+latex: \bigbreak
#+latex: \noindent
A number of control variables are used: 
# 
On the level of the founder, gender constitutes a time-invariant variable; with possible values being male, female and couple.
#
# Organizational transformation, such as change of authority has been to increase chances of closure both generally [[parencite:&Carroll_Khessina_2019_demography]] and in the case of private museums specifically ([[cite:&Walker_2019_collector p.234]]: "seldom do heirs share a similar passion or wish to take on the financial burden of maintaining private museum indefinitely").
# Therefore, a measure of founder death is constructed as a time-varying covariate, and is set to 1 for museum-years after the death of the founder. 
#
Centrality of the founder's vision is measured via the proxy of whether the name of the founder is included in the name of the museum.


# Furthermore, organizational theory [[parencite:&hannan89_organ]] predicts a U-shaped relationship between density and mortality:
# # 
# While at low levels, increases in the number of organizations are argued to primarily increase legitimacy and lower exit rates, increases at higher numbers increase the competition over resources and thereby raise mortality rates.
#
# On the level of the environment, therefore the density (number) of private museum per country is included both in linear and squared form.





# limitations:
# - how many are matched: around 60% -> complain that rest isn't included
# - 






*** Analytical framework


First, I investigate the relationship between age and closing descriptively using hazard rates and the Kaplan-Meier survival function.
#
This non-parametric method estimates the hazard rate as the conditional probability of exiting at time t_i given being alive as $h(t_i) = \frac{d_i}{n_i}$, (with $n_i$ as the number of units at risk at time $t_i$ and $d_i$ as the number of exits at time $t_i$), and the survival function as the product of these conditional probabilities as $S(t) = \prod_{t_i \geq t} \left(1-h(t_i) \right)$.



# In a second step,
Secondly, we use Cox proportional hazard models which estimate the relationship between covariates and the hazard rate.
#
The Cox-proportional hazard model has the form $h(t,\mathbf{x}) = h_0(t) \psi$, where $\psi = \exp(\sum_{j} \mathbf{x}_j \beta_j)$; with $h(t)$ as the hazard rate, $h_0(t)$ as the baseline hazard rate, $\mathbf{x}$ as the set of variables indexed by $j$, and $\beta$ as the coefficient vector.
#
Partial maximum likelihood estimation allows calculating \beta without defining the baseline hazard rate, which therefore is not constrained to a parametric form. 
# 
Coefficients are interpeted as log hazard ratios, i.e. as multipliers of the baseline hazard rate. 



** Results

*** Summary statistics

#+INCLUDE: "../tables/t_sumstats_wcpF.tex" export latex

In total, 479 private museums are included in the database, 53 of them have closed.
#
6903 museum-years are observed; table {{{reftbl_t_sumstats}}} shows summary statistics for all variables.

*** Hazard rate and Age Dependence 

{{{ynkplt_p_hazard}}}

{{{ynkplt_p_surv}}}


Figure {{{refplt_p_hazard}}} shows the hazard rate over time, figure {{{refplt_p_surv}}} the corresponding survival probability.
#
The hazard rate doubles over the first 10 years from approximately 0.45% to 0.9%, at which value it approximately stays constant for the next 20 years, after which it appears to decline.
#
However, the decline after thirty years is presumably less certain as very few private museums have already reached this age.


The increase in the first years is likely due to endowments: As the establishment of a museum requires considerable resources, their founders appear to allocate enough resources to keep the risk of closure small in the first years after opening.
#
Given that founders are likely aware that their endeavor is unlikely to generate a profit, they are not vulnerable to the liability of newness [[parencite:&Stinchcombe_1965_structure]].
#
The relative stability of the hazard rate after ten years has no correspondence in classical theories on age dependence:
#
While an increase in mortality as observed here is predicted by the idea of "liability of adolescence" [[parencite:&Carroll_Khessina_2019_demography]], this framework also predicts a decline in mortality after a peak due to becoming established.
# 
Furthermore, while "liability of obsolescence" and "liability of senescence" (ibid.) predict higher mortality for older organizations due to mismatch with the environment and inertia (inflexible internal routines), it seems questionable whether museums would have reached obsolescence or senescence already after ten years.
#
Furthermore, the applicability of obsolescence and senescence might be limited for non-profit organizations.


Overall the entire life span, the average hazard rate is {{{meanhaz_upto_100}}}, which allows comparison to other studies of NPO closure.
# 
While I did not find a systematic literature review or meta-analysis, a number of individual studies had investigated similar populations based on IRS data (see table \ref{tbl:litreview}) 

#+caption: Hazard rates in studies of museums and art NPOs
#+label: tbl:litreview
|-----------------------------------+--------------+------------------+
| study                             | population   | avg. hazard rate |
|-----------------------------------+--------------+------------------+
| [[cite:&Hager_2001_vulnerability]]    | Art Museums  |             2.4% |
| [[cite:&Gordon_etal_2013_insolvency]] | Museums      |             0.7% |
| [[cite:&Bowen_1994_charitable]]       | Museums      |             1.1% |
|-----------------------------------+--------------+------------------+
| cite:&Hager_2001_vulnerability    | all Art NPOs |             2.8% |
| cite:&Gordon_etal_2013_insolvency | all Art NPOs |            2.08% |
|-----------------------------------+--------------+------------------+

# this is kinda the main comparison...
[[textcite:&Hager_2001_vulnerability]] and [[textcite:&Gordon_etal_2013_insolvency]] both study NPOs more generally, but report survival estimates by organizational form.
#
# At the moment it is not clear which factors account for their hazard rates to differ substantially, but it might be due to selection criteria.
#
Both these studies also report substantial variation in hazard rates between organizational forms.
#
While these comparisons indicate that private museums have dissolution rates lower or similar to museums and non-profit organizations generally, more research is needed to establish the comparability of these hazard rates.


Comparison to other forms of nonprofit organizations reported by [[parencite:&Gordon_etal_2013_insolvency]]
places private museum at a risk similar to that of animal shelters and zoos (0.7%), botanical & environmental centers (0.8%), colleges and universities (0.8%), food and agricultural-oriented human service organizations (0.8%) and  student and educational services (0.8%).
#
While the diversity of non-profit organizations makes comparisons to its entirety difficult, it is still worthwhile to consider that the average hazard of private museums {{{meanhaz_upto_100}}} is around half that of that NPOs generally (1.58%, see table \ref{tbl:litreview2} for studies on wider nonprofit populations).
#
It is furthermore substantially lower than that of youth centers (1.4%), children-focused human services (2.4%), K12 schools (1.8%), mental health organizations (2.4%) or performing arts organizations (3.7%).
#
In fact, lower dissolution rates are only reported for historical societies (0.5%) and libraries (0.2%).



#+caption: Hazard rates in studies of NPOs
#+label: tbl:litreview2
|------------------------------------------------+------------------+------------------+------------------------|
| study                                          | population       | avg. hazard rate | data source            |
|------------------------------------------------+------------------+------------------+------------------------|
| cite:&Gordon_etal_2013_insolvency              | NPOs             |            1.58% | IRS                    |
| [[cite:&Hager_Galaskiewicz_Larson_2007_liability]] | NPOs             |            1.25% | own data               |
| [[cite:&Clifford_2018_reinforcing]]                | Charities        |            2%-5% | Reg. of Charities (UK) |
| [[cite:&Mayer_2022_simmer]]                        | public charities |            0.17% | IRS                    |
|------------------------------------------------+------------------+------------------+------------------------|


# The Kaplan-Meier survival probability is around 75% after thirty years (figure {{{refplt_p_surv}}}).






# #+latex: \noindent
# TODO:
# - get confidence interval for hazard rate
# - see how age can be integrated into survival models (linear term doesn't work)
# - expand comparison to other studies



*** Regression Results

#+INCLUDE: "../tables/t_reg_coxph_wcpF.tex" export latex

Table {{{reftbl_t_reg_coxph}}} shows the results of Cox proportional hazard regression model.


**** Control Variables

#
Neither gender nor inclusion of founder name is significantly associated with mortality rates.
#
# (TODO: add reference, very speculative!!)
While generally organizations whose name include the name of their founder might be more centered around the founder, and hence display higher inertia, making them less able to adapt to changing environments, these results indicate that it does not seem to be case for private museums.


**** Identity Variables

Museums which include the term "museum" in their name are the least likely to close, while those with the term "foundation" or "collection" have higher closure rates (but not significantly higher).
#
Museums which include neither of these are the most likely to close, and have mortality rates more than three times as high ($e$^1.18 = 3.25, p<0.01) than institutions including the term "museum".
#
The usage of unconventional names might reflect adherence to museum standards which makes museums more understandable and familiar to third parties (e.g. audiences, other museums, companies or the government) and thereby facilitates interactions which are beneficial for long-term survival (e.g. attracting visitors, cooperations, sponsorships or subsidies).
# 
However, as founders can choose the name of their museum arbitrarily, they might choose a name without reference to organizational forms associated with perpetuity precisely because their intention is not an institution enduring in perpetuity but rather a more temporally bounded project.


Museums included in the Museum of the World Database are $e$^-0.88 = 0.41 (p < 0.05) times as likely to close than museums which are not, yet this result might be produced by different mechanisms.
#
On the one hand, it might reflect that larger and richer institutions are both more likely to be noticed by the MOW and more likely to survive (MOW inclusion would then be a proxy for resources).
#
#
# (TODO: Because of this I wonder if it even makes even sense to include MOW)
# Thirdly, the MOW effect might be endogenous: As no longitudinal MOW data is available, museums might be absent in the MOW because they have closed.
On the other hand, similar to unconventional naming patterns, lack of inclusion in the MOW could be an indicator of deviance from museum standards, which could increase the unfamiliarity of the museum vis-a-vis third parties, reducing the chance of survival-enhancing interactions.


The reputation of the founder is not statistically related to closure. 
#
Museums whose founders are not included in the ARTnews collector ranking (reference category) are the least likely to close, followed by museums whose founders are included (not statistically significant) and by founders who were included at some point but are no longer included (not statistically significant).
#
# While the order of the categories does not fully correspond to the expected order, according to which museums whose collectors are not included would be more likely to close than collectors who are, it nevertheless provides some evidence that status matters; as in particular the loss of status appears to be substantially associated with museum closure.

**** Organizational transformation

The death of the founder is not associated with a significant difference in private museum closure, i.e. museums are not significantly more likely to close after their founder has died.
#
This possibly indicates that private museums might be less dependent on the mood of a single person (or couple), and have in fact become institutionalized to an extent that heirs of founders feel as motivated to continue the original founders' efforts as these founders themselves.

**** Competition
{{{ynkplt_p_pred_popprxcnt}}}



Country-level Environmental variables show no association with mortality.
#
However, at the local level the number of private museum and population density predicts survival chances as the main effects of population number of private museums as well as its interaction is significant.
#
Figure {{{refplt_p_pred_popprxcnt}}} shows predicted average hazard rates for different conditions of regional PM density and population numbers.
#
Museums located in sparsely populated areas have (at low PM densities) lower hazard rates than museums in more densely populated areas. 
#
Furthermore, these "rural" museums see an increase in the risk of closing for each additional private museum present within 10 kilometers, whereas the risk of closing decreases with  each additional private museum in the local environment for museums in more urban areas. 
#

#
# However, they have at low PM density lower closing rates than museum in more populated areas.

# #
# While the density-dependence paradigm predicts a negative effect of numbers of organizations on closing rate at low numbers (due to legitimacy, i.e. growing familiarity with a new organizational form), and a positive effect at high numbers (due to competition over resources), neither relationship is significant in the case of private museums.


** Discussion


Investigating the survival prospects of private museum furthermore illucidates the long-term development of the organizational form as a whole, as it provides insights into factors related to variation of sustainability and thereby into trends in composition. 

*** gender :ignhead:
#
# While the composition of private museums is not only influenced by closures, but also by foundings,
# 
Given the non-significant gender difference, it can be expected that (unless given a strong increase in founding by women) the population of private museums will continue to remain a man-dominated affair.
# [fn::The point estimates, which are higher for women and couples, albeit not significantly so, even point towards a slight expansion of the proportion of museums established by men.] # add this if gender - female is substantially positive
#
This finding also provides no evidence that female founders face gender-specific challenges that decrease the survival prospects of their private museums. 


*** audience/competition :ignhead:



# FIXME: rewrite with focus on audience/competition
# The effects of location might be seen
# #
# On the one hand, museum location is chosen by the founder at the time of founding (or rather, several years in advance).
# #
# This gives founders substantial choice in the size and composition of the potential audience who will be able to easily assess the museum.
# #
# On the other hand, collectors are less able to influence what plans other collectors might have.
# #
# What may have been at one point been identified as a promising location without substantial competition may turn out to be a much less fertile ground as soon as other collectors start eyeing the same region for their own private museum projects.
# # 
# In particular private museum in rural locations with low population densities seem to be at risk when other museums open in the neighborhood. 
# #
# This is not to say that private museums cannot endure in areas with low population densities. 
# #
# In fact, at low numbers of private museums in the neighborhood their survival prospects are better than those located in larger cities.
# #
# These larger cities with low private museum counts are possibly also characterized by lower numbers of other cultural institutions as well as an audience less interested in postmaterial art consumption.


{{{ynkplt_p_pred_heatmap}}}



*** facilities/size :ignhead:
# FIXME: rewrite with 


The lack of a relation between temporary exhibitions and survival prospect is somewhat unexpected.
#
It was expected that as temporary exhibitions constitute one of the main tasks of a museums operations, organizing them would benefit a museum financially (via visitor fees) and symbolically (via prestige of other art field actors, which might be developed into further contacts), leading to higher survival chances[fn::Furthermore, the ability to organization exhibitions likely reflects museum resources, which should also enhance survival.]
# not sure this follows
However, organizing exhibitions does not seem to bestow benefits for the museums which organize them, nor do organizations seem to be organized only by established/sustainable/secure organizations.
#
One possibility for this discrepancy could be that exhibitions are expensive, and whatever benefits gained from them are offset by the associated costs.
#
One might see in this association again the importance of the founder:
#
Founders who are committed to their museums will keep them alive, regardless of whether or not they plan to organize temporary exhibitions.







*** founder
:PROPERTIES:
:CREATED:  [2024-05-29 wo 12:08]
:ID:       676af2e2-9b94-489e-88a8-6a87397c864a
:END:

# FIXME: rewrite from observation level to process level
# The role of the founder is two sided.
# #
# Death and exclusion from a prestigious ranking are not associated with a higher risk of closure, which indicates that private museums have attained a substantial degree of institutionalization.
# #
# On the other hand, self-identifying as an institution which is not a museum, foundation or collection possibly reflects a kind of founder attitudes which substantially influences survival chances.
# #
# Founders who are less interested in establish institutions might be more inclined to choose a name which less reflects this ambition. 
# #
# One way of conceptualizing this distinction might then be that whereas involuntary, externally imposed events are less able to close museums of otherwise motivated founders, some founders might from the very beginning voluntarily decide to not establish a museum that is intended for perpetuity.


# However, this group is somewhat small.
# #
# Of the XXX museums included in the database, XXX do not carry the term museum, foundation or collection.
# #
# Thus given this low share, and the corresponding  higher closing rate, a possible future for the private museum population might be increased institutionalization and consolidation of relatively robust organizations.
# #


** Conclusion
# The conducted analysis shows a substantial association between private museum identity and closures.
# #
# While alternative explanations cannot be completely ruled out, a clearly understandable identity and a favorable founder reputation emerge as important predictors of the chance of a private museum to close.
# #
# Future research can expand on these findings by in more detail investigating the resource perspective of private museums, the intransparency of which has so far aggravated insights about budgetary aspects, in particular how these financial and material characteristics are moderated or mediated by processes of organizational identity.

Private museum have been characterized as fragile institutions due to their reliance on a single founder.
#
However, my analysis finds neither a higher substantially higher mortality rates for private museums compared to (art) museums generally, nor a conclusive relationship between museum closure and a number of founder characteristics, such as founder gender, death, exclusion from the Artnews collector ranking or inclusion of founder name in the museum name.
# 
While Self-identification and audience/competition are significantly associated with higher mortality, and possibly reflect or influence founder motivations, they are also subject to alternative mechanisms, namely devaluation by third parties and competition, respectively (self-identification furthermore concerns a relatively small group of institutions).
#
Furthermore, even if they reflect founder motivations, these are likely cases of voluntary closure; there is thus no large evidence that private museums are at a higher risk of unvoluntary closure than more diversified museums as a consequence of their reliance on a single founder. 



A possible explanation of the characterization of private museums as fragile might be due to the focus on case studies, which disregards the much larger population who don't experience closing.
#
Due to the "private museum boom", some museums will experience closing over a period of around two decades even if the underlying closing probability is low.





It cannot be stated whether private museums experience higher mortality rates than publicly funded museums (for which European countries would be the most natural comparison).
#
While public museums have been characterized to some extent as very stable due to government picking up deficits [[parencite:&Meier_Frey_2003_faces;&Bechtler_Imhof_2018_future]], [[textcite:&Walker_2019_collector]] argues that due to declining cultural spending even public museums might face hard times.
#
While national public flagship institutions will likely remain sufficiently funded to survive, this might not be the case for the vast majority of smaller museums in less touristic regions who rely on limited municipal funding, as textcite:&StylianouLambert_etal_2014_museums demonstrates for a number of smaller publicly funded ethnography museums in Cyprus.
#
Without access to museum register comparable to the IRS/NCCS datasets, such questions regarding the relation between type of ownership and survival remain speculative.


#+Latex: \begin{sloppypar}
#+Latex: \printbibliography
#+Latex: \end{sloppypar}



*** Limitations

**** no transformation :ignhead:
For this study, I only investigated the occurence of closure events.
#
However, private museums can stop existing as private museums not just by closing down, but also by being transformed into other organizational forms.
#
One way in which this can happen is when other parties, such as local governments other philanthropists, foundations, or corporations become substantially involved in the ownership, governance and/or funding of the museum.
#
Sometimes this involves changes in the composition of the board of directors (or equivalent), with new parties gaining seats and hence influence in decision-making, thereby diminishing the private character of the museum to an extent that it no longer fits the working definition.
#
Museums which experienced this trajectory have been excluded from the analysis as explorative investigation showed that it was not possible to generally determine the date of such transitions[fn:: Consequently they are excluded from the analysis alltogether, and thus also not contributing to the the hazard rate for closing, despite being entities at risk for closing. However, as their numbers are limited to {{{pmdb_n_nlpm}}} entries in the database, the bias this introduces into closing risks is likely not substantial.]
#
The main issues that made the determination of the date impossible was the intransparency of these organizations (~event in the past, no track of organizational history~), as well as the gradual process.
# 
As the presence of non-founder members does not categorically exclude a museum from being categorized as private museum as long as third-party influence is limited, this influence can grow until the museum bears little resemblance to its former self.
#
The possibility of other outcomes than surival and closures has been investigated for NPOs more generally
[[parencite:&Searing_2020_zombies;&HernandezOrtiz_2022_discontinuity;&Helmig_Ingerfurth_Pinz_2013_nonprofit]], and for private museums specifically: 
#
[[textcite:&Walker_2019_collector]] argues that in the case of Germany, private museum founders turn to the state to ensure the survival of their projects in the form of public-private partnerships.
#
Investigating this process of transformation into a different organizational form thus provides fruitful avenue for further research. 

**** closing reasons not as rich as previous studies
:PROPERTIES:
:CREATED:  [2024-08-23 vr 10:34]
:ID:       45725b05-928c-4633-a690-9095ef61b849
:END:

The extent to which closing factors are investigated does not reach the level of detail by [[cite:&Velthuis_Gera_2024_fragility]], who investigate each closing separately.
#
On the other hand, the inclusion of the museums who do not close results in a more more complete comparatison. 
#
A research approach that would combine the strengths of both approaches could for example consist of leveraging additional data sources, such as financial histories of founder companies to investigate financial issues or search engine results, media reports or social media posts to assess interest from the public. 

# maybe move to future research

**** environment :ignhead:
environment can be measured more
- geocoding of other institutiosn
- tax incentives
- government spending
- government: political changes, censorship, persecution  
-> this might futher specify the niches in which PMs can endure

**** facilities/size :ignhead:
:PROPERTIES:
:CREATED:  [2024-08-23 vr 10:32]
:ID:       4b290835-a2d9-4d50-915f-1eb90d8a7cf5
:END:
Museum characteristics might influence closing to a larger extent than has been considered here.
#
For example, museum size, facilities, as well as marketing and outreach activities might be related to long-term survival prospect.
#
For example, museums with more XXX might be more expensive to run, but on the other hand attract higher visitor numbers, cooperations and sponsorships. ~liability of smallness~
#
Furthermore, having XXX might reflect founder commitment/resources.
# 
While the original data collection included the measurement of various museum characteristics, such as floor and collection size, facilities, and cooperations, it became clear in the process that desk research was unsuitable to construct reliabile indicators from these findings due to difficulty in assessing them in many cases.
#
Especially for closed museums data collection proved difficult, as in many cases websites had been shut down, and while in many cases snapshots of the main website were available in the Internet archive, ~subdomains~ were archived much less frequently, and sometimes inaccessible despite being archived due to changes in webtechnology (such as flash).
#
While it would be possible to
absence of evidence as evidence of absence

*supplementary material*






covid effect may take longer to be effective

 
*** future research
The US register data on NPO tax filings constitutes a promising source for data for museum research (while this data source has seen frequent usage in non-profit management, it remains underexploited in the field of museum research). 
#
While the United States private museum population with XX museums and YY closings might not be sufficient to test whether private museums have a a higher closing risks than other museums, it still hosts a large population of museums.
#
Thus this data can be used to establish average mortality estimates for museums generally as well as different types of museums, which can be compared to those observed for private museums globally. 
#
Its furthermore a rich source of financial data

egmus doesn't have that

