* lit review 
:PROPERTIES:
:ID:       f6770c62-73be-446d-98d2-6ffd9b32b282
:END:

** existing stuff 

on private museums: 
- [[cite:&Adam_2021_rise]]
- [[cite:&Brown_2019_private]]
- [[cite:&Walker_2019_collector]]
- [[cite:&Velthuis_Gera_forthcoming_fragility]]
  elegant approach: talk about costs generally, then as a reason for closure
  cites
  - [[cite:&Walker_2019_collector, p.146]]: finance
  - [[cite:&DeNigris_2018_museums]]: no long-term strategy
  - [[cite:&Adam_2021_rise]]: founder disengagement, wrongdoing
  own finding: complex, often finance 
  -> very PM focused, also wishy-washy with "complexity"
  

density-dependence
- [[cite:Carroll_1989_density]]
- [[cite:&Carroll_1989_density_repl]]
- [[cite:&Carroll_2000_brewery]]
- [[cite:&Hannan_1992_dynamics]]: chapter 6
- [[cite:&Hannan_etal_1995_cars]]
- [[cite:&Hedstroem_1992_impasse]]: check if this gets referenced


overall argument: low density -> low legitimacy -> high closing
increasing density -> increasing legitimacy -> less closing
what is actually at high closing? [[cite:&Delacroix_Rao_1994_unbundling]]: -> competition -> high closing 


extentions of density
- [[cite:&Rao_1994_reputation]]: actual measurement of legitimation through competitions/certification/rating
- [[cite:&Zucker_1989_legitimacy]]
- [[cite:&Kennedy_2008_counted]]: sensemaking
  -> somewhat addressed in [[id:f6f23e3e-0cad-42c3-ace6-1518d4208b86][variable-driven]]
- [[cite:&Ruef_2000_emergence]]: discourse 
- [[cite:&Ruef_2004_demise]]:
  check who cites this
- [[cite:&Abrahamson_1999_fashion]]: superstitious: PMs get dropped when not providing differentiation
  # but failure to provide differentiation will be impossible to measure
- [[cite:&Dobbin_Dowd_1997_competition]]: about policy -> foundings
- [[cite:&Greve_2006_vox]]: combination of SM, ecology, production of culture
  also dealing with theory is relevant/inspiration: not actually about microradios, but theoretical contribution
- [[cite:&Greve_2002_banking]]: spatial dimension
- [[cite:&Hedstroem_1994_diffusion]]: mobilization, spatial
- [[cite:&Hsu_2005_forms]]: organizational identity/form should be measured directly (or what?), taken-for-grantedness
- [[cite:&Lizardo_2009_comparative]]: all kind of stuff of field, identity, category, logic
- [[cite:&Lomi_1995_population]]: spatial stuff, heterogeneity: not really new stuff, but expanded existing -> nice normal science
- [[cite:&Porac_1990_taxonomic]]: competitor definition
- [[cite:&Powell_1991_introduction]]: taken-for-grantedness
- [[cite:&Singh_1991_change]]: government recognition, funding -> periods change density dynamics
- [[cite:&Negro_2011_winemaking]]: schemas, also has defection tho
- [[cite:&Fligstein_2002_markets]]: much about markets, PMs aren't.. but the institutional part
- [[cite:&Fligstein_2015_fields]]

*should map key concepts from all articles -> sees what gaps there are*


luxury:
- [[cite:&Cousin_Chauvin_2021_bourgeoisie]]: has some references to luxury consumption


  


*** variable-driven
:PROPERTIES:
:ID:       f6f23e3e-0cad-42c3-ace6-1518d4208b86
:END:

demand/legitimacy
- *inclusion in MOW/IDA*: don't have good longitudinal data tho..
- *trip advisor/social media/google reviews/media*: could link to insufficient interest from public [[cite:&Velthuis_Gera_forthcoming_fragility]]

- *organizational characteristics*
  - activities (PMDB), size, collaborations

- *founder characteristics*:
  - financial situation: performance of companies that they are board members of? -> BvD
    could also be complicated..
  - industry? I don't see how this is a good measurement.. also throwing 15 dummies in there doesn't sound great for identification
  - could do billionaire or not KEK

 - Covid restrictions


-> all things that could matter for PM, but *what's the point*? -> need more theory overall
we actually don't care about private museums...

resource-dependence

we care about wider stories/mechanisms of which private museums are an example
-> should be liberating: can choose the story, and fit PMs in there



*** use clickhouse/org-brain tags to find similar terms/papers
:PROPERTIES:
:ID:       f64cff75-7387-4440-b41a-bb3d6fc7a932
:END:

search terms:
- [X] density
- [X] ecology
- [X] mortality
- [ ] survival: at Hanna_2010_partiality
- [ ] exit
- [ ] defection
- [ ] event-history


#+begin_src R
library(DBI)
library(collapse)

con <- DBI::dbConnect(RClickhouse::clickhouse(), host="localhost", db = "obvz")

cmd_bc <- "select * from bc"
cmd_bp <- "select * from bp"

## get both parent and child relations (unclear why there are separate tables, but whatever)
dt_bc <- qDT(dbGetQuery(con, cmd_bc))
dt_bp <- qDT(dbGetQuery(con, cmd_bp))

## generate brain links
dt_bl <- rbind(dt_bp[, .(child, parent)], dt_bc[, .(child, parent)]) %>% unique 
  
rel_terms1 <- .c(ecology, mortality, density)

## find papers that are good on relevant terms

## long-collapse version
sbt(dt_bl, parent %in% rel_terms1) %>% gby(child) %>% smr(cnt = len(child)) %>% sbt(cnt >= 2)

## more compact collapse
dt_rel_papers <- sbt(dt_bl, parent %in% rel_terms1) %>% fcount(child) %>% sbt(N >= 2)

## even more compact collapse possible? doubt it: different steps
## sbt(dt_bl, parent %in% rel_terms1 & fcount(parent, child) > 2)

## dt still most compact 
dt_bl[parent %in% rel_terms1, .N, child][N >= 2]

## tags they they use
dt_bl[dt_rel_papers[, .(child)], .(parent), on = "child"] %>% fcount(parent) %>% roworder(-N) %>%
  sbt(parent %!in% rel_terms1) %>% sbt(1:20)


## find papers that have similar tags to papers high on relevant terms
dt_other_papers <- dt_bl[dt_rel_papers[, .(child)], .(parent), on = "child"] %>% funique %>% 
  dt_bl[., on = "parent"] %>% .[!dt_rel_papers, on = "child"]

## tags that other papers use
dt_other_papers %>% fcount(parent) %>% roworder(-N) %>% sbt(1:20)

## print the papers with the largest absolute overlap
dt_other_papers %>% fcount(child) %>% roworder(-N) %>% sbt(1:30)
  
  
#+end_src

#+RESULTS:
| Porac_Ventresca_Mishina_2017_cognition | 29 |
| Hsu_2005_forms                         | 27 |
| Peltoniemi_2014_cultural               | 23 |
| Fligstein_2015_fields                  | 23 |
| Rossman_2012_climbing                  | 22 |
| King_Pearce_2010_contentiousness       | 20 |
| Porac_1990_taxonomic                   | 20 |
| Kirschbaum_2017_jazz                   | 20 |
| Bourdieu_1993_production               | 19 |
| Abrahamson_1999_fashion                | 18 |
| Friedland_1991_symbols                 | 18 |
| Rao_1994_reputation                    | 17 |
| Maclean_etal_2021_philanthropy         | 17 |
| Fligstein_2002_markets                 | 17 |
| Cousin_Chauvin_2021_bourgeoisie        | 17 |
| Powell_1991_introduction               | 16 |
| Berwick_Christia_2018_capacity         | 16 |
| Hsu_2006_jacks                         | 16 |
| Hsu_2015_granted                       | 16 |
| Kackovic_etal_2020_quality             | 16 |
| Piazzai_concepts                       | 15 |
| Lena_2019_entitled                     | 15 |
| Lizardo_2009_comparative               | 15 |
| Fligstein_1991_transformation          | 15 |
| Gnyp_2015_collectors                   | 15 |
| Boone_2012_uneveness                   | 15 |
| Brown_2019_private                     | 15 |
| KohlArenas_2015_selfhelp               | 15 |
| Lena_2008_classification               | 14 |
| KalbCosmo_2020_museum                  | 14 |

-> this really seems to be all kind of things.. 


** stuff I haven't read
:PROPERTIES:
:ORDERED:  t
:END:



[[cite:&Chambre_Fatt_2002_liability]]


[[cite:&Hager_etal_1996_grave]]

[[cite:&Dupuy_Ron_Prakash_2014_crackdown]]: can cite it as extreme case, or even use their measurement

[[cite:&Vance_2010_funding]]

[[cite:&Mayer_2022_slimmer]]: also recycling the IRS data

[[cite:&Shon_Lu_2023_demographic]]: heh really milking your IRS data aren't you
[[cite:&Park_Shon_Lu_2021_mortality]]: meh IRS

[[cite:&HernandezOrtiz_2022_discontinuity]]

[[cite:&Helmig_Ingerfurth_Pinz_2013_nonprofit]]: maybe.. 
[[cite:&Lu_Shon_Zhang_2019_dissolution]]



[[cite:&Hager_1999_demise]]

[[cite:&Arbogust_2020_closure]]

[[cite:&Herlin_2013_sorry]]
[[cite:&Hager_Galaskiewicz_Larson_2007_liability]]


[[cite:&Haugh_etal_2021_nascent]]


[[cite:&Lounsbury_Ventresca_Hirsch_2003_recycling]]: inspiration: irrelevant actual case, nice theorizing


[[cite:&Kennedy_2009_TQM]]: both economic and social considerations in adoption decisions

[[cite:&Pizza_Abrahamson_2020_fads]]: management fashion.. maybe too much about management


[[cite:&Goldfarb_Zavyalova_Pillai_2018_Rao]]: check also for methodology
certification: is there something like best museums?
https://www.forbes.com/sites/rsmdiscovery/2017/10/30/ranking-the-worlds-most-admired-art-museums-and-what-big-business-can-learn-from-them/
could google for "top 100 museums in the world"
https://www.theinternationalman.com/art-museums.php LUL 

[[cite:&Greenwood_etal_2017_handbook]]: there are some interesting chapteres: Meyer, Scott, Diversity programs,
[[cite:&Scott_2008_theory]]

[[cite:&Dupin_Wezel_2023_bakeries]]: read for inspiration of theorizing


[[cite:&Wakefield_2017_superrich]]

[[cite:&Petersen_Koput_1991_heterogeneity]]: decreasing mortality when density increases could be unobserved heterogeneity -> should measure legitimation directly
see how it relates to [[cite:&Lomi_1995_population]]
[[cite:&Tasselli_Zappa_Lomi_2020_holes]]

[[cite:&Delacroix_Rao_1994_unbundling]]: decompose density into separate processes
- Dominik Meier (ERNOP): survival: [[file:~/Dropbox/phd/conferences/ERNOP/Meier_Litofcenko_2023ernop_blurry.docx]]
  paper doesn't include survival aspect.. 

  could also look at mission statements -> atypical have higher mortality rate?

- Petra van Aken: [[file:~/Dropbox/phd/conferences/ERNOP/van_Aken_2023_identity.docx]]

[[cite:&Barnett_Fen_Luo_2012_identity]]: cited by [[cite:&Carroll_Khessina_2019_demography]]: naming as constraint to change

[[cite:&Glynn_Abzug_2002_names]]: cited by [[cite:&Carroll_Khessina_2019_demography]]: names matter

cite:&Dobrev_etal_2006_interdependence

[[cite:&Rousseliere_2019_mortality]]: methods: correlated random effects, also some yuge Bayesian approach.. 

check Dieuwke's lit

** donesies

[[cite:&Hager_2001_vulnerability]]: museums close quite much as well: 6.2% in 4 years; 10% in 8 years
shows against the nichyness of PMs


[[cite:&Duckles_Hager_Galaskiewicz_2005_close]]: finance doesn't matter sooo much (neither necessary nor sufficient), internal cohesion/external demand important

cite:&Bogaert_etal_2014_ecological: about founding/closing ~ legitimation
check the arguments about NPOs
fuzziness is interesting -> should look into GoM


[[file:~/Dropbox/nootes/Teece_2023_euram.org]]: dynamic capabilities -> corporate shill


[[cite:&Bielefeld_1994_survival]]: high mortality in fast-growing sectors; age/size/strategies/funding
[[cite:&Carroll_Khessina_2019_demography]]: resources, competition, specialization, cognition/identities, inertia


[[cite:&Searing_2020_zombies]]: p. 369: "the role of financial resource dependence appears to be limited. If anything, financial difficulties appear to be symptomatic of other, deeper conditions that are more contributory"




** less directly relevant
[[cite:&Walker_2010_reputation]]: reputation overall
[[cite:&Pfarrer_Pollock_Rindova_2010_assets]]: reputation on earnings surprise behavior/perception of that
[[cite:&Lange_Lee_Dai_2010_reputation]]: also lit review of reputation

[[cite:&Cavusgil_Seggie_Talay_2007_dynamic]]: dynamic capabilities
[[cite:&Strang_Soule_1998_diffusion]]: diffusion

management fashion: 
- [[cite:&Clark_2004_surge]]
- [[cite:&Gill_Whittle_1993_panacea]]

** ideas dumping ground
:PROPERTIES:
:CREATED:  <2023-08-17 do 11:19>
:END:

- search the openalex citations of density papers for luxury consumption
- search the openalex citations/references of non-profit closure for
  - luxury consumption
  - tax incentives
  - (government) regulationk


variation: what variable have proper (correponding to theory) amounts of variation:
- not funding source variation...
- countries

  
Andy thinks there's still some variation, e.g. having a board -> more people are putting in money -> less concentration of resource sources
same with friends-of association

what if interaction? e.g. lack of diverse funding sources could be a problem only if there's a decline in founder's wealth -> i'm done

also thinks laws of countries matter [[cite:&Dupuy_Ron_Prakash_2014_crackdown]], tax incentives
search on semantic scholar:  https://www.semanticscholar.org/search?q=tax%20incentives%20nonprofit%20survival&sort=relevance


EFA of PM attributes: hybridity, typicality [[cite:&Smith_2014_hybridity]]

is there some arguemnt to be made about mediation of cultural stuff (recognition, awards, prestige, reputation) via material reources/money into survival?


** relevance
relevance of density lit: if it quacks like a duck -> if it behaves like an organizational form, it is an organizational form?
point would be that survival doesn't depend on organizational characteristics but environmental
wider relevance: are PMs really a new thing?

e.g. if there was
- no decline in mortality with higher density (which would be more legitimacy)
- less closing with better government spending, or more transformation into public
-> then PMs are not really a thing?

*(institutional) logic*: do PMs constitute a shift in logic of art provision?
# like Yu's husband: kindergardens are clash of confucian (obey authorities), socialist (care for others/society?), capitalist (develop yourself) ideology
hmm doesn't it crash with nichiness? logics [[cite:&Thornton_2015_ilp;&thornton_2012_logics]] are iirc quite large things (state, market, family, religion)
I mean there is no a-priori reason why logic can't operate on smaller scale tho: the logic of public art provision...
# yeah but if I'd look at changes I'd compare e.g. government spending with value added (economic activity in sector)





is consideration of environmental characteristics contribution? to PMs maybe (although [[cite:&Velthuis_Gera_forthcoming_fragility]] have it somewhat), but not overall..
could do some cross-level interactions? -> for now seems forced, maybe makes sense later tho


fashion: what would show that it's superstitious vs substantial (actually provides something for someone) ?
could be framing: fad/fashion or sustainable?
-> would need bunch of indicators that can differentiate 


dynamic capabilities? 








** AI/citation network tools
:PROPERTIES:
:ID:       97506cf5-5c36-4567-990b-4f5f0351a57e
:END:

*** https://scite.ai/
 15 euros a month

*** done https://citationgecko.azurewebsites.net/
CLOSED: [2023-08-11 vr 10:58]
free, but super incomplete:
[[cite:&Rao_1994_reputation]] has 2k citations irl,
but maybe ~80 there, and none after 2015 (real 943) 

also has no references among the recommended papers

*** https://www.connectedpapers.com/
:PROPERTIES:
:ID:       707111d6-cbab-402a-acc3-41d9b6477c43
:END:
hmm just one paper as input

still not bad

- Walker 2010: A Systematic Review of the Corporate Reputation Literature: Definition, Measurement, and Theory
  [[cite:&Walker_2010_reputation]]: seems less relevant: not much about survival
- Michael D. Pfarrer, Timothy G. Pollock, V. Rindova 2010: A Tale of Two Assets: The Effects of Firm Reputation and Celebrity on Earnings Surprises and Investors' Reactions
  [[cite:&Pfarrer_Pollock_Rindova_2010_assets]]: reputation on behavior -> reaction to that by other parties
- Donald Lange, Peggy M. Lee, Ye Dai 2011: Organizational Reputation: A Review
  [[cite:&Lange_Lee_Dai_2010_reputation]]



Erin Çavuşgil, Steven H. Seggie, M. Talay, 2007: Dynamic Capabilities View: Foundations and Research Agenda
[[cite:&Cavusgil_Seggie_Talay_2007_dynamic]]

G. R. Ferris+ 4 authorsF. R. Blass: The role of reputation in the organizational sciences: A multilevel review, construct assessment, and research directions: dont' even bother to download atm 

using [[cite:&Abrahamson_1999_fashion]]: 

- A. Portes, C. S. Smith, K. Schwartzman 2007: DIFFUSION IN ORGANIZATIONS AND SOCIAL MOVEMENTS: From Hybrid Corn to Poison Pills: [[cite:&Strang_Soule_1998_diffusion]]
- [[cite:&Kennedy_2009_TQM]]
- Alessandro Piazza, Eric Abrahamson: 2020: Fads and Fashions in Management Practices: Taking Stock and Looking Forward: [[cite:&Pizza_Abrahamson_2020_fads]]
  
- Timothy B. Clark 2004: The Fashion of Management Fashion: a Surge Too Far?
  [[cite:&Clark_2004_surge]]
  also refer to [[cite:&Gill_Whittle_1993_panacea]] as having come up with the idea

  

hmm could treat closing as abandoment of PMs on part of founder -> BvD
*PMs is actually not really management fashion, just actual fashion*
maybe see which works gets cited as fashion overall by by [[cite:&Pizza_Abrahamson_2020_fads;&Abrahamson_1996_fashion;&Abrahamson_1999_fashion;&Gill_Whittle_1993_panacea]]



*** https://www.researchrabbit.ai/mission

kinda works, but can't filter by date
also always 50 papers -> can't filter

Lounsbury 2003: social movements, field frames and industry emergence: a cultural political persepective on US recycling
[[cite:&Lounsbury_Ventresca_Hirsch_2003_recycling]]

Carroll: 20 : organization, productd and corporate demography
[[cite:&Poston_2019_population]], [[cite:&Carroll_Khessina_2019_demography]]

Helen Haugh & Paul Robson & John Hagedoorn & Kate Sugar: 2021: The nascent ecology of social enterprise
[[cite:&Haugh_etal_2021_nascent]]

*** https://www.cocites.com
seems to have gone nowhere                          
*** https://www.semanticscholar.org/

*** elicit https://elicit.org

https://www.sciencedirect.com/science/article/pii/S0148296314001684



*** semantic scholar
*** web of science


** angles
organizational lit
fashion/luxury consumption
philanthropy

does environment matter? or is it all about organizational characteristics? resourcss, whether founder loses interest

-> maybe better: how does environment matter, which parts of it?
--> need to specify dimensions, but there's probably not so much material dependence




** hypotheses

*** inertia I (name I)

**** concept
inertia

**** text
[[textcite:&Carroll_Khessina_2019_demography]] argue due to inertia that organizational transformation are difficult, especially of core features such as authority, technology and marketing strategy.
#
Inertia can also be cognitive; characterized by adherence to taken-for-granted categories and blueprints as well as organizational identity. 
#
One component of organizational identity is the name of an organization.
# 
(*Barnett, Pontikes*) argue that the name can constrain organizational transformation, such as in the case of banks who were less likely to transform if they included the region in which they were initially active in their name. 
#
Similarly, inclusion of the name of the founder may be an indicator of organizational inertia, and thus decrease probability of transforming the private museum into a different organizational form. 


**** data 
PMDB on whether founder's name is in museum name


*** inertia II (death)

**** concept
inertia
resources? 

**** text

change in authority (core feature)
also commitment of children less clear -> resources


**** data
death in PMDB: just 1 for PMs after founder died?


there's also some funny interaction specification with years after death [[cite:&Carroll_Khessina_2019_demography]]: p.527

original approach: whether mortality increases after organizational change

could also be non-linear: if organization survives transition, it's stable (red queen, trial by fire)



*** categorical imperative (name II)
**** concept
category adherence? [[cite:&Hsu_2005_forms;&Zuckerman_1999_illegitimacy]]



**** text
name indicates form (if forms are stable, there's something in the name)

[[cite:&Barnett_Fen_Luo_2012_identity]]: something about name, but not really
[[cite:&Glynn_Abzug_2002_names]]: seems more relevant.. 

**** data
PMDB: whether museum has "museum" in name, compare chance of dissolution with other names (institute, gallery)



*** categorical imperative II (recognition)
**** concept
recognition

**** text
recognition by third parties might
- give better access to art -> founder finds it more rewarding
- attract more audience -> more income
- attract more VIPs/HNWI -> better for networking

  

**** data
listed in MOW/IDA

*** government crackdown/
**** concept
regulation

**** text
[[cite:&Dupuy_Ron_Prakash_2014_crackdown]]

**** data
can use that of cite:&Dupuy_Ron_Prakash_2014_crackdown




*** organizational resources I: organizational characteristics

**** concept
resources

**** text
Firms depend on resources.
#
While non-profits do not have to run profitably (and are indeed often dependent on cash infusions or endowments), parts of the revenue are still gained from other income sources such as ticket sales and museum shop and restaurent income. 
#
liability of size: 
- [[cite:&Hager_2001_demise]],
- [[cite:&Carroll_Khessina_2019_demography]],
- 


Do these and other organizational characteristics reflect organizational resources, which in turn affect survival chances? 


**** data

actual measures:
- PMDB: endowment

proxies of organizational resources:
- PMDB: room size
- PMDB: collection size
- PMBD: employees
- PMDB: activities
- Artfacts: number of shows in organization


*** organizational resources II: founder inflows

**** concept
resources

**** text
Organizations depend on resources.
#
Given that PMs are often non-profits, they are often dependent on cash inflows from their founders.
#
[[cite:&Velthuis_Gera_forthcoming_fragility;&Velthuis_2007_talking]]: debt as one of the few contexts (next to death and divorce) which legitimate selling of artworks.
#
Thus, declining financial status of founders might lead to higher probability of closure. 



**** data
BvD: how firms of founders are doing
PMBD: whether wealth is available


*** organizational resources III: tax incentives 
**** concept
resources

**** text
Organizations depend on resources.
#
NPOs, and PMs in particular, depend on donors.
#
Higher TMITR increase the tax incentives as they increase the amount the amount of money returned.
#
Hypothesis: higher TMITR -> lower mortality

maybe this can be a contribution?
search the non-profit closing literature and its references and citations

use semantic scholar

**** data
Top marginal income tax rates: 
can use correlated random effects


*** environment resources
**** concept
resources

**** text
resources in environment matter

Museums need to exhibit artists to audiences, without either the legitimacy/purpose of the museums declines?

But could be that art can just be imported globally -> local supply doesn't matter much?
althrough IIRC the

more local shows/PMDB -> lower mortality?
# but this could also be competition -> resources basically turns pretty quickly into density dependence


**** data
PMDB density: could be proxy for how much art there is?

Artfacts: number of shows on NUTS/1/2/3/city level:
might measure both artists (supply) and audiences (demand)



*** firm diversity
**** concept
firm diversity
# seems to develop into capabilities pretty quickly


**** text
if organizations have more diversity (rather capabilities), they can better adopt to changing circumstances

**** data
PMDB: diversity of collection in terms of genre/medium/regional focus



*** environmental diversity
**** concept
diversity

**** text
[[cite:&Carroll_Khessina_2019_demography]] argue that the diversity of the organization population influences mortality 
# do they? 

**** data
Artfacts: diversity of stuff in terms of genre/medium exhibited
# do we have medium? not atm, but artfacts has..
# could also have gender/country/age diversity



*** match between collection genre content and local art supply

**** concept

match between collection genre content and local art supply

**** text
organizations might thrive better in contexts where they have easy access to the resources that they rely on.
[[cite:&Carroll_Khessina_2019_demography]]

**** data
Artfacts: overlap between collection focus and supply
# don't have artfacts medium/genre tho.. 



*** density -> control


*** cooperation
**** concept
ties, capabilities

**** text
[[cite:&Carroll_Khessina_2019_demography]]: has something on mutualism
p. 529: "ties with important actors"

not clear what those ties provide tho: is not really money, or business opportunity
could rather be indicator of organizational resources


**** data
pmdb: cooperation with other organizations






